// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=contracts_mock.go -package=modelexecution
//

// Package modelexecution is a generated GoMock package.
package modelexecution

import (
	context "context"
	reflect "reflect"

	model "github.com/n-r-w/glyph/host/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockProviderAttempt is a mock of ProviderAttempt interface.
type MockProviderAttempt struct {
	ctrl     *gomock.Controller
	recorder *MockProviderAttemptMockRecorder
	isgomock struct{}
}

// MockProviderAttemptMockRecorder is the mock recorder for MockProviderAttempt.
type MockProviderAttemptMockRecorder struct {
	mock *MockProviderAttempt
}

// NewMockProviderAttempt creates a new mock instance.
func NewMockProviderAttempt(ctrl *gomock.Controller) *MockProviderAttempt {
	mock := &MockProviderAttempt{ctrl: ctrl}
	mock.recorder = &MockProviderAttemptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderAttempt) EXPECT() *MockProviderAttemptMockRecorder {
	return m.recorder
}

// Stream mocks base method.
func (m *MockProviderAttempt) Stream(ctx context.Context, request ProviderRequest, handle StreamHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, request, handle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stream indicates an expected call of Stream.
func (mr *MockProviderAttemptMockRecorder) Stream(ctx, request, handle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockProviderAttempt)(nil).Stream), ctx, request, handle)
}

// MockConversationContext is a mock of ConversationContext interface.
type MockConversationContext struct {
	ctrl     *gomock.Controller
	recorder *MockConversationContextMockRecorder
	isgomock struct{}
}

// MockConversationContextMockRecorder is the mock recorder for MockConversationContext.
type MockConversationContextMockRecorder struct {
	mock *MockConversationContext
}

// NewMockConversationContext creates a new mock instance.
func NewMockConversationContext(ctrl *gomock.Controller) *MockConversationContext {
	mock := &MockConversationContext{ctrl: ctrl}
	mock.recorder = &MockConversationContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationContext) EXPECT() *MockConversationContextMockRecorder {
	return m.recorder
}

// ObserveCompletedConversation mocks base method.
func (m *MockConversationContext) ObserveCompletedConversation(request ProviderRequest, response model.Response) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveCompletedConversation", request, response)
}

// ObserveCompletedConversation indicates an expected call of ObserveCompletedConversation.
func (mr *MockConversationContextMockRecorder) ObserveCompletedConversation(request, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveCompletedConversation", reflect.TypeOf((*MockConversationContext)(nil).ObserveCompletedConversation), request, response)
}

// MockCatalogResolver is a mock of CatalogResolver interface.
type MockCatalogResolver struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogResolverMockRecorder
	isgomock struct{}
}

// MockCatalogResolverMockRecorder is the mock recorder for MockCatalogResolver.
type MockCatalogResolverMockRecorder struct {
	mock *MockCatalogResolver
}

// NewMockCatalogResolver creates a new mock instance.
func NewMockCatalogResolver(ctrl *gomock.Controller) *MockCatalogResolver {
	mock := &MockCatalogResolver{ctrl: ctrl}
	mock.recorder = &MockCatalogResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogResolver) EXPECT() *MockCatalogResolverMockRecorder {
	return m.recorder
}

// ActiveBinding mocks base method.
func (m *MockCatalogResolver) ActiveBinding() CatalogBinding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveBinding")
	ret0, _ := ret[0].(CatalogBinding)
	return ret0
}

// ActiveBinding indicates an expected call of ActiveBinding.
func (mr *MockCatalogResolverMockRecorder) ActiveBinding() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveBinding", reflect.TypeOf((*MockCatalogResolver)(nil).ActiveBinding))
}

// ResolveBinding mocks base method.
func (m *MockCatalogResolver) ResolveBinding(selection model.Selection) (CatalogBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveBinding", selection)
	ret0, _ := ret[0].(CatalogBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveBinding indicates an expected call of ResolveBinding.
func (mr *MockCatalogResolverMockRecorder) ResolveBinding(selection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveBinding", reflect.TypeOf((*MockCatalogResolver)(nil).ResolveBinding), selection)
}

// ResolveConfiguredBinding mocks base method.
func (m *MockCatalogResolver) ResolveConfiguredBinding(ctx context.Context, selection model.Selection) (CatalogBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveConfiguredBinding", ctx, selection)
	ret0, _ := ret[0].(CatalogBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveConfiguredBinding indicates an expected call of ResolveConfiguredBinding.
func (mr *MockCatalogResolverMockRecorder) ResolveConfiguredBinding(ctx, selection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveConfiguredBinding", reflect.TypeOf((*MockCatalogResolver)(nil).ResolveConfiguredBinding), ctx, selection)
}
