// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=extension
//

// Package extension is a generated GoMock package.
package extension

import (
	context "context"
	reflect "reflect"

	agent "github.com/n-r-w/glyph/host/internal/domain/agent"
	extension "github.com/n-r-w/glyph/host/internal/domain/extension"
	model "github.com/n-r-w/glyph/host/internal/domain/model"
	session "github.com/n-r-w/glyph/host/internal/domain/session"
	mo "github.com/samber/mo"
	gomock "go.uber.org/mock/gomock"
)

// MockModelOperations is a mock of ModelOperations interface.
type MockModelOperations struct {
	ctrl     *gomock.Controller
	recorder *MockModelOperationsMockRecorder
	isgomock struct{}
}

// MockModelOperationsMockRecorder is the mock recorder for MockModelOperations.
type MockModelOperationsMockRecorder struct {
	mock *MockModelOperations
}

// NewMockModelOperations creates a new mock instance.
func NewMockModelOperations(ctrl *gomock.Controller) *MockModelOperations {
	mock := &MockModelOperations{ctrl: ctrl}
	mock.recorder = &MockModelOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelOperations) EXPECT() *MockModelOperationsMockRecorder {
	return m.recorder
}

// ReadModels mocks base method.
func (m *MockModelOperations) ReadModels(ctx context.Context, extensionID, runtimeID string, reference extension.ContextRef) (ModelCatalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadModels", ctx, extensionID, runtimeID, reference)
	ret0, _ := ret[0].(ModelCatalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadModels indicates an expected call of ReadModels.
func (mr *MockModelOperationsMockRecorder) ReadModels(ctx, extensionID, runtimeID, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadModels", reflect.TypeOf((*MockModelOperations)(nil).ReadModels), ctx, extensionID, runtimeID, reference)
}

// ReadProviders mocks base method.
func (m *MockModelOperations) ReadProviders(ctx context.Context, extensionID, runtimeID string, reference extension.ContextRef) ([]Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadProviders", ctx, extensionID, runtimeID, reference)
	ret0, _ := ret[0].([]Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadProviders indicates an expected call of ReadProviders.
func (mr *MockModelOperationsMockRecorder) ReadProviders(ctx, extensionID, runtimeID, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadProviders", reflect.TypeOf((*MockModelOperations)(nil).ReadProviders), ctx, extensionID, runtimeID, reference)
}

// Request mocks base method.
func (m *MockModelOperations) Request(ctx context.Context, extensionID, runtimeID string, reference extension.ContextRef, selection model.Selection, instructions string, history []agent.HistoryEntry, progress func(ConfiguredRetryProgress) error) (model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, extensionID, runtimeID, reference, selection, instructions, history, progress)
	ret0, _ := ret[0].(model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockModelOperationsMockRecorder) Request(ctx, extensionID, runtimeID, reference, selection, instructions, history, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockModelOperations)(nil).Request), ctx, extensionID, runtimeID, reference, selection, instructions, history, progress)
}

// MockCompactionGate is a mock of CompactionGate interface.
type MockCompactionGate struct {
	ctrl     *gomock.Controller
	recorder *MockCompactionGateMockRecorder
	isgomock struct{}
}

// MockCompactionGateMockRecorder is the mock recorder for MockCompactionGate.
type MockCompactionGateMockRecorder struct {
	mock *MockCompactionGate
}

// NewMockCompactionGate creates a new mock instance.
func NewMockCompactionGate(ctrl *gomock.Controller) *MockCompactionGate {
	mock := &MockCompactionGate{ctrl: ctrl}
	mock.recorder = &MockCompactionGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompactionGate) EXPECT() *MockCompactionGateMockRecorder {
	return m.recorder
}

// TryAcquire mocks base method.
func (m *MockCompactionGate) TryAcquire() (func(), bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquire")
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// TryAcquire indicates an expected call of TryAcquire.
func (mr *MockCompactionGateMockRecorder) TryAcquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquire", reflect.TypeOf((*MockCompactionGate)(nil).TryAcquire))
}

// MockCompactionOperations is a mock of CompactionOperations interface.
type MockCompactionOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCompactionOperationsMockRecorder
	isgomock struct{}
}

// MockCompactionOperationsMockRecorder is the mock recorder for MockCompactionOperations.
type MockCompactionOperationsMockRecorder struct {
	mock *MockCompactionOperations
}

// NewMockCompactionOperations creates a new mock instance.
func NewMockCompactionOperations(ctrl *gomock.Controller) *MockCompactionOperations {
	mock := &MockCompactionOperations{ctrl: ctrl}
	mock.recorder = &MockCompactionOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompactionOperations) EXPECT() *MockCompactionOperationsMockRecorder {
	return m.recorder
}

// CompactExtension mocks base method.
func (m *MockCompactionOperations) CompactExtension(arg0 context.Context, arg1, arg2 string, arg3 extension.ContextRef, arg4 mo.Option[string]) (CompactionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompactExtension", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(CompactionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompactExtension indicates an expected call of CompactExtension.
func (mr *MockCompactionOperationsMockRecorder) CompactExtension(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompactExtension", reflect.TypeOf((*MockCompactionOperations)(nil).CompactExtension), arg0, arg1, arg2, arg3, arg4)
}

// MockContextOperations is a mock of ContextOperations interface.
type MockContextOperations struct {
	ctrl     *gomock.Controller
	recorder *MockContextOperationsMockRecorder
	isgomock struct{}
}

// MockContextOperationsMockRecorder is the mock recorder for MockContextOperations.
type MockContextOperationsMockRecorder struct {
	mock *MockContextOperations
}

// NewMockContextOperations creates a new mock instance.
func NewMockContextOperations(ctrl *gomock.Controller) *MockContextOperations {
	mock := &MockContextOperations{ctrl: ctrl}
	mock.recorder = &MockContextOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextOperations) EXPECT() *MockContextOperationsMockRecorder {
	return m.recorder
}

// AppendExtension mocks base method.
func (m *MockContextOperations) AppendExtension(ctx context.Context, extensionID, runtimeID string, reference extension.ContextRef, entryType string, data []byte) (session.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExtension", ctx, extensionID, runtimeID, reference, entryType, data)
	ret0, _ := ret[0].(session.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendExtension indicates an expected call of AppendExtension.
func (mr *MockContextOperationsMockRecorder) AppendExtension(ctx, extensionID, runtimeID, reference, entryType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExtension", reflect.TypeOf((*MockContextOperations)(nil).AppendExtension), ctx, extensionID, runtimeID, reference, entryType, data)
}

// AppendExtensionMessage mocks base method.
func (m *MockContextOperations) AppendExtensionMessage(ctx context.Context, extensionID, runtimeID string, reference extension.ContextRef, entryType, text string, visibility session.ClientVisibility) (AppendMessageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExtensionMessage", ctx, extensionID, runtimeID, reference, entryType, text, visibility)
	ret0, _ := ret[0].(AppendMessageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendExtensionMessage indicates an expected call of AppendExtensionMessage.
func (mr *MockContextOperationsMockRecorder) AppendExtensionMessage(ctx, extensionID, runtimeID, reference, entryType, text, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExtensionMessage", reflect.TypeOf((*MockContextOperations)(nil).AppendExtensionMessage), ctx, extensionID, runtimeID, reference, entryType, text, visibility)
}

// ReadSessionState mocks base method.
func (m *MockContextOperations) ReadSessionState(ctx context.Context, extensionID, runtimeID string, reference extension.ContextRef) (SessionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSessionState", ctx, extensionID, runtimeID, reference)
	ret0, _ := ret[0].(SessionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSessionState indicates an expected call of ReadSessionState.
func (mr *MockContextOperationsMockRecorder) ReadSessionState(ctx, extensionID, runtimeID, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSessionState", reflect.TypeOf((*MockContextOperations)(nil).ReadSessionState), ctx, extensionID, runtimeID, reference)
}

// ValidateContext mocks base method.
func (m *MockContextOperations) ValidateContext(extensionID, runtimeID string, reference extension.ContextRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContext", extensionID, runtimeID, reference)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateContext indicates an expected call of ValidateContext.
func (mr *MockContextOperationsMockRecorder) ValidateContext(extensionID, runtimeID, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContext", reflect.TypeOf((*MockContextOperations)(nil).ValidateContext), extensionID, runtimeID, reference)
}

// MockPreparedSelection is a mock of PreparedSelection interface.
type MockPreparedSelection struct {
	ctrl     *gomock.Controller
	recorder *MockPreparedSelectionMockRecorder
	isgomock struct{}
}

// MockPreparedSelectionMockRecorder is the mock recorder for MockPreparedSelection.
type MockPreparedSelectionMockRecorder struct {
	mock *MockPreparedSelection
}

// NewMockPreparedSelection creates a new mock instance.
func NewMockPreparedSelection(ctrl *gomock.Controller) *MockPreparedSelection {
	mock := &MockPreparedSelection{ctrl: ctrl}
	mock.recorder = &MockPreparedSelectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreparedSelection) EXPECT() *MockPreparedSelectionMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockPreparedSelection) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockPreparedSelectionMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPreparedSelection)(nil).Release))
}

// Run mocks base method.
func (m *MockPreparedSelection) Run(arg0 context.Context) SelectionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(SelectionResult)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockPreparedSelectionMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPreparedSelection)(nil).Run), arg0)
}

// MockModelSelection is a mock of ModelSelection interface.
type MockModelSelection struct {
	ctrl     *gomock.Controller
	recorder *MockModelSelectionMockRecorder
	isgomock struct{}
}

// MockModelSelectionMockRecorder is the mock recorder for MockModelSelection.
type MockModelSelectionMockRecorder struct {
	mock *MockModelSelection
}

// NewMockModelSelection creates a new mock instance.
func NewMockModelSelection(ctrl *gomock.Controller) *MockModelSelection {
	mock := &MockModelSelection{ctrl: ctrl}
	mock.recorder = &MockModelSelectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelSelection) EXPECT() *MockModelSelectionMockRecorder {
	return m.recorder
}

// PrepareExtensionSelection mocks base method.
func (m *MockModelSelection) PrepareExtensionSelection(arg0 SelectionCommand) (PreparedSelection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareExtensionSelection", arg0)
	ret0, _ := ret[0].(PreparedSelection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareExtensionSelection indicates an expected call of PrepareExtensionSelection.
func (mr *MockModelSelectionMockRecorder) PrepareExtensionSelection(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareExtensionSelection", reflect.TypeOf((*MockModelSelection)(nil).PrepareExtensionSelection), arg0)
}

// MockSelectionFailure is a mock of SelectionFailure interface.
type MockSelectionFailure struct {
	ctrl     *gomock.Controller
	recorder *MockSelectionFailureMockRecorder
	isgomock struct{}
}

// MockSelectionFailureMockRecorder is the mock recorder for MockSelectionFailure.
type MockSelectionFailureMockRecorder struct {
	mock *MockSelectionFailure
}

// NewMockSelectionFailure creates a new mock instance.
func NewMockSelectionFailure(ctrl *gomock.Controller) *MockSelectionFailure {
	mock := &MockSelectionFailure{ctrl: ctrl}
	mock.recorder = &MockSelectionFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSelectionFailure) EXPECT() *MockSelectionFailureMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockSelectionFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockSelectionFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSelectionFailure)(nil).Error))
}

// ModelSelectionCode mocks base method.
func (m *MockSelectionFailure) ModelSelectionCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelSelectionCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// ModelSelectionCode indicates an expected call of ModelSelectionCode.
func (mr *MockSelectionFailureMockRecorder) ModelSelectionCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelSelectionCode", reflect.TypeOf((*MockSelectionFailure)(nil).ModelSelectionCode))
}

// MockModelFailure is a mock of ModelFailure interface.
type MockModelFailure struct {
	ctrl     *gomock.Controller
	recorder *MockModelFailureMockRecorder
	isgomock struct{}
}

// MockModelFailureMockRecorder is the mock recorder for MockModelFailure.
type MockModelFailureMockRecorder struct {
	mock *MockModelFailure
}

// NewMockModelFailure creates a new mock instance.
func NewMockModelFailure(ctrl *gomock.Controller) *MockModelFailure {
	mock := &MockModelFailure{ctrl: ctrl}
	mock.recorder = &MockModelFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelFailure) EXPECT() *MockModelFailureMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockModelFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockModelFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockModelFailure)(nil).Error))
}

// ModelCode mocks base method.
func (m *MockModelFailure) ModelCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// ModelCode indicates an expected call of ModelCode.
func (mr *MockModelFailureMockRecorder) ModelCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelCode", reflect.TypeOf((*MockModelFailure)(nil).ModelCode))
}

// MockContextFailure is a mock of ContextFailure interface.
type MockContextFailure struct {
	ctrl     *gomock.Controller
	recorder *MockContextFailureMockRecorder
	isgomock struct{}
}

// MockContextFailureMockRecorder is the mock recorder for MockContextFailure.
type MockContextFailureMockRecorder struct {
	mock *MockContextFailure
}

// NewMockContextFailure creates a new mock instance.
func NewMockContextFailure(ctrl *gomock.Controller) *MockContextFailure {
	mock := &MockContextFailure{ctrl: ctrl}
	mock.recorder = &MockContextFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextFailure) EXPECT() *MockContextFailureMockRecorder {
	return m.recorder
}

// ContextCode mocks base method.
func (m *MockContextFailure) ContextCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// ContextCode indicates an expected call of ContextCode.
func (mr *MockContextFailureMockRecorder) ContextCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextCode", reflect.TypeOf((*MockContextFailure)(nil).ContextCode))
}

// Error mocks base method.
func (m *MockContextFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockContextFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockContextFailure)(nil).Error))
}

// MockRuntimeOperations is a mock of RuntimeOperations interface.
type MockRuntimeOperations struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeOperationsMockRecorder
	isgomock struct{}
}

// MockRuntimeOperationsMockRecorder is the mock recorder for MockRuntimeOperations.
type MockRuntimeOperationsMockRecorder struct {
	mock *MockRuntimeOperations
}

// NewMockRuntimeOperations creates a new mock instance.
func NewMockRuntimeOperations(ctrl *gomock.Controller) *MockRuntimeOperations {
	mock := &MockRuntimeOperations{ctrl: ctrl}
	mock.recorder = &MockRuntimeOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeOperations) EXPECT() *MockRuntimeOperationsMockRecorder {
	return m.recorder
}

// BeginContextOperation mocks base method.
func (m *MockRuntimeOperations) BeginContextOperation(ctx context.Context, extensionID, runtimeID string) (func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginContextOperation", ctx, extensionID, runtimeID)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginContextOperation indicates an expected call of BeginContextOperation.
func (mr *MockRuntimeOperationsMockRecorder) BeginContextOperation(ctx, extensionID, runtimeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginContextOperation", reflect.TypeOf((*MockRuntimeOperations)(nil).BeginContextOperation), ctx, extensionID, runtimeID)
}
