// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: api/plugins/extension/v1/extension.proto

package extensionv1

import (
	v1 "github.com/n-r-w/glyph/pkg/operation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenRequest carries one Host operation request or close request.
type OpenRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OperationId *string                `protobuf:"bytes,1,opt,name=operation_id,json=operationId"`
	xxx_hidden_Content     isOpenRequest_Content  `protobuf_oneof:"content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpenRequest) GetOperationId() string {
	if x != nil {
		if x.xxx_hidden_OperationId != nil {
			return *x.xxx_hidden_OperationId
		}
		return ""
	}
	return ""
}

func (x *OpenRequest) GetRequest() *HostRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*openRequest_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *OpenRequest) GetClose() *v1.CloseConnection {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*openRequest_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *OpenRequest) SetOperationId(v string) {
	x.xxx_hidden_OperationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OpenRequest) SetRequest(v *HostRequest) {
	if v == nil {
		x.xxx_hidden_Content = nil
		return
	}
	x.xxx_hidden_Content = &openRequest_Request{v}
}

func (x *OpenRequest) SetClose(v *v1.CloseConnection) {
	if v == nil {
		x.xxx_hidden_Content = nil
		return
	}
	x.xxx_hidden_Content = &openRequest_Close{v}
}

func (x *OpenRequest) HasOperationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpenRequest) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *OpenRequest) HasRequest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*openRequest_Request)
	return ok
}

func (x *OpenRequest) HasClose() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*openRequest_Close)
	return ok
}

func (x *OpenRequest) ClearOperationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OperationId = nil
}

func (x *OpenRequest) ClearContent() {
	x.xxx_hidden_Content = nil
}

func (x *OpenRequest) ClearRequest() {
	if _, ok := x.xxx_hidden_Content.(*openRequest_Request); ok {
		x.xxx_hidden_Content = nil
	}
}

func (x *OpenRequest) ClearClose() {
	if _, ok := x.xxx_hidden_Content.(*openRequest_Close); ok {
		x.xxx_hidden_Content = nil
	}
}

const OpenRequest_Content_not_set_case case_OpenRequest_Content = 0
const OpenRequest_Request_case case_OpenRequest_Content = 2
const OpenRequest_Close_case case_OpenRequest_Content = 3

func (x *OpenRequest) WhichContent() case_OpenRequest_Content {
	if x == nil {
		return OpenRequest_Content_not_set_case
	}
	switch x.xxx_hidden_Content.(type) {
	case *openRequest_Request:
		return OpenRequest_Request_case
	case *openRequest_Close:
		return OpenRequest_Close_case
	default:
		return OpenRequest_Content_not_set_case
	}
}

type OpenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The operation identifier for operation requests.
	OperationId *string
	// The stream content.

	// Fields of oneof xxx_hidden_Content:
	Request *HostRequest
	Close   *v1.CloseConnection
	// -- end of xxx_hidden_Content
}

func (b0 OpenRequest_builder) Build() *OpenRequest {
	m0 := &OpenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OperationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_OperationId = b.OperationId
	}
	if b.Request != nil {
		x.xxx_hidden_Content = &openRequest_Request{b.Request}
	}
	if b.Close != nil {
		x.xxx_hidden_Content = &openRequest_Close{b.Close}
	}
	return m0
}

type case_OpenRequest_Content protoreflect.FieldNumber

func (x case_OpenRequest_Content) String() string {
	md := file_api_plugins_extension_v1_extension_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOpenRequest_Content interface {
	isOpenRequest_Content()
}

type openRequest_Request struct {
	Request *HostRequest `protobuf:"bytes,2,opt,name=request,oneof"`
}

type openRequest_Close struct {
	Close *v1.CloseConnection `protobuf:"bytes,3,opt,name=close,oneof"`
}

func (*openRequest_Request) isOpenRequest_Content() {}

func (*openRequest_Close) isOpenRequest_Content() {}

// OpenResponse carries one extension operation lifecycle event.
type OpenResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OperationId *string                `protobuf:"bytes,1,opt,name=operation_id,json=operationId"`
	xxx_hidden_Content     isOpenResponse_Content `protobuf_oneof:"content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpenResponse) GetOperationId() string {
	if x != nil {
		if x.xxx_hidden_OperationId != nil {
			return *x.xxx_hidden_OperationId
		}
		return ""
	}
	return ""
}

func (x *OpenResponse) GetEvent() *ExtensionEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*openResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *OpenResponse) SetOperationId(v string) {
	x.xxx_hidden_OperationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OpenResponse) SetEvent(v *ExtensionEvent) {
	if v == nil {
		x.xxx_hidden_Content = nil
		return
	}
	x.xxx_hidden_Content = &openResponse_Event{v}
}

func (x *OpenResponse) HasOperationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpenResponse) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *OpenResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*openResponse_Event)
	return ok
}

func (x *OpenResponse) ClearOperationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OperationId = nil
}

func (x *OpenResponse) ClearContent() {
	x.xxx_hidden_Content = nil
}

func (x *OpenResponse) ClearEvent() {
	if _, ok := x.xxx_hidden_Content.(*openResponse_Event); ok {
		x.xxx_hidden_Content = nil
	}
}

const OpenResponse_Content_not_set_case case_OpenResponse_Content = 0
const OpenResponse_Event_case case_OpenResponse_Content = 2

func (x *OpenResponse) WhichContent() case_OpenResponse_Content {
	if x == nil {
		return OpenResponse_Content_not_set_case
	}
	switch x.xxx_hidden_Content.(type) {
	case *openResponse_Event:
		return OpenResponse_Event_case
	default:
		return OpenResponse_Content_not_set_case
	}
}

type OpenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The operation identifier for lifecycle events.
	OperationId *string
	// The stream content.

	// Fields of oneof xxx_hidden_Content:
	Event *ExtensionEvent
	// -- end of xxx_hidden_Content
}

func (b0 OpenResponse_builder) Build() *OpenResponse {
	m0 := &OpenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OperationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_OperationId = b.OperationId
	}
	if b.Event != nil {
		x.xxx_hidden_Content = &openResponse_Event{b.Event}
	}
	return m0
}

type case_OpenResponse_Content protoreflect.FieldNumber

func (x case_OpenResponse_Content) String() string {
	md := file_api_plugins_extension_v1_extension_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOpenResponse_Content interface {
	isOpenResponse_Content()
}

type openResponse_Event struct {
	Event *ExtensionEvent `protobuf:"bytes,2,opt,name=event,oneof"`
}

func (*openResponse_Event) isOpenResponse_Content() {}

// HostRequest carries exactly one Host-initiated operation kind.
type HostRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Request isHostRequest_Request  `protobuf_oneof:"request"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HostRequest) Reset() {
	*x = HostRequest{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequest) ProtoMessage() {}

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HostRequest) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Request.(*hostRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *HostRequest) GetHandle() *HandleRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Request.(*hostRequest_Handle); ok {
			return x.Handle
		}
	}
	return nil
}

func (x *HostRequest) GetExecute() *ExecuteRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Request.(*hostRequest_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *HostRequest) GetCancel() *v1.CancelOperation {
	if x != nil {
		if x, ok := x.xxx_hidden_Request.(*hostRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *HostRequest) SetRegister(v *RegisterRequest) {
	if v == nil {
		x.xxx_hidden_Request = nil
		return
	}
	x.xxx_hidden_Request = &hostRequest_Register{v}
}

func (x *HostRequest) SetHandle(v *HandleRequest) {
	if v == nil {
		x.xxx_hidden_Request = nil
		return
	}
	x.xxx_hidden_Request = &hostRequest_Handle{v}
}

func (x *HostRequest) SetExecute(v *ExecuteRequest) {
	if v == nil {
		x.xxx_hidden_Request = nil
		return
	}
	x.xxx_hidden_Request = &hostRequest_Execute{v}
}

func (x *HostRequest) SetCancel(v *v1.CancelOperation) {
	if v == nil {
		x.xxx_hidden_Request = nil
		return
	}
	x.xxx_hidden_Request = &hostRequest_Cancel{v}
}

func (x *HostRequest) HasRequest() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Request != nil
}

func (x *HostRequest) HasRegister() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Request.(*hostRequest_Register)
	return ok
}

func (x *HostRequest) HasHandle() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Request.(*hostRequest_Handle)
	return ok
}

func (x *HostRequest) HasExecute() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Request.(*hostRequest_Execute)
	return ok
}

func (x *HostRequest) HasCancel() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Request.(*hostRequest_Cancel)
	return ok
}

func (x *HostRequest) ClearRequest() {
	x.xxx_hidden_Request = nil
}

func (x *HostRequest) ClearRegister() {
	if _, ok := x.xxx_hidden_Request.(*hostRequest_Register); ok {
		x.xxx_hidden_Request = nil
	}
}

func (x *HostRequest) ClearHandle() {
	if _, ok := x.xxx_hidden_Request.(*hostRequest_Handle); ok {
		x.xxx_hidden_Request = nil
	}
}

func (x *HostRequest) ClearExecute() {
	if _, ok := x.xxx_hidden_Request.(*hostRequest_Execute); ok {
		x.xxx_hidden_Request = nil
	}
}

func (x *HostRequest) ClearCancel() {
	if _, ok := x.xxx_hidden_Request.(*hostRequest_Cancel); ok {
		x.xxx_hidden_Request = nil
	}
}

const HostRequest_Request_not_set_case case_HostRequest_Request = 0
const HostRequest_Register_case case_HostRequest_Request = 1
const HostRequest_Handle_case case_HostRequest_Request = 2
const HostRequest_Execute_case case_HostRequest_Request = 3
const HostRequest_Cancel_case case_HostRequest_Request = 4

func (x *HostRequest) WhichRequest() case_HostRequest_Request {
	if x == nil {
		return HostRequest_Request_not_set_case
	}
	switch x.xxx_hidden_Request.(type) {
	case *hostRequest_Register:
		return HostRequest_Register_case
	case *hostRequest_Handle:
		return HostRequest_Handle_case
	case *hostRequest_Execute:
		return HostRequest_Execute_case
	case *hostRequest_Cancel:
		return HostRequest_Cancel_case
	default:
		return HostRequest_Request_not_set_case
	}
}

type HostRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The operation request.

	// Fields of oneof xxx_hidden_Request:
	Register *RegisterRequest
	Handle   *HandleRequest
	Execute  *ExecuteRequest
	Cancel   *v1.CancelOperation
	// -- end of xxx_hidden_Request
}

func (b0 HostRequest_builder) Build() *HostRequest {
	m0 := &HostRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Register != nil {
		x.xxx_hidden_Request = &hostRequest_Register{b.Register}
	}
	if b.Handle != nil {
		x.xxx_hidden_Request = &hostRequest_Handle{b.Handle}
	}
	if b.Execute != nil {
		x.xxx_hidden_Request = &hostRequest_Execute{b.Execute}
	}
	if b.Cancel != nil {
		x.xxx_hidden_Request = &hostRequest_Cancel{b.Cancel}
	}
	return m0
}

type case_HostRequest_Request protoreflect.FieldNumber

func (x case_HostRequest_Request) String() string {
	md := file_api_plugins_extension_v1_extension_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHostRequest_Request interface {
	isHostRequest_Request()
}

type hostRequest_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,oneof"`
}

type hostRequest_Handle struct {
	Handle *HandleRequest `protobuf:"bytes,2,opt,name=handle,oneof"`
}

type hostRequest_Execute struct {
	Execute *ExecuteRequest `protobuf:"bytes,3,opt,name=execute,oneof"`
}

type hostRequest_Cancel struct {
	Cancel *v1.CancelOperation `protobuf:"bytes,4,opt,name=cancel,oneof"`
}

func (*hostRequest_Register) isHostRequest_Request() {}

func (*hostRequest_Handle) isHostRequest_Request() {}

func (*hostRequest_Execute) isHostRequest_Request() {}

func (*hostRequest_Cancel) isHostRequest_Request() {}

// ExtensionEvent carries one lifecycle event for a Host-initiated operation.
type ExtensionEvent struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event isExtensionEvent_Event `protobuf_oneof:"event"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtensionEvent) Reset() {
	*x = ExtensionEvent{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionEvent) ProtoMessage() {}

func (x *ExtensionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExtensionEvent) GetAccepted() *v1.Accepted {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *ExtensionEvent) GetRunning() *v1.Running {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Running); ok {
			return x.Running
		}
	}
	return nil
}

func (x *ExtensionEvent) GetProgress() *ExtensionProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ExtensionEvent) GetCompleted() *ExtensionCompleted {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *ExtensionEvent) GetCanceled() *v1.Canceled {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Canceled); ok {
			return x.Canceled
		}
	}
	return nil
}

func (x *ExtensionEvent) GetFailed() *v1.Failed {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *ExtensionEvent) GetRejected() *v1.Rejected {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*extensionEvent_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *ExtensionEvent) SetAccepted(v *v1.Accepted) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Accepted{v}
}

func (x *ExtensionEvent) SetRunning(v *v1.Running) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Running{v}
}

func (x *ExtensionEvent) SetProgress(v *ExtensionProgress) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Progress{v}
}

func (x *ExtensionEvent) SetCompleted(v *ExtensionCompleted) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Completed{v}
}

func (x *ExtensionEvent) SetCanceled(v *v1.Canceled) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Canceled{v}
}

func (x *ExtensionEvent) SetFailed(v *v1.Failed) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Failed{v}
}

func (x *ExtensionEvent) SetRejected(v *v1.Rejected) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &extensionEvent_Rejected{v}
}

func (x *ExtensionEvent) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *ExtensionEvent) HasAccepted() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Accepted)
	return ok
}

func (x *ExtensionEvent) HasRunning() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Running)
	return ok
}

func (x *ExtensionEvent) HasProgress() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Progress)
	return ok
}

func (x *ExtensionEvent) HasCompleted() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Completed)
	return ok
}

func (x *ExtensionEvent) HasCanceled() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Canceled)
	return ok
}

func (x *ExtensionEvent) HasFailed() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Failed)
	return ok
}

func (x *ExtensionEvent) HasRejected() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*extensionEvent_Rejected)
	return ok
}

func (x *ExtensionEvent) ClearEvent() {
	x.xxx_hidden_Event = nil
}

func (x *ExtensionEvent) ClearAccepted() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Accepted); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *ExtensionEvent) ClearRunning() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Running); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *ExtensionEvent) ClearProgress() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Progress); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *ExtensionEvent) ClearCompleted() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Completed); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *ExtensionEvent) ClearCanceled() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Canceled); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *ExtensionEvent) ClearFailed() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Failed); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *ExtensionEvent) ClearRejected() {
	if _, ok := x.xxx_hidden_Event.(*extensionEvent_Rejected); ok {
		x.xxx_hidden_Event = nil
	}
}

const ExtensionEvent_Event_not_set_case case_ExtensionEvent_Event = 0
const ExtensionEvent_Accepted_case case_ExtensionEvent_Event = 1
const ExtensionEvent_Running_case case_ExtensionEvent_Event = 2
const ExtensionEvent_Progress_case case_ExtensionEvent_Event = 3
const ExtensionEvent_Completed_case case_ExtensionEvent_Event = 4
const ExtensionEvent_Canceled_case case_ExtensionEvent_Event = 5
const ExtensionEvent_Failed_case case_ExtensionEvent_Event = 6
const ExtensionEvent_Rejected_case case_ExtensionEvent_Event = 7

func (x *ExtensionEvent) WhichEvent() case_ExtensionEvent_Event {
	if x == nil {
		return ExtensionEvent_Event_not_set_case
	}
	switch x.xxx_hidden_Event.(type) {
	case *extensionEvent_Accepted:
		return ExtensionEvent_Accepted_case
	case *extensionEvent_Running:
		return ExtensionEvent_Running_case
	case *extensionEvent_Progress:
		return ExtensionEvent_Progress_case
	case *extensionEvent_Completed:
		return ExtensionEvent_Completed_case
	case *extensionEvent_Canceled:
		return ExtensionEvent_Canceled_case
	case *extensionEvent_Failed:
		return ExtensionEvent_Failed_case
	case *extensionEvent_Rejected:
		return ExtensionEvent_Rejected_case
	default:
		return ExtensionEvent_Event_not_set_case
	}
}

type ExtensionEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The lifecycle event.

	// Fields of oneof xxx_hidden_Event:
	Accepted  *v1.Accepted
	Running   *v1.Running
	Progress  *ExtensionProgress
	Completed *ExtensionCompleted
	Canceled  *v1.Canceled
	Failed    *v1.Failed
	Rejected  *v1.Rejected
	// -- end of xxx_hidden_Event
}

func (b0 ExtensionEvent_builder) Build() *ExtensionEvent {
	m0 := &ExtensionEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Accepted != nil {
		x.xxx_hidden_Event = &extensionEvent_Accepted{b.Accepted}
	}
	if b.Running != nil {
		x.xxx_hidden_Event = &extensionEvent_Running{b.Running}
	}
	if b.Progress != nil {
		x.xxx_hidden_Event = &extensionEvent_Progress{b.Progress}
	}
	if b.Completed != nil {
		x.xxx_hidden_Event = &extensionEvent_Completed{b.Completed}
	}
	if b.Canceled != nil {
		x.xxx_hidden_Event = &extensionEvent_Canceled{b.Canceled}
	}
	if b.Failed != nil {
		x.xxx_hidden_Event = &extensionEvent_Failed{b.Failed}
	}
	if b.Rejected != nil {
		x.xxx_hidden_Event = &extensionEvent_Rejected{b.Rejected}
	}
	return m0
}

type case_ExtensionEvent_Event protoreflect.FieldNumber

func (x case_ExtensionEvent_Event) String() string {
	md := file_api_plugins_extension_v1_extension_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isExtensionEvent_Event interface {
	isExtensionEvent_Event()
}

type extensionEvent_Accepted struct {
	Accepted *v1.Accepted `protobuf:"bytes,1,opt,name=accepted,oneof"`
}

type extensionEvent_Running struct {
	Running *v1.Running `protobuf:"bytes,2,opt,name=running,oneof"`
}

type extensionEvent_Progress struct {
	Progress *ExtensionProgress `protobuf:"bytes,3,opt,name=progress,oneof"`
}

type extensionEvent_Completed struct {
	Completed *ExtensionCompleted `protobuf:"bytes,4,opt,name=completed,oneof"`
}

type extensionEvent_Canceled struct {
	Canceled *v1.Canceled `protobuf:"bytes,5,opt,name=canceled,oneof"`
}

type extensionEvent_Failed struct {
	Failed *v1.Failed `protobuf:"bytes,6,opt,name=failed,oneof"`
}

type extensionEvent_Rejected struct {
	Rejected *v1.Rejected `protobuf:"bytes,7,opt,name=rejected,oneof"`
}

func (*extensionEvent_Accepted) isExtensionEvent_Event() {}

func (*extensionEvent_Running) isExtensionEvent_Event() {}

func (*extensionEvent_Progress) isExtensionEvent_Event() {}

func (*extensionEvent_Completed) isExtensionEvent_Event() {}

func (*extensionEvent_Canceled) isExtensionEvent_Event() {}

func (*extensionEvent_Failed) isExtensionEvent_Event() {}

func (*extensionEvent_Rejected) isExtensionEvent_Event() {}

// ExtensionProgress carries one operation-specific progress payload.
type ExtensionProgress struct {
	state               protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Progress isExtensionProgress_Progress `protobuf_oneof:"progress"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExtensionProgress) Reset() {
	*x = ExtensionProgress{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionProgress) ProtoMessage() {}

func (x *ExtensionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExtensionProgress) GetTool() *ToolProgress {
	if x != nil {
		if x, ok := x.xxx_hidden_Progress.(*extensionProgress_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *ExtensionProgress) SetTool(v *ToolProgress) {
	if v == nil {
		x.xxx_hidden_Progress = nil
		return
	}
	x.xxx_hidden_Progress = &extensionProgress_Tool{v}
}

func (x *ExtensionProgress) HasProgress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Progress != nil
}

func (x *ExtensionProgress) HasTool() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Progress.(*extensionProgress_Tool)
	return ok
}

func (x *ExtensionProgress) ClearProgress() {
	x.xxx_hidden_Progress = nil
}

func (x *ExtensionProgress) ClearTool() {
	if _, ok := x.xxx_hidden_Progress.(*extensionProgress_Tool); ok {
		x.xxx_hidden_Progress = nil
	}
}

const ExtensionProgress_Progress_not_set_case case_ExtensionProgress_Progress = 0
const ExtensionProgress_Tool_case case_ExtensionProgress_Progress = 1

func (x *ExtensionProgress) WhichProgress() case_ExtensionProgress_Progress {
	if x == nil {
		return ExtensionProgress_Progress_not_set_case
	}
	switch x.xxx_hidden_Progress.(type) {
	case *extensionProgress_Tool:
		return ExtensionProgress_Tool_case
	default:
		return ExtensionProgress_Progress_not_set_case
	}
}

type ExtensionProgress_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The progress payload.

	// Fields of oneof xxx_hidden_Progress:
	Tool *ToolProgress
	// -- end of xxx_hidden_Progress
}

func (b0 ExtensionProgress_builder) Build() *ExtensionProgress {
	m0 := &ExtensionProgress{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Tool != nil {
		x.xxx_hidden_Progress = &extensionProgress_Tool{b.Tool}
	}
	return m0
}

type case_ExtensionProgress_Progress protoreflect.FieldNumber

func (x case_ExtensionProgress_Progress) String() string {
	md := file_api_plugins_extension_v1_extension_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isExtensionProgress_Progress interface {
	isExtensionProgress_Progress()
}

type extensionProgress_Tool struct {
	Tool *ToolProgress `protobuf:"bytes,1,opt,name=tool,oneof"`
}

func (*extensionProgress_Tool) isExtensionProgress_Progress() {}

// ExtensionCompleted carries one operation-specific completed payload.
type ExtensionCompleted struct {
	state                protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Completed isExtensionCompleted_Completed `protobuf_oneof:"completed"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtensionCompleted) Reset() {
	*x = ExtensionCompleted{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionCompleted) ProtoMessage() {}

func (x *ExtensionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExtensionCompleted) GetRegister() *RegisterResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Completed.(*extensionCompleted_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ExtensionCompleted) GetHandle() *HandleResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Completed.(*extensionCompleted_Handle); ok {
			return x.Handle
		}
	}
	return nil
}

func (x *ExtensionCompleted) GetTool() *ToolResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Completed.(*extensionCompleted_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *ExtensionCompleted) GetCancel() *v1.CancelCompleted {
	if x != nil {
		if x, ok := x.xxx_hidden_Completed.(*extensionCompleted_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ExtensionCompleted) SetRegister(v *RegisterResponse) {
	if v == nil {
		x.xxx_hidden_Completed = nil
		return
	}
	x.xxx_hidden_Completed = &extensionCompleted_Register{v}
}

func (x *ExtensionCompleted) SetHandle(v *HandleResponse) {
	if v == nil {
		x.xxx_hidden_Completed = nil
		return
	}
	x.xxx_hidden_Completed = &extensionCompleted_Handle{v}
}

func (x *ExtensionCompleted) SetTool(v *ToolResult) {
	if v == nil {
		x.xxx_hidden_Completed = nil
		return
	}
	x.xxx_hidden_Completed = &extensionCompleted_Tool{v}
}

func (x *ExtensionCompleted) SetCancel(v *v1.CancelCompleted) {
	if v == nil {
		x.xxx_hidden_Completed = nil
		return
	}
	x.xxx_hidden_Completed = &extensionCompleted_Cancel{v}
}

func (x *ExtensionCompleted) HasCompleted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Completed != nil
}

func (x *ExtensionCompleted) HasRegister() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Completed.(*extensionCompleted_Register)
	return ok
}

func (x *ExtensionCompleted) HasHandle() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Completed.(*extensionCompleted_Handle)
	return ok
}

func (x *ExtensionCompleted) HasTool() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Completed.(*extensionCompleted_Tool)
	return ok
}

func (x *ExtensionCompleted) HasCancel() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Completed.(*extensionCompleted_Cancel)
	return ok
}

func (x *ExtensionCompleted) ClearCompleted() {
	x.xxx_hidden_Completed = nil
}

func (x *ExtensionCompleted) ClearRegister() {
	if _, ok := x.xxx_hidden_Completed.(*extensionCompleted_Register); ok {
		x.xxx_hidden_Completed = nil
	}
}

func (x *ExtensionCompleted) ClearHandle() {
	if _, ok := x.xxx_hidden_Completed.(*extensionCompleted_Handle); ok {
		x.xxx_hidden_Completed = nil
	}
}

func (x *ExtensionCompleted) ClearTool() {
	if _, ok := x.xxx_hidden_Completed.(*extensionCompleted_Tool); ok {
		x.xxx_hidden_Completed = nil
	}
}

func (x *ExtensionCompleted) ClearCancel() {
	if _, ok := x.xxx_hidden_Completed.(*extensionCompleted_Cancel); ok {
		x.xxx_hidden_Completed = nil
	}
}

const ExtensionCompleted_Completed_not_set_case case_ExtensionCompleted_Completed = 0
const ExtensionCompleted_Register_case case_ExtensionCompleted_Completed = 1
const ExtensionCompleted_Handle_case case_ExtensionCompleted_Completed = 2
const ExtensionCompleted_Tool_case case_ExtensionCompleted_Completed = 3
const ExtensionCompleted_Cancel_case case_ExtensionCompleted_Completed = 4

func (x *ExtensionCompleted) WhichCompleted() case_ExtensionCompleted_Completed {
	if x == nil {
		return ExtensionCompleted_Completed_not_set_case
	}
	switch x.xxx_hidden_Completed.(type) {
	case *extensionCompleted_Register:
		return ExtensionCompleted_Register_case
	case *extensionCompleted_Handle:
		return ExtensionCompleted_Handle_case
	case *extensionCompleted_Tool:
		return ExtensionCompleted_Tool_case
	case *extensionCompleted_Cancel:
		return ExtensionCompleted_Cancel_case
	default:
		return ExtensionCompleted_Completed_not_set_case
	}
}

type ExtensionCompleted_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The completed payload.

	// Fields of oneof xxx_hidden_Completed:
	Register *RegisterResponse
	Handle   *HandleResponse
	Tool     *ToolResult
	Cancel   *v1.CancelCompleted
	// -- end of xxx_hidden_Completed
}

func (b0 ExtensionCompleted_builder) Build() *ExtensionCompleted {
	m0 := &ExtensionCompleted{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Register != nil {
		x.xxx_hidden_Completed = &extensionCompleted_Register{b.Register}
	}
	if b.Handle != nil {
		x.xxx_hidden_Completed = &extensionCompleted_Handle{b.Handle}
	}
	if b.Tool != nil {
		x.xxx_hidden_Completed = &extensionCompleted_Tool{b.Tool}
	}
	if b.Cancel != nil {
		x.xxx_hidden_Completed = &extensionCompleted_Cancel{b.Cancel}
	}
	return m0
}

type case_ExtensionCompleted_Completed protoreflect.FieldNumber

func (x case_ExtensionCompleted_Completed) String() string {
	md := file_api_plugins_extension_v1_extension_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isExtensionCompleted_Completed interface {
	isExtensionCompleted_Completed()
}

type extensionCompleted_Register struct {
	Register *RegisterResponse `protobuf:"bytes,1,opt,name=register,oneof"`
}

type extensionCompleted_Handle struct {
	Handle *HandleResponse `protobuf:"bytes,2,opt,name=handle,oneof"`
}

type extensionCompleted_Tool struct {
	Tool *ToolResult `protobuf:"bytes,3,opt,name=tool,oneof"`
}

type extensionCompleted_Cancel struct {
	Cancel *v1.CancelCompleted `protobuf:"bytes,4,opt,name=cancel,oneof"`
}

func (*extensionCompleted_Register) isExtensionCompleted_Completed() {}

func (*extensionCompleted_Handle) isExtensionCompleted_Completed() {}

func (*extensionCompleted_Tool) isExtensionCompleted_Completed() {}

func (*extensionCompleted_Cancel) isExtensionCompleted_Completed() {}

// RegisterRequest has no fields because registration is fixed at startup.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// RegisterResponse contains the complete registration for one extension.
type RegisterResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tools    *[]*ToolDescriptor     `protobuf:"bytes,1,rep,name=tools"`
	xxx_hidden_Handlers *[]*HandlerDescriptor  `protobuf:"bytes,2,rep,name=handlers"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetTools() []*ToolDescriptor {
	if x != nil {
		if x.xxx_hidden_Tools != nil {
			return *x.xxx_hidden_Tools
		}
	}
	return nil
}

func (x *RegisterResponse) GetHandlers() []*HandlerDescriptor {
	if x != nil {
		if x.xxx_hidden_Handlers != nil {
			return *x.xxx_hidden_Handlers
		}
	}
	return nil
}

func (x *RegisterResponse) SetTools(v []*ToolDescriptor) {
	x.xxx_hidden_Tools = &v
}

func (x *RegisterResponse) SetHandlers(v []*HandlerDescriptor) {
	x.xxx_hidden_Handlers = &v
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The complete ordered tool catalog.
	Tools []*ToolDescriptor
	// The complete ordered session-tree handler catalog.
	Handlers []*HandlerDescriptor
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tools = &b.Tools
	x.xxx_hidden_Handlers = &b.Handlers
	return m0
}

var File_api_plugins_extension_v1_extension_proto protoreflect.FileDescriptor

const file_api_plugins_extension_v1_extension_proto_rawDesc = "" +
	"\n" +
	"(api/plugins/extension/v1/extension.proto\x12\x1aglyph.plugins.extension.v1\x1a api/operation/v1/operation.proto\x1a+api/plugins/extension/v1/session_tree.proto\x1a#api/plugins/extension/v1/tool.proto\"\xbd\x01\n" +
	"\vOpenRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12C\n" +
	"\arequest\x18\x02 \x01(\v2'.glyph.plugins.extension.v1.HostRequestH\x00R\arequest\x12;\n" +
	"\x05close\x18\x03 \x01(\v2#.glyph.operation.v1.CloseConnectionH\x00R\x05closeB\t\n" +
	"\acontent\"\x80\x01\n" +
	"\fOpenResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12B\n" +
	"\x05event\x18\x02 \x01(\v2*.glyph.plugins.extension.v1.ExtensionEventH\x00R\x05eventB\t\n" +
	"\acontent\"\xaf\x02\n" +
	"\vHostRequest\x12I\n" +
	"\bregister\x18\x01 \x01(\v2+.glyph.plugins.extension.v1.RegisterRequestH\x00R\bregister\x12C\n" +
	"\x06handle\x18\x02 \x01(\v2).glyph.plugins.extension.v1.HandleRequestH\x00R\x06handle\x12F\n" +
	"\aexecute\x18\x03 \x01(\v2*.glyph.plugins.extension.v1.ExecuteRequestH\x00R\aexecute\x12=\n" +
	"\x06cancel\x18\x04 \x01(\v2#.glyph.operation.v1.CancelOperationH\x00R\x06cancelB\t\n" +
	"\arequest\"\xd9\x03\n" +
	"\x0eExtensionEvent\x12:\n" +
	"\baccepted\x18\x01 \x01(\v2\x1c.glyph.operation.v1.AcceptedH\x00R\baccepted\x127\n" +
	"\arunning\x18\x02 \x01(\v2\x1b.glyph.operation.v1.RunningH\x00R\arunning\x12K\n" +
	"\bprogress\x18\x03 \x01(\v2-.glyph.plugins.extension.v1.ExtensionProgressH\x00R\bprogress\x12N\n" +
	"\tcompleted\x18\x04 \x01(\v2..glyph.plugins.extension.v1.ExtensionCompletedH\x00R\tcompleted\x12:\n" +
	"\bcanceled\x18\x05 \x01(\v2\x1c.glyph.operation.v1.CanceledH\x00R\bcanceled\x124\n" +
	"\x06failed\x18\x06 \x01(\v2\x1a.glyph.operation.v1.FailedH\x00R\x06failed\x12:\n" +
	"\brejected\x18\a \x01(\v2\x1c.glyph.operation.v1.RejectedH\x00R\brejectedB\a\n" +
	"\x05event\"_\n" +
	"\x11ExtensionProgress\x12>\n" +
	"\x04tool\x18\x01 \x01(\v2(.glyph.plugins.extension.v1.ToolProgressH\x00R\x04toolB\n" +
	"\n" +
	"\bprogress\"\xb0\x02\n" +
	"\x12ExtensionCompleted\x12J\n" +
	"\bregister\x18\x01 \x01(\v2,.glyph.plugins.extension.v1.RegisterResponseH\x00R\bregister\x12D\n" +
	"\x06handle\x18\x02 \x01(\v2*.glyph.plugins.extension.v1.HandleResponseH\x00R\x06handle\x12<\n" +
	"\x04tool\x18\x03 \x01(\v2&.glyph.plugins.extension.v1.ToolResultH\x00R\x04tool\x12=\n" +
	"\x06cancel\x18\x04 \x01(\v2#.glyph.operation.v1.CancelCompletedH\x00R\x06cancelB\v\n" +
	"\tcompleted\"\x11\n" +
	"\x0fRegisterRequest\"\x9f\x01\n" +
	"\x10RegisterResponse\x12@\n" +
	"\x05tools\x18\x01 \x03(\v2*.glyph.plugins.extension.v1.ToolDescriptorR\x05tools\x12I\n" +
	"\bhandlers\x18\x02 \x03(\v2-.glyph.plugins.extension.v1.HandlerDescriptorR\bhandlers2q\n" +
	"\x10ExtensionService\x12]\n" +
	"\x04Open\x12'.glyph.plugins.extension.v1.OpenRequest\x1a(.glyph.plugins.extension.v1.OpenResponse(\x010\x01B=Z;github.com/n-r-w/glyph/pkg/plugins/extension/v1;extensionv1b\beditionsp\xe8\a"

var file_api_plugins_extension_v1_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_plugins_extension_v1_extension_proto_goTypes = []any{
	(*OpenRequest)(nil),        // 0: glyph.plugins.extension.v1.OpenRequest
	(*OpenResponse)(nil),       // 1: glyph.plugins.extension.v1.OpenResponse
	(*HostRequest)(nil),        // 2: glyph.plugins.extension.v1.HostRequest
	(*ExtensionEvent)(nil),     // 3: glyph.plugins.extension.v1.ExtensionEvent
	(*ExtensionProgress)(nil),  // 4: glyph.plugins.extension.v1.ExtensionProgress
	(*ExtensionCompleted)(nil), // 5: glyph.plugins.extension.v1.ExtensionCompleted
	(*RegisterRequest)(nil),    // 6: glyph.plugins.extension.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 7: glyph.plugins.extension.v1.RegisterResponse
	(*v1.CloseConnection)(nil), // 8: glyph.operation.v1.CloseConnection
	(*HandleRequest)(nil),      // 9: glyph.plugins.extension.v1.HandleRequest
	(*ExecuteRequest)(nil),     // 10: glyph.plugins.extension.v1.ExecuteRequest
	(*v1.CancelOperation)(nil), // 11: glyph.operation.v1.CancelOperation
	(*v1.Accepted)(nil),        // 12: glyph.operation.v1.Accepted
	(*v1.Running)(nil),         // 13: glyph.operation.v1.Running
	(*v1.Canceled)(nil),        // 14: glyph.operation.v1.Canceled
	(*v1.Failed)(nil),          // 15: glyph.operation.v1.Failed
	(*v1.Rejected)(nil),        // 16: glyph.operation.v1.Rejected
	(*ToolProgress)(nil),       // 17: glyph.plugins.extension.v1.ToolProgress
	(*HandleResponse)(nil),     // 18: glyph.plugins.extension.v1.HandleResponse
	(*ToolResult)(nil),         // 19: glyph.plugins.extension.v1.ToolResult
	(*v1.CancelCompleted)(nil), // 20: glyph.operation.v1.CancelCompleted
	(*ToolDescriptor)(nil),     // 21: glyph.plugins.extension.v1.ToolDescriptor
	(*HandlerDescriptor)(nil),  // 22: glyph.plugins.extension.v1.HandlerDescriptor
}
var file_api_plugins_extension_v1_extension_proto_depIdxs = []int32{
	2,  // 0: glyph.plugins.extension.v1.OpenRequest.request:type_name -> glyph.plugins.extension.v1.HostRequest
	8,  // 1: glyph.plugins.extension.v1.OpenRequest.close:type_name -> glyph.operation.v1.CloseConnection
	3,  // 2: glyph.plugins.extension.v1.OpenResponse.event:type_name -> glyph.plugins.extension.v1.ExtensionEvent
	6,  // 3: glyph.plugins.extension.v1.HostRequest.register:type_name -> glyph.plugins.extension.v1.RegisterRequest
	9,  // 4: glyph.plugins.extension.v1.HostRequest.handle:type_name -> glyph.plugins.extension.v1.HandleRequest
	10, // 5: glyph.plugins.extension.v1.HostRequest.execute:type_name -> glyph.plugins.extension.v1.ExecuteRequest
	11, // 6: glyph.plugins.extension.v1.HostRequest.cancel:type_name -> glyph.operation.v1.CancelOperation
	12, // 7: glyph.plugins.extension.v1.ExtensionEvent.accepted:type_name -> glyph.operation.v1.Accepted
	13, // 8: glyph.plugins.extension.v1.ExtensionEvent.running:type_name -> glyph.operation.v1.Running
	4,  // 9: glyph.plugins.extension.v1.ExtensionEvent.progress:type_name -> glyph.plugins.extension.v1.ExtensionProgress
	5,  // 10: glyph.plugins.extension.v1.ExtensionEvent.completed:type_name -> glyph.plugins.extension.v1.ExtensionCompleted
	14, // 11: glyph.plugins.extension.v1.ExtensionEvent.canceled:type_name -> glyph.operation.v1.Canceled
	15, // 12: glyph.plugins.extension.v1.ExtensionEvent.failed:type_name -> glyph.operation.v1.Failed
	16, // 13: glyph.plugins.extension.v1.ExtensionEvent.rejected:type_name -> glyph.operation.v1.Rejected
	17, // 14: glyph.plugins.extension.v1.ExtensionProgress.tool:type_name -> glyph.plugins.extension.v1.ToolProgress
	7,  // 15: glyph.plugins.extension.v1.ExtensionCompleted.register:type_name -> glyph.plugins.extension.v1.RegisterResponse
	18, // 16: glyph.plugins.extension.v1.ExtensionCompleted.handle:type_name -> glyph.plugins.extension.v1.HandleResponse
	19, // 17: glyph.plugins.extension.v1.ExtensionCompleted.tool:type_name -> glyph.plugins.extension.v1.ToolResult
	20, // 18: glyph.plugins.extension.v1.ExtensionCompleted.cancel:type_name -> glyph.operation.v1.CancelCompleted
	21, // 19: glyph.plugins.extension.v1.RegisterResponse.tools:type_name -> glyph.plugins.extension.v1.ToolDescriptor
	22, // 20: glyph.plugins.extension.v1.RegisterResponse.handlers:type_name -> glyph.plugins.extension.v1.HandlerDescriptor
	0,  // 21: glyph.plugins.extension.v1.ExtensionService.Open:input_type -> glyph.plugins.extension.v1.OpenRequest
	1,  // 22: glyph.plugins.extension.v1.ExtensionService.Open:output_type -> glyph.plugins.extension.v1.OpenResponse
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_plugins_extension_v1_extension_proto_init() }
func file_api_plugins_extension_v1_extension_proto_init() {
	if File_api_plugins_extension_v1_extension_proto != nil {
		return
	}
	file_api_plugins_extension_v1_session_tree_proto_init()
	file_api_plugins_extension_v1_tool_proto_init()
	file_api_plugins_extension_v1_extension_proto_msgTypes[0].OneofWrappers = []any{
		(*openRequest_Request)(nil),
		(*openRequest_Close)(nil),
	}
	file_api_plugins_extension_v1_extension_proto_msgTypes[1].OneofWrappers = []any{
		(*openResponse_Event)(nil),
	}
	file_api_plugins_extension_v1_extension_proto_msgTypes[2].OneofWrappers = []any{
		(*hostRequest_Register)(nil),
		(*hostRequest_Handle)(nil),
		(*hostRequest_Execute)(nil),
		(*hostRequest_Cancel)(nil),
	}
	file_api_plugins_extension_v1_extension_proto_msgTypes[3].OneofWrappers = []any{
		(*extensionEvent_Accepted)(nil),
		(*extensionEvent_Running)(nil),
		(*extensionEvent_Progress)(nil),
		(*extensionEvent_Completed)(nil),
		(*extensionEvent_Canceled)(nil),
		(*extensionEvent_Failed)(nil),
		(*extensionEvent_Rejected)(nil),
	}
	file_api_plugins_extension_v1_extension_proto_msgTypes[4].OneofWrappers = []any{
		(*extensionProgress_Tool)(nil),
	}
	file_api_plugins_extension_v1_extension_proto_msgTypes[5].OneofWrappers = []any{
		(*extensionCompleted_Register)(nil),
		(*extensionCompleted_Handle)(nil),
		(*extensionCompleted_Tool)(nil),
		(*extensionCompleted_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugins_extension_v1_extension_proto_rawDesc), len(file_api_plugins_extension_v1_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_plugins_extension_v1_extension_proto_goTypes,
		DependencyIndexes: file_api_plugins_extension_v1_extension_proto_depIdxs,
		MessageInfos:      file_api_plugins_extension_v1_extension_proto_msgTypes,
	}.Build()
	File_api_plugins_extension_v1_extension_proto = out.File
	file_api_plugins_extension_v1_extension_proto_goTypes = nil
	file_api_plugins_extension_v1_extension_proto_depIdxs = nil
}
