// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: api/plugins/extension/v1/lifecycle.proto

package extensionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageUpdateKind identifies one model content transition.
type MessageUpdateKind int32

const (
	// No transition was supplied.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_UNSPECIFIED MessageUpdateKind = 0
	// One content block started.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_CONTENT_START MessageUpdateKind = 1
	// Text was appended to one content block.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_TEXT_DELTA MessageUpdateKind = 2
	// One content block ended.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_CONTENT_END MessageUpdateKind = 3
	// One tool call started.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_TOOL_CALL_START MessageUpdateKind = 4
	// One tool call changed.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_TOOL_CALL_UPDATE MessageUpdateKind = 5
	// One tool call ended.
	MessageUpdateKind_MESSAGE_UPDATE_KIND_TOOL_CALL_END MessageUpdateKind = 6
)

// Enum value maps for MessageUpdateKind.
var (
	MessageUpdateKind_name = map[int32]string{
		0: "MESSAGE_UPDATE_KIND_UNSPECIFIED",
		1: "MESSAGE_UPDATE_KIND_CONTENT_START",
		2: "MESSAGE_UPDATE_KIND_TEXT_DELTA",
		3: "MESSAGE_UPDATE_KIND_CONTENT_END",
		4: "MESSAGE_UPDATE_KIND_TOOL_CALL_START",
		5: "MESSAGE_UPDATE_KIND_TOOL_CALL_UPDATE",
		6: "MESSAGE_UPDATE_KIND_TOOL_CALL_END",
	}
	MessageUpdateKind_value = map[string]int32{
		"MESSAGE_UPDATE_KIND_UNSPECIFIED":      0,
		"MESSAGE_UPDATE_KIND_CONTENT_START":    1,
		"MESSAGE_UPDATE_KIND_TEXT_DELTA":       2,
		"MESSAGE_UPDATE_KIND_CONTENT_END":      3,
		"MESSAGE_UPDATE_KIND_TOOL_CALL_START":  4,
		"MESSAGE_UPDATE_KIND_TOOL_CALL_UPDATE": 5,
		"MESSAGE_UPDATE_KIND_TOOL_CALL_END":    6,
	}
)

func (x MessageUpdateKind) Enum() *MessageUpdateKind {
	p := new(MessageUpdateKind)
	*p = x
	return p
}

func (x MessageUpdateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageUpdateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugins_extension_v1_lifecycle_proto_enumTypes[0].Descriptor()
}

func (MessageUpdateKind) Type() protoreflect.EnumType {
	return &file_api_plugins_extension_v1_lifecycle_proto_enumTypes[0]
}

func (x MessageUpdateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// LifecycleInvocation carries one provider-neutral Agent Core lifecycle event.
type LifecycleInvocation struct {
	state            protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Event isLifecycleInvocation_Event `protobuf_oneof:"event"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LifecycleInvocation) Reset() {
	*x = LifecycleInvocation{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleInvocation) ProtoMessage() {}

func (x *LifecycleInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LifecycleInvocation) GetAgentStart() *AgentStart {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentStart); ok {
			return x.AgentStart
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetAgentEnd() *AgentEnd {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentEnd); ok {
			return x.AgentEnd
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetAgentSettled() *AgentSettled {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentSettled); ok {
			return x.AgentSettled
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetTurnStart() *TurnStart {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_TurnStart); ok {
			return x.TurnStart
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetTurnEnd() *TurnEnd {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_TurnEnd); ok {
			return x.TurnEnd
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetMessageStart() *MessageStart {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageStart); ok {
			return x.MessageStart
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetMessageUpdate() *MessageUpdate {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageUpdate); ok {
			return x.MessageUpdate
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetMessageEnd() *MessageEnd {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageEnd); ok {
			return x.MessageEnd
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetToolExecutionStart() *ToolExecutionStart {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionStart); ok {
			return x.ToolExecutionStart
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetToolExecutionUpdate() *ToolExecutionUpdate {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionUpdate); ok {
			return x.ToolExecutionUpdate
		}
	}
	return nil
}

func (x *LifecycleInvocation) GetToolExecutionEnd() *ToolExecutionEnd {
	if x != nil {
		if x, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionEnd); ok {
			return x.ToolExecutionEnd
		}
	}
	return nil
}

func (x *LifecycleInvocation) SetAgentStart(v *AgentStart) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_AgentStart{v}
}

func (x *LifecycleInvocation) SetAgentEnd(v *AgentEnd) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_AgentEnd{v}
}

func (x *LifecycleInvocation) SetAgentSettled(v *AgentSettled) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_AgentSettled{v}
}

func (x *LifecycleInvocation) SetTurnStart(v *TurnStart) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_TurnStart{v}
}

func (x *LifecycleInvocation) SetTurnEnd(v *TurnEnd) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_TurnEnd{v}
}

func (x *LifecycleInvocation) SetMessageStart(v *MessageStart) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_MessageStart{v}
}

func (x *LifecycleInvocation) SetMessageUpdate(v *MessageUpdate) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_MessageUpdate{v}
}

func (x *LifecycleInvocation) SetMessageEnd(v *MessageEnd) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_MessageEnd{v}
}

func (x *LifecycleInvocation) SetToolExecutionStart(v *ToolExecutionStart) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_ToolExecutionStart{v}
}

func (x *LifecycleInvocation) SetToolExecutionUpdate(v *ToolExecutionUpdate) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_ToolExecutionUpdate{v}
}

func (x *LifecycleInvocation) SetToolExecutionEnd(v *ToolExecutionEnd) {
	if v == nil {
		x.xxx_hidden_Event = nil
		return
	}
	x.xxx_hidden_Event = &lifecycleInvocation_ToolExecutionEnd{v}
}

func (x *LifecycleInvocation) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *LifecycleInvocation) HasAgentStart() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentStart)
	return ok
}

func (x *LifecycleInvocation) HasAgentEnd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentEnd)
	return ok
}

func (x *LifecycleInvocation) HasAgentSettled() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentSettled)
	return ok
}

func (x *LifecycleInvocation) HasTurnStart() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_TurnStart)
	return ok
}

func (x *LifecycleInvocation) HasTurnEnd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_TurnEnd)
	return ok
}

func (x *LifecycleInvocation) HasMessageStart() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageStart)
	return ok
}

func (x *LifecycleInvocation) HasMessageUpdate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageUpdate)
	return ok
}

func (x *LifecycleInvocation) HasMessageEnd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageEnd)
	return ok
}

func (x *LifecycleInvocation) HasToolExecutionStart() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionStart)
	return ok
}

func (x *LifecycleInvocation) HasToolExecutionUpdate() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionUpdate)
	return ok
}

func (x *LifecycleInvocation) HasToolExecutionEnd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionEnd)
	return ok
}

func (x *LifecycleInvocation) ClearEvent() {
	x.xxx_hidden_Event = nil
}

func (x *LifecycleInvocation) ClearAgentStart() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentStart); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearAgentEnd() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentEnd); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearAgentSettled() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_AgentSettled); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearTurnStart() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_TurnStart); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearTurnEnd() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_TurnEnd); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearMessageStart() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageStart); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearMessageUpdate() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageUpdate); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearMessageEnd() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_MessageEnd); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearToolExecutionStart() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionStart); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearToolExecutionUpdate() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionUpdate); ok {
		x.xxx_hidden_Event = nil
	}
}

func (x *LifecycleInvocation) ClearToolExecutionEnd() {
	if _, ok := x.xxx_hidden_Event.(*lifecycleInvocation_ToolExecutionEnd); ok {
		x.xxx_hidden_Event = nil
	}
}

const LifecycleInvocation_Event_not_set_case case_LifecycleInvocation_Event = 0
const LifecycleInvocation_AgentStart_case case_LifecycleInvocation_Event = 1
const LifecycleInvocation_AgentEnd_case case_LifecycleInvocation_Event = 2
const LifecycleInvocation_AgentSettled_case case_LifecycleInvocation_Event = 3
const LifecycleInvocation_TurnStart_case case_LifecycleInvocation_Event = 4
const LifecycleInvocation_TurnEnd_case case_LifecycleInvocation_Event = 5
const LifecycleInvocation_MessageStart_case case_LifecycleInvocation_Event = 6
const LifecycleInvocation_MessageUpdate_case case_LifecycleInvocation_Event = 7
const LifecycleInvocation_MessageEnd_case case_LifecycleInvocation_Event = 8
const LifecycleInvocation_ToolExecutionStart_case case_LifecycleInvocation_Event = 9
const LifecycleInvocation_ToolExecutionUpdate_case case_LifecycleInvocation_Event = 10
const LifecycleInvocation_ToolExecutionEnd_case case_LifecycleInvocation_Event = 11

func (x *LifecycleInvocation) WhichEvent() case_LifecycleInvocation_Event {
	if x == nil {
		return LifecycleInvocation_Event_not_set_case
	}
	switch x.xxx_hidden_Event.(type) {
	case *lifecycleInvocation_AgentStart:
		return LifecycleInvocation_AgentStart_case
	case *lifecycleInvocation_AgentEnd:
		return LifecycleInvocation_AgentEnd_case
	case *lifecycleInvocation_AgentSettled:
		return LifecycleInvocation_AgentSettled_case
	case *lifecycleInvocation_TurnStart:
		return LifecycleInvocation_TurnStart_case
	case *lifecycleInvocation_TurnEnd:
		return LifecycleInvocation_TurnEnd_case
	case *lifecycleInvocation_MessageStart:
		return LifecycleInvocation_MessageStart_case
	case *lifecycleInvocation_MessageUpdate:
		return LifecycleInvocation_MessageUpdate_case
	case *lifecycleInvocation_MessageEnd:
		return LifecycleInvocation_MessageEnd_case
	case *lifecycleInvocation_ToolExecutionStart:
		return LifecycleInvocation_ToolExecutionStart_case
	case *lifecycleInvocation_ToolExecutionUpdate:
		return LifecycleInvocation_ToolExecutionUpdate_case
	case *lifecycleInvocation_ToolExecutionEnd:
		return LifecycleInvocation_ToolExecutionEnd_case
	default:
		return LifecycleInvocation_Event_not_set_case
	}
}

type LifecycleInvocation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The lifecycle payload.

	// Fields of oneof xxx_hidden_Event:
	AgentStart          *AgentStart
	AgentEnd            *AgentEnd
	AgentSettled        *AgentSettled
	TurnStart           *TurnStart
	TurnEnd             *TurnEnd
	MessageStart        *MessageStart
	MessageUpdate       *MessageUpdate
	MessageEnd          *MessageEnd
	ToolExecutionStart  *ToolExecutionStart
	ToolExecutionUpdate *ToolExecutionUpdate
	ToolExecutionEnd    *ToolExecutionEnd
	// -- end of xxx_hidden_Event
}

func (b0 LifecycleInvocation_builder) Build() *LifecycleInvocation {
	m0 := &LifecycleInvocation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AgentStart != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_AgentStart{b.AgentStart}
	}
	if b.AgentEnd != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_AgentEnd{b.AgentEnd}
	}
	if b.AgentSettled != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_AgentSettled{b.AgentSettled}
	}
	if b.TurnStart != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_TurnStart{b.TurnStart}
	}
	if b.TurnEnd != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_TurnEnd{b.TurnEnd}
	}
	if b.MessageStart != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_MessageStart{b.MessageStart}
	}
	if b.MessageUpdate != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_MessageUpdate{b.MessageUpdate}
	}
	if b.MessageEnd != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_MessageEnd{b.MessageEnd}
	}
	if b.ToolExecutionStart != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_ToolExecutionStart{b.ToolExecutionStart}
	}
	if b.ToolExecutionUpdate != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_ToolExecutionUpdate{b.ToolExecutionUpdate}
	}
	if b.ToolExecutionEnd != nil {
		x.xxx_hidden_Event = &lifecycleInvocation_ToolExecutionEnd{b.ToolExecutionEnd}
	}
	return m0
}

type case_LifecycleInvocation_Event protoreflect.FieldNumber

func (x case_LifecycleInvocation_Event) String() string {
	md := file_api_plugins_extension_v1_lifecycle_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isLifecycleInvocation_Event interface {
	isLifecycleInvocation_Event()
}

type lifecycleInvocation_AgentStart struct {
	AgentStart *AgentStart `protobuf:"bytes,1,opt,name=agent_start,json=agentStart,oneof"`
}

type lifecycleInvocation_AgentEnd struct {
	AgentEnd *AgentEnd `protobuf:"bytes,2,opt,name=agent_end,json=agentEnd,oneof"`
}

type lifecycleInvocation_AgentSettled struct {
	AgentSettled *AgentSettled `protobuf:"bytes,3,opt,name=agent_settled,json=agentSettled,oneof"`
}

type lifecycleInvocation_TurnStart struct {
	TurnStart *TurnStart `protobuf:"bytes,4,opt,name=turn_start,json=turnStart,oneof"`
}

type lifecycleInvocation_TurnEnd struct {
	TurnEnd *TurnEnd `protobuf:"bytes,5,opt,name=turn_end,json=turnEnd,oneof"`
}

type lifecycleInvocation_MessageStart struct {
	MessageStart *MessageStart `protobuf:"bytes,6,opt,name=message_start,json=messageStart,oneof"`
}

type lifecycleInvocation_MessageUpdate struct {
	MessageUpdate *MessageUpdate `protobuf:"bytes,7,opt,name=message_update,json=messageUpdate,oneof"`
}

type lifecycleInvocation_MessageEnd struct {
	MessageEnd *MessageEnd `protobuf:"bytes,8,opt,name=message_end,json=messageEnd,oneof"`
}

type lifecycleInvocation_ToolExecutionStart struct {
	ToolExecutionStart *ToolExecutionStart `protobuf:"bytes,9,opt,name=tool_execution_start,json=toolExecutionStart,oneof"`
}

type lifecycleInvocation_ToolExecutionUpdate struct {
	ToolExecutionUpdate *ToolExecutionUpdate `protobuf:"bytes,10,opt,name=tool_execution_update,json=toolExecutionUpdate,oneof"`
}

type lifecycleInvocation_ToolExecutionEnd struct {
	ToolExecutionEnd *ToolExecutionEnd `protobuf:"bytes,11,opt,name=tool_execution_end,json=toolExecutionEnd,oneof"`
}

func (*lifecycleInvocation_AgentStart) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_AgentEnd) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_AgentSettled) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_TurnStart) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_TurnEnd) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_MessageStart) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_MessageUpdate) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_MessageEnd) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_ToolExecutionStart) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_ToolExecutionUpdate) isLifecycleInvocation_Event() {}

func (*lifecycleInvocation_ToolExecutionEnd) isLifecycleInvocation_Event() {}

// LifecycleAction acknowledges one observed lifecycle event.
type LifecycleAction struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleAction) Reset() {
	*x = LifecycleAction{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleAction) ProtoMessage() {}

func (x *LifecycleAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LifecycleAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LifecycleAction_builder) Build() *LifecycleAction {
	m0 := &LifecycleAction{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// AgentStart reports that one agent run started.
type AgentStart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentStart) Reset() {
	*x = AgentStart{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStart) ProtoMessage() {}

func (x *AgentStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentStart) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *AgentStart) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AgentStart) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentStart) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

type AgentStart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
}

func (b0 AgentStart_builder) Build() *AgentStart {
	m0 := &AgentStart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RunId = b.RunId
	}
	return m0
}

// AgentEnd reports one terminal agent outcome.
type AgentEnd struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId        *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_Outcome      *string                `protobuf:"bytes,2,opt,name=outcome"`
	xxx_hidden_ErrorMessage *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AgentEnd) Reset() {
	*x = AgentEnd{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnd) ProtoMessage() {}

func (x *AgentEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentEnd) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *AgentEnd) GetOutcome() string {
	if x != nil {
		if x.xxx_hidden_Outcome != nil {
			return *x.xxx_hidden_Outcome
		}
		return ""
	}
	return ""
}

func (x *AgentEnd) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *AgentEnd) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AgentEnd) SetOutcome(v string) {
	x.xxx_hidden_Outcome = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AgentEnd) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AgentEnd) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentEnd) HasOutcome() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentEnd) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AgentEnd) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *AgentEnd) ClearOutcome() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Outcome = nil
}

func (x *AgentEnd) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

type AgentEnd_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The provider-neutral outcome.
	Outcome *string
	// The safe terminal error message.
	ErrorMessage *string
}

func (b0 AgentEnd_builder) Build() *AgentEnd {
	m0 := &AgentEnd{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.Outcome != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Outcome = b.Outcome
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	return m0
}

// AgentSettled reports that Host settlement completed for one run.
type AgentSettled struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentSettled) Reset() {
	*x = AgentSettled{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSettled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSettled) ProtoMessage() {}

func (x *AgentSettled) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentSettled) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *AgentSettled) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AgentSettled) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentSettled) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

type AgentSettled_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
}

func (b0 AgentSettled_builder) Build() *AgentSettled {
	m0 := &AgentSettled{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RunId = b.RunId
	}
	return m0
}

// TurnStart reports that one agent turn started.
type TurnStart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TurnStart) Reset() {
	*x = TurnStart{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnStart) ProtoMessage() {}

func (x *TurnStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TurnStart) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *TurnStart) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TurnStart) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TurnStart) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

type TurnStart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
}

func (b0 TurnStart_builder) Build() *TurnStart {
	m0 := &TurnStart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RunId = b.RunId
	}
	return m0
}

// TurnEnd reports the terminal model response for one turn.
type TurnEnd struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_Response    *ConfiguredModelResult `protobuf:"bytes,2,opt,name=response"`
	xxx_hidden_ToolResults *[]*ToolExecutionEnd   `protobuf:"bytes,3,rep,name=tool_results,json=toolResults"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TurnEnd) Reset() {
	*x = TurnEnd{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnEnd) ProtoMessage() {}

func (x *TurnEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TurnEnd) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *TurnEnd) GetResponse() *ConfiguredModelResult {
	if x != nil {
		return x.xxx_hidden_Response
	}
	return nil
}

func (x *TurnEnd) GetToolResults() []*ToolExecutionEnd {
	if x != nil {
		if x.xxx_hidden_ToolResults != nil {
			return *x.xxx_hidden_ToolResults
		}
	}
	return nil
}

func (x *TurnEnd) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TurnEnd) SetResponse(v *ConfiguredModelResult) {
	x.xxx_hidden_Response = v
}

func (x *TurnEnd) SetToolResults(v []*ToolExecutionEnd) {
	x.xxx_hidden_ToolResults = &v
}

func (x *TurnEnd) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TurnEnd) HasResponse() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Response != nil
}

func (x *TurnEnd) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *TurnEnd) ClearResponse() {
	x.xxx_hidden_Response = nil
}

type TurnEnd_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The provider-neutral terminal response.
	Response *ConfiguredModelResult
	// The ordered terminal tool results from this turn.
	ToolResults []*ToolExecutionEnd
}

func (b0 TurnEnd_builder) Build() *TurnEnd {
	m0 := &TurnEnd{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RunId = b.RunId
	}
	x.xxx_hidden_Response = b.Response
	x.xxx_hidden_ToolResults = &b.ToolResults
	return m0
}

// MessageStart reports that one model response started.
type MessageStart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MessageStart) Reset() {
	*x = MessageStart{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStart) ProtoMessage() {}

func (x *MessageStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageStart) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *MessageStart) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *MessageStart) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MessageStart) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

type MessageStart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
}

func (b0 MessageStart_builder) Build() *MessageStart {
	m0 := &MessageStart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RunId = b.RunId
	}
	return m0
}

// MessageUpdate carries one model content transition in source order.
type MessageUpdate struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                 `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_Kind        MessageUpdateKind       `protobuf:"varint,2,opt,name=kind,enum=glyph.plugins.extension.v1.MessageUpdateKind"`
	xxx_hidden_Position    int64                   `protobuf:"varint,3,opt,name=position"`
	xxx_hidden_Content     *ConfiguredModelContent `protobuf:"bytes,4,opt,name=content"`
	xxx_hidden_ToolCall    *LifecycleToolCall      `protobuf:"bytes,5,opt,name=tool_call,json=toolCall"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MessageUpdate) Reset() {
	*x = MessageUpdate{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdate) ProtoMessage() {}

func (x *MessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageUpdate) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *MessageUpdate) GetKind() MessageUpdateKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Kind
		}
	}
	return MessageUpdateKind_MESSAGE_UPDATE_KIND_UNSPECIFIED
}

func (x *MessageUpdate) GetPosition() int64 {
	if x != nil {
		return x.xxx_hidden_Position
	}
	return 0
}

func (x *MessageUpdate) GetContent() *ConfiguredModelContent {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *MessageUpdate) GetToolCall() *LifecycleToolCall {
	if x != nil {
		return x.xxx_hidden_ToolCall
	}
	return nil
}

func (x *MessageUpdate) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *MessageUpdate) SetKind(v MessageUpdateKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *MessageUpdate) SetPosition(v int64) {
	x.xxx_hidden_Position = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *MessageUpdate) SetContent(v *ConfiguredModelContent) {
	x.xxx_hidden_Content = v
}

func (x *MessageUpdate) SetToolCall(v *LifecycleToolCall) {
	x.xxx_hidden_ToolCall = v
}

func (x *MessageUpdate) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MessageUpdate) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MessageUpdate) HasPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MessageUpdate) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *MessageUpdate) HasToolCall() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ToolCall != nil
}

func (x *MessageUpdate) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *MessageUpdate) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Kind = MessageUpdateKind_MESSAGE_UPDATE_KIND_UNSPECIFIED
}

func (x *MessageUpdate) ClearPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Position = 0
}

func (x *MessageUpdate) ClearContent() {
	x.xxx_hidden_Content = nil
}

func (x *MessageUpdate) ClearToolCall() {
	x.xxx_hidden_ToolCall = nil
}

type MessageUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The transition kind.
	Kind *MessageUpdateKind
	// The zero-based content position.
	Position *int64
	// The provider-neutral content when present.
	Content *ConfiguredModelContent
	// The current or finalized tool call when present.
	ToolCall *LifecycleToolCall
}

func (b0 MessageUpdate_builder) Build() *MessageUpdate {
	m0 := &MessageUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Position != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Position = *b.Position
	}
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_ToolCall = b.ToolCall
	return m0
}

// LifecycleToolCall carries current provider-neutral function-call state.
type LifecycleToolCall struct {
	state                    protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                    `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name          *string                    `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Position      int64                      `protobuf:"varint,3,opt,name=position"`
	xxx_hidden_Provisional   bool                       `protobuf:"varint,4,opt,name=provisional"`
	xxx_hidden_Fields        *[]*LifecycleToolCallField `protobuf:"bytes,5,rep,name=fields"`
	xxx_hidden_ArgumentsJson []byte                     `protobuf:"bytes,6,opt,name=arguments_json,json=argumentsJson"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LifecycleToolCall) Reset() {
	*x = LifecycleToolCall{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleToolCall) ProtoMessage() {}

func (x *LifecycleToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LifecycleToolCall) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *LifecycleToolCall) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *LifecycleToolCall) GetPosition() int64 {
	if x != nil {
		return x.xxx_hidden_Position
	}
	return 0
}

func (x *LifecycleToolCall) GetProvisional() bool {
	if x != nil {
		return x.xxx_hidden_Provisional
	}
	return false
}

func (x *LifecycleToolCall) GetFields() []*LifecycleToolCallField {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *LifecycleToolCall) GetArgumentsJson() []byte {
	if x != nil {
		return x.xxx_hidden_ArgumentsJson
	}
	return nil
}

func (x *LifecycleToolCall) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *LifecycleToolCall) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *LifecycleToolCall) SetPosition(v int64) {
	x.xxx_hidden_Position = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *LifecycleToolCall) SetProvisional(v bool) {
	x.xxx_hidden_Provisional = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *LifecycleToolCall) SetFields(v []*LifecycleToolCallField) {
	x.xxx_hidden_Fields = &v
}

func (x *LifecycleToolCall) SetArgumentsJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ArgumentsJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *LifecycleToolCall) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LifecycleToolCall) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LifecycleToolCall) HasPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LifecycleToolCall) HasProvisional() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LifecycleToolCall) HasArgumentsJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *LifecycleToolCall) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *LifecycleToolCall) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *LifecycleToolCall) ClearPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Position = 0
}

func (x *LifecycleToolCall) ClearProvisional() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Provisional = false
}

func (x *LifecycleToolCall) ClearArgumentsJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ArgumentsJson = nil
}

type LifecycleToolCall_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The provider-assigned call identifier.
	Id *string
	// The current tool name.
	Name *string
	// The zero-based response position.
	Position *int64
	// Whether this state can still change.
	Provisional *bool
	// The ordered currently decoded fields.
	Fields []*LifecycleToolCallField
	// The finalized JSON arguments when available.
	ArgumentsJson []byte
}

func (b0 LifecycleToolCall_builder) Build() *LifecycleToolCall {
	m0 := &LifecycleToolCall{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Position != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Position = *b.Position
	}
	if b.Provisional != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Provisional = *b.Provisional
	}
	x.xxx_hidden_Fields = &b.Fields
	if b.ArgumentsJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_ArgumentsJson = b.ArgumentsJson
	}
	return m0
}

// LifecycleToolCallField carries one complete value or exact scalar prefix.
type LifecycleToolCallField struct {
	state                  protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                          `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Content     isLifecycleToolCallField_Content `protobuf_oneof:"content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LifecycleToolCallField) Reset() {
	*x = LifecycleToolCallField{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleToolCallField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleToolCallField) ProtoMessage() {}

func (x *LifecycleToolCallField) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LifecycleToolCallField) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *LifecycleToolCallField) GetValueJson() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*lifecycleToolCallField_ValueJson); ok {
			return x.ValueJson
		}
	}
	return nil
}

func (x *LifecycleToolCallField) GetPrefix() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*lifecycleToolCallField_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *LifecycleToolCallField) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LifecycleToolCallField) SetValueJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = &lifecycleToolCallField_ValueJson{v}
}

func (x *LifecycleToolCallField) SetPrefix(v string) {
	x.xxx_hidden_Content = &lifecycleToolCallField_Prefix{v}
}

func (x *LifecycleToolCallField) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LifecycleToolCallField) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *LifecycleToolCallField) HasValueJson() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*lifecycleToolCallField_ValueJson)
	return ok
}

func (x *LifecycleToolCallField) HasPrefix() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*lifecycleToolCallField_Prefix)
	return ok
}

func (x *LifecycleToolCallField) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *LifecycleToolCallField) ClearContent() {
	x.xxx_hidden_Content = nil
}

func (x *LifecycleToolCallField) ClearValueJson() {
	if _, ok := x.xxx_hidden_Content.(*lifecycleToolCallField_ValueJson); ok {
		x.xxx_hidden_Content = nil
	}
}

func (x *LifecycleToolCallField) ClearPrefix() {
	if _, ok := x.xxx_hidden_Content.(*lifecycleToolCallField_Prefix); ok {
		x.xxx_hidden_Content = nil
	}
}

const LifecycleToolCallField_Content_not_set_case case_LifecycleToolCallField_Content = 0
const LifecycleToolCallField_ValueJson_case case_LifecycleToolCallField_Content = 2
const LifecycleToolCallField_Prefix_case case_LifecycleToolCallField_Content = 3

func (x *LifecycleToolCallField) WhichContent() case_LifecycleToolCallField_Content {
	if x == nil {
		return LifecycleToolCallField_Content_not_set_case
	}
	switch x.xxx_hidden_Content.(type) {
	case *lifecycleToolCallField_ValueJson:
		return LifecycleToolCallField_ValueJson_case
	case *lifecycleToolCallField_Prefix:
		return LifecycleToolCallField_Prefix_case
	default:
		return LifecycleToolCallField_Content_not_set_case
	}
}

type LifecycleToolCallField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The argument field name.
	Name *string
	// The current field content.

	// Fields of oneof xxx_hidden_Content:
	ValueJson []byte
	Prefix    *string
	// -- end of xxx_hidden_Content
}

func (b0 LifecycleToolCallField_builder) Build() *LifecycleToolCallField {
	m0 := &LifecycleToolCallField{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.ValueJson != nil {
		x.xxx_hidden_Content = &lifecycleToolCallField_ValueJson{b.ValueJson}
	}
	if b.Prefix != nil {
		x.xxx_hidden_Content = &lifecycleToolCallField_Prefix{*b.Prefix}
	}
	return m0
}

type case_LifecycleToolCallField_Content protoreflect.FieldNumber

func (x case_LifecycleToolCallField_Content) String() string {
	md := file_api_plugins_extension_v1_lifecycle_proto_msgTypes[10].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isLifecycleToolCallField_Content interface {
	isLifecycleToolCallField_Content()
}

type lifecycleToolCallField_ValueJson struct {
	ValueJson []byte `protobuf:"bytes,2,opt,name=value_json,json=valueJson,oneof"`
}

type lifecycleToolCallField_Prefix struct {
	Prefix string `protobuf:"bytes,3,opt,name=prefix,oneof"`
}

func (*lifecycleToolCallField_ValueJson) isLifecycleToolCallField_Content() {}

func (*lifecycleToolCallField_Prefix) isLifecycleToolCallField_Content() {}

// MessageEnd reports one finalized model response.
type MessageEnd struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_Response    *ConfiguredModelResult `protobuf:"bytes,2,opt,name=response"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MessageEnd) Reset() {
	*x = MessageEnd{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnd) ProtoMessage() {}

func (x *MessageEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageEnd) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *MessageEnd) GetResponse() *ConfiguredModelResult {
	if x != nil {
		return x.xxx_hidden_Response
	}
	return nil
}

func (x *MessageEnd) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *MessageEnd) SetResponse(v *ConfiguredModelResult) {
	x.xxx_hidden_Response = v
}

func (x *MessageEnd) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MessageEnd) HasResponse() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Response != nil
}

func (x *MessageEnd) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *MessageEnd) ClearResponse() {
	x.xxx_hidden_Response = nil
}

type MessageEnd_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The provider-neutral terminal response.
	Response *ConfiguredModelResult
}

func (b0 MessageEnd_builder) Build() *MessageEnd {
	m0 := &MessageEnd{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_RunId = b.RunId
	}
	x.xxx_hidden_Response = b.Response
	return m0
}

// ToolExecutionStart reports that one tool execution started.
type ToolExecutionStart struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_CallId      *string                `protobuf:"bytes,2,opt,name=call_id,json=callId"`
	xxx_hidden_ToolName    *string                `protobuf:"bytes,3,opt,name=tool_name,json=toolName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolExecutionStart) Reset() {
	*x = ToolExecutionStart{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionStart) ProtoMessage() {}

func (x *ToolExecutionStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolExecutionStart) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionStart) GetCallId() string {
	if x != nil {
		if x.xxx_hidden_CallId != nil {
			return *x.xxx_hidden_CallId
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionStart) GetToolName() string {
	if x != nil {
		if x.xxx_hidden_ToolName != nil {
			return *x.xxx_hidden_ToolName
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionStart) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ToolExecutionStart) SetCallId(v string) {
	x.xxx_hidden_CallId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ToolExecutionStart) SetToolName(v string) {
	x.xxx_hidden_ToolName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ToolExecutionStart) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolExecutionStart) HasCallId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ToolExecutionStart) HasToolName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ToolExecutionStart) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *ToolExecutionStart) ClearCallId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CallId = nil
}

func (x *ToolExecutionStart) ClearToolName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ToolName = nil
}

type ToolExecutionStart_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The provider-assigned tool call identifier.
	CallId *string
	// The tool name.
	ToolName *string
}

func (b0 ToolExecutionStart_builder) Build() *ToolExecutionStart {
	m0 := &ToolExecutionStart{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.CallId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_CallId = b.CallId
	}
	if b.ToolName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ToolName = b.ToolName
	}
	return m0
}

// ToolExecutionUpdate reports one tool progress fragment.
type ToolExecutionUpdate struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_CallId      *string                `protobuf:"bytes,2,opt,name=call_id,json=callId"`
	xxx_hidden_ToolName    *string                `protobuf:"bytes,3,opt,name=tool_name,json=toolName"`
	xxx_hidden_Channel     ProgressChannel        `protobuf:"varint,4,opt,name=channel,enum=glyph.plugins.extension.v1.ProgressChannel"`
	xxx_hidden_Content     *string                `protobuf:"bytes,5,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolExecutionUpdate) Reset() {
	*x = ToolExecutionUpdate{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionUpdate) ProtoMessage() {}

func (x *ToolExecutionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolExecutionUpdate) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionUpdate) GetCallId() string {
	if x != nil {
		if x.xxx_hidden_CallId != nil {
			return *x.xxx_hidden_CallId
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionUpdate) GetToolName() string {
	if x != nil {
		if x.xxx_hidden_ToolName != nil {
			return *x.xxx_hidden_ToolName
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionUpdate) GetChannel() ProgressChannel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Channel
		}
	}
	return ProgressChannel_PROGRESS_CHANNEL_UNSPECIFIED
}

func (x *ToolExecutionUpdate) GetContent() string {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionUpdate) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ToolExecutionUpdate) SetCallId(v string) {
	x.xxx_hidden_CallId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ToolExecutionUpdate) SetToolName(v string) {
	x.xxx_hidden_ToolName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ToolExecutionUpdate) SetChannel(v ProgressChannel) {
	x.xxx_hidden_Channel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ToolExecutionUpdate) SetContent(v string) {
	x.xxx_hidden_Content = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ToolExecutionUpdate) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolExecutionUpdate) HasCallId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ToolExecutionUpdate) HasToolName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ToolExecutionUpdate) HasChannel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ToolExecutionUpdate) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ToolExecutionUpdate) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *ToolExecutionUpdate) ClearCallId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CallId = nil
}

func (x *ToolExecutionUpdate) ClearToolName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ToolName = nil
}

func (x *ToolExecutionUpdate) ClearChannel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Channel = ProgressChannel_PROGRESS_CHANNEL_UNSPECIFIED
}

func (x *ToolExecutionUpdate) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Content = nil
}

type ToolExecutionUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The provider-assigned tool call identifier.
	CallId *string
	// The tool name.
	ToolName *string
	// The progress channel.
	Channel *ProgressChannel
	// The exact progress content.
	Content *string
}

func (b0 ToolExecutionUpdate_builder) Build() *ToolExecutionUpdate {
	m0 := &ToolExecutionUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.CallId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_CallId = b.CallId
	}
	if b.ToolName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ToolName = b.ToolName
	}
	if b.Channel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Channel = *b.Channel
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

// ToolExecutionEnd reports one terminal tool result.
type ToolExecutionEnd struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       *string                `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_CallId      *string                `protobuf:"bytes,2,opt,name=call_id,json=callId"`
	xxx_hidden_ToolName    *string                `protobuf:"bytes,3,opt,name=tool_name,json=toolName"`
	xxx_hidden_Contents    *[]*ToolResultContent  `protobuf:"bytes,4,rep,name=contents"`
	xxx_hidden_IsError     bool                   `protobuf:"varint,5,opt,name=is_error,json=isError"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolExecutionEnd) Reset() {
	*x = ToolExecutionEnd{}
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolExecutionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolExecutionEnd) ProtoMessage() {}

func (x *ToolExecutionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_extension_v1_lifecycle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolExecutionEnd) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionEnd) GetCallId() string {
	if x != nil {
		if x.xxx_hidden_CallId != nil {
			return *x.xxx_hidden_CallId
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionEnd) GetToolName() string {
	if x != nil {
		if x.xxx_hidden_ToolName != nil {
			return *x.xxx_hidden_ToolName
		}
		return ""
	}
	return ""
}

func (x *ToolExecutionEnd) GetContents() []*ToolResultContent {
	if x != nil {
		if x.xxx_hidden_Contents != nil {
			return *x.xxx_hidden_Contents
		}
	}
	return nil
}

func (x *ToolExecutionEnd) GetIsError() bool {
	if x != nil {
		return x.xxx_hidden_IsError
	}
	return false
}

func (x *ToolExecutionEnd) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ToolExecutionEnd) SetCallId(v string) {
	x.xxx_hidden_CallId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ToolExecutionEnd) SetToolName(v string) {
	x.xxx_hidden_ToolName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ToolExecutionEnd) SetContents(v []*ToolResultContent) {
	x.xxx_hidden_Contents = &v
}

func (x *ToolExecutionEnd) SetIsError(v bool) {
	x.xxx_hidden_IsError = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ToolExecutionEnd) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolExecutionEnd) HasCallId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ToolExecutionEnd) HasToolName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ToolExecutionEnd) HasIsError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ToolExecutionEnd) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RunId = nil
}

func (x *ToolExecutionEnd) ClearCallId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CallId = nil
}

func (x *ToolExecutionEnd) ClearToolName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ToolName = nil
}

func (x *ToolExecutionEnd) ClearIsError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_IsError = false
}

type ToolExecutionEnd_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The Host run identifier.
	RunId *string
	// The provider-assigned tool call identifier.
	CallId *string
	// The tool name.
	ToolName *string
	// The ordered terminal content.
	Contents []*ToolResultContent
	// Whether tool execution failed.
	IsError *bool
}

func (b0 ToolExecutionEnd_builder) Build() *ToolExecutionEnd {
	m0 := &ToolExecutionEnd{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.CallId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_CallId = b.CallId
	}
	if b.ToolName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ToolName = b.ToolName
	}
	x.xxx_hidden_Contents = &b.Contents
	if b.IsError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_IsError = *b.IsError
	}
	return m0
}

var File_api_plugins_extension_v1_lifecycle_proto protoreflect.FileDescriptor

const file_api_plugins_extension_v1_lifecycle_proto_rawDesc = "" +
	"\n" +
	"(api/plugins/extension/v1/lifecycle.proto\x12\x1aglyph.plugins.extension.v1\x1a$api/plugins/extension/v1/model.proto\x1a#api/plugins/extension/v1/tool.proto\"\xa2\a\n" +
	"\x13LifecycleInvocation\x12I\n" +
	"\vagent_start\x18\x01 \x01(\v2&.glyph.plugins.extension.v1.AgentStartH\x00R\n" +
	"agentStart\x12C\n" +
	"\tagent_end\x18\x02 \x01(\v2$.glyph.plugins.extension.v1.AgentEndH\x00R\bagentEnd\x12O\n" +
	"\ragent_settled\x18\x03 \x01(\v2(.glyph.plugins.extension.v1.AgentSettledH\x00R\fagentSettled\x12F\n" +
	"\n" +
	"turn_start\x18\x04 \x01(\v2%.glyph.plugins.extension.v1.TurnStartH\x00R\tturnStart\x12@\n" +
	"\bturn_end\x18\x05 \x01(\v2#.glyph.plugins.extension.v1.TurnEndH\x00R\aturnEnd\x12O\n" +
	"\rmessage_start\x18\x06 \x01(\v2(.glyph.plugins.extension.v1.MessageStartH\x00R\fmessageStart\x12R\n" +
	"\x0emessage_update\x18\a \x01(\v2).glyph.plugins.extension.v1.MessageUpdateH\x00R\rmessageUpdate\x12I\n" +
	"\vmessage_end\x18\b \x01(\v2&.glyph.plugins.extension.v1.MessageEndH\x00R\n" +
	"messageEnd\x12b\n" +
	"\x14tool_execution_start\x18\t \x01(\v2..glyph.plugins.extension.v1.ToolExecutionStartH\x00R\x12toolExecutionStart\x12e\n" +
	"\x15tool_execution_update\x18\n" +
	" \x01(\v2/.glyph.plugins.extension.v1.ToolExecutionUpdateH\x00R\x13toolExecutionUpdate\x12\\\n" +
	"\x12tool_execution_end\x18\v \x01(\v2,.glyph.plugins.extension.v1.ToolExecutionEndH\x00R\x10toolExecutionEndB\a\n" +
	"\x05event\"\x11\n" +
	"\x0fLifecycleAction\"#\n" +
	"\n" +
	"AgentStart\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"`\n" +
	"\bAgentEnd\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"%\n" +
	"\fAgentSettled\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\"\n" +
	"\tTurnStart\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xc0\x01\n" +
	"\aTurnEnd\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12M\n" +
	"\bresponse\x18\x02 \x01(\v21.glyph.plugins.extension.v1.ConfiguredModelResultR\bresponse\x12O\n" +
	"\ftool_results\x18\x03 \x03(\v2,.glyph.plugins.extension.v1.ToolExecutionEndR\vtoolResults\"%\n" +
	"\fMessageStart\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x9f\x02\n" +
	"\rMessageUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12A\n" +
	"\x04kind\x18\x02 \x01(\x0e2-.glyph.plugins.extension.v1.MessageUpdateKindR\x04kind\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x12L\n" +
	"\acontent\x18\x04 \x01(\v22.glyph.plugins.extension.v1.ConfiguredModelContentR\acontent\x12J\n" +
	"\ttool_call\x18\x05 \x01(\v2-.glyph.plugins.extension.v1.LifecycleToolCallR\btoolCall\"\xe8\x01\n" +
	"\x11LifecycleToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x12 \n" +
	"\vprovisional\x18\x04 \x01(\bR\vprovisional\x12J\n" +
	"\x06fields\x18\x05 \x03(\v22.glyph.plugins.extension.v1.LifecycleToolCallFieldR\x06fields\x12%\n" +
	"\x0earguments_json\x18\x06 \x01(\fR\rargumentsJson\"r\n" +
	"\x16LifecycleToolCallField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fH\x00R\tvalueJson\x12\x18\n" +
	"\x06prefix\x18\x03 \x01(\tH\x00R\x06prefixB\t\n" +
	"\acontent\"r\n" +
	"\n" +
	"MessageEnd\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12M\n" +
	"\bresponse\x18\x02 \x01(\v21.glyph.plugins.extension.v1.ConfiguredModelResultR\bresponse\"a\n" +
	"\x12ToolExecutionStart\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\"\xc3\x01\n" +
	"\x13ToolExecutionUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12E\n" +
	"\achannel\x18\x04 \x01(\x0e2+.glyph.plugins.extension.v1.ProgressChannelR\achannel\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"\xc5\x01\n" +
	"\x10ToolExecutionEnd\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12I\n" +
	"\bcontents\x18\x04 \x03(\v2-.glyph.plugins.extension.v1.ToolResultContentR\bcontents\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError*\xa2\x02\n" +
	"\x11MessageUpdateKind\x12#\n" +
	"\x1fMESSAGE_UPDATE_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!MESSAGE_UPDATE_KIND_CONTENT_START\x10\x01\x12\"\n" +
	"\x1eMESSAGE_UPDATE_KIND_TEXT_DELTA\x10\x02\x12#\n" +
	"\x1fMESSAGE_UPDATE_KIND_CONTENT_END\x10\x03\x12'\n" +
	"#MESSAGE_UPDATE_KIND_TOOL_CALL_START\x10\x04\x12(\n" +
	"$MESSAGE_UPDATE_KIND_TOOL_CALL_UPDATE\x10\x05\x12%\n" +
	"!MESSAGE_UPDATE_KIND_TOOL_CALL_END\x10\x06B=Z;github.com/n-r-w/glyph/pkg/plugins/extension/v1;extensionv1b\beditionsp\xe8\a"

var file_api_plugins_extension_v1_lifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_plugins_extension_v1_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_plugins_extension_v1_lifecycle_proto_goTypes = []any{
	(MessageUpdateKind)(0),         // 0: glyph.plugins.extension.v1.MessageUpdateKind
	(*LifecycleInvocation)(nil),    // 1: glyph.plugins.extension.v1.LifecycleInvocation
	(*LifecycleAction)(nil),        // 2: glyph.plugins.extension.v1.LifecycleAction
	(*AgentStart)(nil),             // 3: glyph.plugins.extension.v1.AgentStart
	(*AgentEnd)(nil),               // 4: glyph.plugins.extension.v1.AgentEnd
	(*AgentSettled)(nil),           // 5: glyph.plugins.extension.v1.AgentSettled
	(*TurnStart)(nil),              // 6: glyph.plugins.extension.v1.TurnStart
	(*TurnEnd)(nil),                // 7: glyph.plugins.extension.v1.TurnEnd
	(*MessageStart)(nil),           // 8: glyph.plugins.extension.v1.MessageStart
	(*MessageUpdate)(nil),          // 9: glyph.plugins.extension.v1.MessageUpdate
	(*LifecycleToolCall)(nil),      // 10: glyph.plugins.extension.v1.LifecycleToolCall
	(*LifecycleToolCallField)(nil), // 11: glyph.plugins.extension.v1.LifecycleToolCallField
	(*MessageEnd)(nil),             // 12: glyph.plugins.extension.v1.MessageEnd
	(*ToolExecutionStart)(nil),     // 13: glyph.plugins.extension.v1.ToolExecutionStart
	(*ToolExecutionUpdate)(nil),    // 14: glyph.plugins.extension.v1.ToolExecutionUpdate
	(*ToolExecutionEnd)(nil),       // 15: glyph.plugins.extension.v1.ToolExecutionEnd
	(*ConfiguredModelResult)(nil),  // 16: glyph.plugins.extension.v1.ConfiguredModelResult
	(*ConfiguredModelContent)(nil), // 17: glyph.plugins.extension.v1.ConfiguredModelContent
	(ProgressChannel)(0),           // 18: glyph.plugins.extension.v1.ProgressChannel
	(*ToolResultContent)(nil),      // 19: glyph.plugins.extension.v1.ToolResultContent
}
var file_api_plugins_extension_v1_lifecycle_proto_depIdxs = []int32{
	3,  // 0: glyph.plugins.extension.v1.LifecycleInvocation.agent_start:type_name -> glyph.plugins.extension.v1.AgentStart
	4,  // 1: glyph.plugins.extension.v1.LifecycleInvocation.agent_end:type_name -> glyph.plugins.extension.v1.AgentEnd
	5,  // 2: glyph.plugins.extension.v1.LifecycleInvocation.agent_settled:type_name -> glyph.plugins.extension.v1.AgentSettled
	6,  // 3: glyph.plugins.extension.v1.LifecycleInvocation.turn_start:type_name -> glyph.plugins.extension.v1.TurnStart
	7,  // 4: glyph.plugins.extension.v1.LifecycleInvocation.turn_end:type_name -> glyph.plugins.extension.v1.TurnEnd
	8,  // 5: glyph.plugins.extension.v1.LifecycleInvocation.message_start:type_name -> glyph.plugins.extension.v1.MessageStart
	9,  // 6: glyph.plugins.extension.v1.LifecycleInvocation.message_update:type_name -> glyph.plugins.extension.v1.MessageUpdate
	12, // 7: glyph.plugins.extension.v1.LifecycleInvocation.message_end:type_name -> glyph.plugins.extension.v1.MessageEnd
	13, // 8: glyph.plugins.extension.v1.LifecycleInvocation.tool_execution_start:type_name -> glyph.plugins.extension.v1.ToolExecutionStart
	14, // 9: glyph.plugins.extension.v1.LifecycleInvocation.tool_execution_update:type_name -> glyph.plugins.extension.v1.ToolExecutionUpdate
	15, // 10: glyph.plugins.extension.v1.LifecycleInvocation.tool_execution_end:type_name -> glyph.plugins.extension.v1.ToolExecutionEnd
	16, // 11: glyph.plugins.extension.v1.TurnEnd.response:type_name -> glyph.plugins.extension.v1.ConfiguredModelResult
	15, // 12: glyph.plugins.extension.v1.TurnEnd.tool_results:type_name -> glyph.plugins.extension.v1.ToolExecutionEnd
	0,  // 13: glyph.plugins.extension.v1.MessageUpdate.kind:type_name -> glyph.plugins.extension.v1.MessageUpdateKind
	17, // 14: glyph.plugins.extension.v1.MessageUpdate.content:type_name -> glyph.plugins.extension.v1.ConfiguredModelContent
	10, // 15: glyph.plugins.extension.v1.MessageUpdate.tool_call:type_name -> glyph.plugins.extension.v1.LifecycleToolCall
	11, // 16: glyph.plugins.extension.v1.LifecycleToolCall.fields:type_name -> glyph.plugins.extension.v1.LifecycleToolCallField
	16, // 17: glyph.plugins.extension.v1.MessageEnd.response:type_name -> glyph.plugins.extension.v1.ConfiguredModelResult
	18, // 18: glyph.plugins.extension.v1.ToolExecutionUpdate.channel:type_name -> glyph.plugins.extension.v1.ProgressChannel
	19, // 19: glyph.plugins.extension.v1.ToolExecutionEnd.contents:type_name -> glyph.plugins.extension.v1.ToolResultContent
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_api_plugins_extension_v1_lifecycle_proto_init() }
func file_api_plugins_extension_v1_lifecycle_proto_init() {
	if File_api_plugins_extension_v1_lifecycle_proto != nil {
		return
	}
	file_api_plugins_extension_v1_model_proto_init()
	file_api_plugins_extension_v1_tool_proto_init()
	file_api_plugins_extension_v1_lifecycle_proto_msgTypes[0].OneofWrappers = []any{
		(*lifecycleInvocation_AgentStart)(nil),
		(*lifecycleInvocation_AgentEnd)(nil),
		(*lifecycleInvocation_AgentSettled)(nil),
		(*lifecycleInvocation_TurnStart)(nil),
		(*lifecycleInvocation_TurnEnd)(nil),
		(*lifecycleInvocation_MessageStart)(nil),
		(*lifecycleInvocation_MessageUpdate)(nil),
		(*lifecycleInvocation_MessageEnd)(nil),
		(*lifecycleInvocation_ToolExecutionStart)(nil),
		(*lifecycleInvocation_ToolExecutionUpdate)(nil),
		(*lifecycleInvocation_ToolExecutionEnd)(nil),
	}
	file_api_plugins_extension_v1_lifecycle_proto_msgTypes[10].OneofWrappers = []any{
		(*lifecycleToolCallField_ValueJson)(nil),
		(*lifecycleToolCallField_Prefix)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugins_extension_v1_lifecycle_proto_rawDesc), len(file_api_plugins_extension_v1_lifecycle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_plugins_extension_v1_lifecycle_proto_goTypes,
		DependencyIndexes: file_api_plugins_extension_v1_lifecycle_proto_depIdxs,
		EnumInfos:         file_api_plugins_extension_v1_lifecycle_proto_enumTypes,
		MessageInfos:      file_api_plugins_extension_v1_lifecycle_proto_msgTypes,
	}.Build()
	File_api_plugins_extension_v1_lifecycle_proto = out.File
	file_api_plugins_extension_v1_lifecycle_proto_goTypes = nil
	file_api_plugins_extension_v1_lifecycle_proto_depIdxs = nil
}
