// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=runcontrol
//

// Package runcontrol is a generated GoMock package.
package runcontrol

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockExecutor) Run(arg0 context.Context, arg1 Request) (Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockExecutorMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExecutor)(nil).Run), arg0, arg1)
}

// Settle mocks base method.
func (m *MockExecutor) Settle(runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settle", runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Settle indicates an expected call of Settle.
func (mr *MockExecutorMockRecorder) Settle(runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settle", reflect.TypeOf((*MockExecutor)(nil).Settle), runID)
}

// MockSettledDelivery is a mock of SettledDelivery interface.
type MockSettledDelivery struct {
	ctrl     *gomock.Controller
	recorder *MockSettledDeliveryMockRecorder
	isgomock struct{}
}

// MockSettledDeliveryMockRecorder is the mock recorder for MockSettledDelivery.
type MockSettledDeliveryMockRecorder struct {
	mock *MockSettledDelivery
}

// NewMockSettledDelivery creates a new mock instance.
func NewMockSettledDelivery(ctrl *gomock.Controller) *MockSettledDelivery {
	mock := &MockSettledDelivery{ctrl: ctrl}
	mock.recorder = &MockSettledDeliveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettledDelivery) EXPECT() *MockSettledDeliveryMockRecorder {
	return m.recorder
}

// DeliverSettled mocks base method.
func (m *MockSettledDelivery) DeliverSettled(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverSettled", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeliverSettled indicates an expected call of DeliverSettled.
func (mr *MockSettledDeliveryMockRecorder) DeliverSettled(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverSettled", reflect.TypeOf((*MockSettledDelivery)(nil).DeliverSettled), arg0, arg1)
}

// MockGate is a mock of Gate interface.
type MockGate struct {
	ctrl     *gomock.Controller
	recorder *MockGateMockRecorder
	isgomock struct{}
}

// MockGateMockRecorder is the mock recorder for MockGate.
type MockGateMockRecorder struct {
	mock *MockGate
}

// NewMockGate creates a new mock instance.
func NewMockGate(ctrl *gomock.Controller) *MockGate {
	mock := &MockGate{ctrl: ctrl}
	mock.recorder = &MockGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGate) EXPECT() *MockGateMockRecorder {
	return m.recorder
}

// TryAcquire mocks base method.
func (m *MockGate) TryAcquire() (func(), bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquire")
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// TryAcquire indicates an expected call of TryAcquire.
func (mr *MockGateMockRecorder) TryAcquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquire", reflect.TypeOf((*MockGate)(nil).TryAcquire))
}
