// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=edit
//

// Package edit is a generated GoMock package.
package edit

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectEditor is a mock of ProjectEditor interface.
type MockProjectEditor struct {
	ctrl     *gomock.Controller
	recorder *MockProjectEditorMockRecorder
	isgomock struct{}
}

// MockProjectEditorMockRecorder is the mock recorder for MockProjectEditor.
type MockProjectEditorMockRecorder struct {
	mock *MockProjectEditor
}

// NewMockProjectEditor creates a new mock instance.
func NewMockProjectEditor(ctrl *gomock.Controller) *MockProjectEditor {
	mock := &MockProjectEditor{ctrl: ctrl}
	mock.recorder = &MockProjectEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectEditor) EXPECT() *MockProjectEditorMockRecorder {
	return m.recorder
}

// UpdateFile mocks base method.
func (m *MockProjectEditor) UpdateFile(arg0 context.Context, arg1 string, arg2 func([]byte) ([]byte, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile.
func (mr *MockProjectEditorMockRecorder) UpdateFile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockProjectEditor)(nil).UpdateFile), arg0, arg1, arg2)
}
