// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=compatible
//

// Package compatible is a generated GoMock package.
package compatible

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAPIKeyResolver is a mock of APIKeyResolver interface.
type MockAPIKeyResolver struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyResolverMockRecorder
	isgomock struct{}
}

// MockAPIKeyResolverMockRecorder is the mock recorder for MockAPIKeyResolver.
type MockAPIKeyResolverMockRecorder struct {
	mock *MockAPIKeyResolver
}

// NewMockAPIKeyResolver creates a new mock instance.
func NewMockAPIKeyResolver(ctrl *gomock.Controller) *MockAPIKeyResolver {
	mock := &MockAPIKeyResolver{ctrl: ctrl}
	mock.recorder = &MockAPIKeyResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyResolver) EXPECT() *MockAPIKeyResolverMockRecorder {
	return m.recorder
}

// ResolveAPIKey mocks base method.
func (m *MockAPIKeyResolver) ResolveAPIKey(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAPIKey", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAPIKey indicates an expected call of ResolveAPIKey.
func (mr *MockAPIKeyResolverMockRecorder) ResolveAPIKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAPIKey", reflect.TypeOf((*MockAPIKeyResolver)(nil).ResolveAPIKey), ctx)
}
