// Code generated by MockGen. DO NOT EDIT.
// Source: operation.go
//
// Generated by this command:
//
//	mockgen -source=operation.go -destination=interfaces_mock_test.go -package=operation
//

// Package operation is a generated GoMock package.
package operation

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrepared is a mock of Prepared interface.
type MockPrepared[P any, R any] struct {
	ctrl     *gomock.Controller
	recorder *MockPreparedMockRecorder[P, R]
	isgomock struct{}
}

// MockPreparedMockRecorder is the mock recorder for MockPrepared.
type MockPreparedMockRecorder[P any, R any] struct {
	mock *MockPrepared[P, R]
}

// NewMockPrepared creates a new mock instance.
func NewMockPrepared[P any, R any](ctrl *gomock.Controller) *MockPrepared[P, R] {
	mock := &MockPrepared[P, R]{ctrl: ctrl}
	mock.recorder = &MockPreparedMockRecorder[P, R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrepared[P, R]) EXPECT() *MockPreparedMockRecorder[P, R] {
	return m.recorder
}

// Release mocks base method.
func (m *MockPrepared[P, R]) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockPreparedMockRecorder[P, R]) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPrepared[P, R])(nil).Release))
}

// Run mocks base method.
func (m *MockPrepared[P, R]) Run(arg0 context.Context, arg1 Reporter[P]) Outcome[R] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(Outcome[R])
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockPreparedMockRecorder[P, R]) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPrepared[P, R])(nil).Run), arg0, arg1)
}

// MockDelivery is a mock of Delivery interface.
type MockDelivery[P any, R any] struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryMockRecorder[P, R]
	isgomock struct{}
}

// MockDeliveryMockRecorder is the mock recorder for MockDelivery.
type MockDeliveryMockRecorder[P any, R any] struct {
	mock *MockDelivery[P, R]
}

// NewMockDelivery creates a new mock instance.
func NewMockDelivery[P any, R any](ctrl *gomock.Controller) *MockDelivery[P, R] {
	mock := &MockDelivery[P, R]{ctrl: ctrl}
	mock.recorder = &MockDeliveryMockRecorder[P, R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelivery[P, R]) EXPECT() *MockDeliveryMockRecorder[P, R] {
	return m.recorder
}

// Accepted mocks base method.
func (m *MockDelivery[P, R]) Accepted(arg0 string) (*Acknowledgement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accepted", arg0)
	ret0, _ := ret[0].(*Acknowledgement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accepted indicates an expected call of Accepted.
func (mr *MockDeliveryMockRecorder[P, R]) Accepted(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accepted", reflect.TypeOf((*MockDelivery[P, R])(nil).Accepted), arg0)
}

// Progress mocks base method.
func (m *MockDelivery[P, R]) Progress(arg0 string, arg1 P) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Progress", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Progress indicates an expected call of Progress.
func (mr *MockDeliveryMockRecorder[P, R]) Progress(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockDelivery[P, R])(nil).Progress), arg0, arg1)
}

// Running mocks base method.
func (m *MockDelivery[P, R]) Running(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Running", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Running indicates an expected call of Running.
func (mr *MockDeliveryMockRecorder[P, R]) Running(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Running", reflect.TypeOf((*MockDelivery[P, R])(nil).Running), arg0)
}

// Terminal mocks base method.
func (m *MockDelivery[P, R]) Terminal(arg0 string, arg1 Outcome[R]) (*Acknowledgement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminal", arg0, arg1)
	ret0, _ := ret[0].(*Acknowledgement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Terminal indicates an expected call of Terminal.
func (mr *MockDeliveryMockRecorder[P, R]) Terminal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminal", reflect.TypeOf((*MockDelivery[P, R])(nil).Terminal), arg0, arg1)
}
