// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=write
//

// Package write is a generated GoMock package.
package write

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectWriter is a mock of ProjectWriter interface.
type MockProjectWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProjectWriterMockRecorder
	isgomock struct{}
}

// MockProjectWriterMockRecorder is the mock recorder for MockProjectWriter.
type MockProjectWriterMockRecorder struct {
	mock *MockProjectWriter
}

// NewMockProjectWriter creates a new mock instance.
func NewMockProjectWriter(ctrl *gomock.Controller) *MockProjectWriter {
	mock := &MockProjectWriter{ctrl: ctrl}
	mock.recorder = &MockProjectWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectWriter) EXPECT() *MockProjectWriterMockRecorder {
	return m.recorder
}

// WriteFile mocks base method.
func (m *MockProjectWriter) WriteFile(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockProjectWriterMockRecorder) WriteFile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockProjectWriter)(nil).WriteFile), arg0, arg1, arg2)
}
