// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=interfaces_mock_test.go -package=uiv1
//

// Package uiv1 is a generated GoMock package.
package uiv1

import (
	context "context"
	reflect "reflect"

	uiv1 "github.com/n-r-w/glyph/pkg/plugins/ui/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockService)(nil).Close))
}

// PrepareInitialize mocks base method.
func (m *MockService) PrepareInitialize(arg0 context.Context, arg1 *uiv1.Initialization) (InitializeOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareInitialize", arg0, arg1)
	ret0, _ := ret[0].(InitializeOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareInitialize indicates an expected call of PrepareInitialize.
func (mr *MockServiceMockRecorder) PrepareInitialize(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareInitialize", reflect.TypeOf((*MockService)(nil).PrepareInitialize), arg0, arg1)
}

// Run mocks base method.
func (m *MockService) Run(arg0 context.Context, arg1 *Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockServiceMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockService)(nil).Run), arg0, arg1)
}

// MockInitializeOperation is a mock of InitializeOperation interface.
type MockInitializeOperation struct {
	ctrl     *gomock.Controller
	recorder *MockInitializeOperationMockRecorder
	isgomock struct{}
}

// MockInitializeOperationMockRecorder is the mock recorder for MockInitializeOperation.
type MockInitializeOperationMockRecorder struct {
	mock *MockInitializeOperation
}

// NewMockInitializeOperation creates a new mock instance.
func NewMockInitializeOperation(ctrl *gomock.Controller) *MockInitializeOperation {
	mock := &MockInitializeOperation{ctrl: ctrl}
	mock.recorder = &MockInitializeOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitializeOperation) EXPECT() *MockInitializeOperationMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockInitializeOperation) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockInitializeOperationMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockInitializeOperation)(nil).Release))
}

// Run mocks base method.
func (m *MockInitializeOperation) Run(arg0 context.Context) (*uiv1.Initialized, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(*uiv1.Initialized)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockInitializeOperationMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockInitializeOperation)(nil).Run), arg0)
}
