//go:build integration

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/n-r-w/glyph/pkg/plugins/ui/v1 (interfaces: UIService_OpenServer)
//
// Generated by this command:
//
//	mockgen -build_constraint=integration -destination=stream_integration_mock_test.go -package=uiv1 github.com/n-r-w/glyph/pkg/plugins/ui/v1 UIService_OpenServer
//

// Package uiv1 is a generated GoMock package.
package uiv1

import (
	context "context"
	reflect "reflect"

	uiv1 "github.com/n-r-w/glyph/pkg/plugins/ui/v1"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockUIService_OpenServer is a mock of UIService_OpenServer interface.
type MockUIService_OpenServer[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockUIService_OpenServerMockRecorder[Req, Res]
	isgomock struct{}
}

// MockUIService_OpenServerMockRecorder is the mock recorder for MockUIService_OpenServer.
type MockUIService_OpenServerMockRecorder[Req any, Res any] struct {
	mock *MockUIService_OpenServer[Req, Res]
}

// NewMockUIService_OpenServer creates a new mock instance.
func NewMockUIService_OpenServer[Req any, Res any](ctrl *gomock.Controller) *MockUIService_OpenServer[Req, Res] {
	mock := &MockUIService_OpenServer[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockUIService_OpenServerMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUIService_OpenServer[Req, Res]) EXPECT() *MockUIService_OpenServerMockRecorder[Req, Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockUIService_OpenServer[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).Context))
}

// Recv mocks base method.
func (m *MockUIService_OpenServer[Req, Res]) Recv() (*uiv1.OpenRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*uiv1.OpenRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockUIService_OpenServer[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockUIService_OpenServer[Req, Res]) Send(arg0 *uiv1.OpenResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockUIService_OpenServer[Req, Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockUIService_OpenServer[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockUIService_OpenServer[Req, Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockUIService_OpenServer[Req, Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockUIService_OpenServerMockRecorder[Req, Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockUIService_OpenServer[Req, Res])(nil).SetTrailer), arg0)
}
