// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=extensioncontext
//

// Package extensioncontext is a generated GoMock package.
package extensioncontext

import (
	context "context"
	reflect "reflect"

	agent "github.com/n-r-w/glyph/host/internal/domain/agent"
	model "github.com/n-r-w/glyph/host/internal/domain/model"
	session "github.com/n-r-w/glyph/host/internal/domain/session"
	gomock "go.uber.org/mock/gomock"
)

// MockRuntimeState is a mock of RuntimeState interface.
type MockRuntimeState struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeStateMockRecorder
	isgomock struct{}
}

// MockRuntimeStateMockRecorder is the mock recorder for MockRuntimeState.
type MockRuntimeStateMockRecorder struct {
	mock *MockRuntimeState
}

// NewMockRuntimeState creates a new mock instance.
func NewMockRuntimeState(ctrl *gomock.Controller) *MockRuntimeState {
	mock := &MockRuntimeState{ctrl: ctrl}
	mock.recorder = &MockRuntimeStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeState) EXPECT() *MockRuntimeStateMockRecorder {
	return m.recorder
}

// BeginContextCommit mocks base method.
func (m *MockRuntimeState) BeginContextCommit(extensionID, runtimeID string) (func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginContextCommit", extensionID, runtimeID)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginContextCommit indicates an expected call of BeginContextCommit.
func (mr *MockRuntimeStateMockRecorder) BeginContextCommit(extensionID, runtimeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginContextCommit", reflect.TypeOf((*MockRuntimeState)(nil).BeginContextCommit), extensionID, runtimeID)
}

// ContextRuntime mocks base method.
func (m *MockRuntimeState) ContextRuntime(extensionID string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextRuntime", extensionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ContextRuntime indicates an expected call of ContextRuntime.
func (mr *MockRuntimeStateMockRecorder) ContextRuntime(extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextRuntime", reflect.TypeOf((*MockRuntimeState)(nil).ContextRuntime), extensionID)
}

// MockSessionState is a mock of SessionState interface.
type MockSessionState struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStateMockRecorder
	isgomock struct{}
}

// MockSessionStateMockRecorder is the mock recorder for MockSessionState.
type MockSessionStateMockRecorder struct {
	mock *MockSessionState
}

// NewMockSessionState creates a new mock instance.
func NewMockSessionState(ctrl *gomock.Controller) *MockSessionState {
	mock := &MockSessionState{ctrl: ctrl}
	mock.recorder = &MockSessionStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionState) EXPECT() *MockSessionStateMockRecorder {
	return m.recorder
}

// AppendExtension mocks base method.
func (m *MockSessionState) AppendExtension(arg0 context.Context, arg1 SessionIdentity, arg2 session.ExtensionEnvelope, arg3 ContextCommitGuard) (session.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExtension", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(session.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendExtension indicates an expected call of AppendExtension.
func (mr *MockSessionStateMockRecorder) AppendExtension(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExtension", reflect.TypeOf((*MockSessionState)(nil).AppendExtension), arg0, arg1, arg2, arg3)
}

// AppendExtensionMessage mocks base method.
func (m *MockSessionState) AppendExtensionMessage(arg0 context.Context, arg1 SessionIdentity, arg2 session.ExtensionMessage, arg3 ContextCommitGuard) (session.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExtensionMessage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(session.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendExtensionMessage indicates an expected call of AppendExtensionMessage.
func (mr *MockSessionStateMockRecorder) AppendExtensionMessage(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExtensionMessage", reflect.TypeOf((*MockSessionState)(nil).AppendExtensionMessage), arg0, arg1, arg2, arg3)
}

// ContextSession mocks base method.
func (m *MockSessionState) ContextSession() SessionIdentity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextSession")
	ret0, _ := ret[0].(SessionIdentity)
	return ret0
}

// ContextSession indicates an expected call of ContextSession.
func (mr *MockSessionStateMockRecorder) ContextSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextSession", reflect.TypeOf((*MockSessionState)(nil).ContextSession))
}

// ExtensionState mocks base method.
func (m *MockSessionState) ExtensionState(arg0 context.Context, arg1 SessionIdentity, arg2 string) (SessionSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtensionState", arg0, arg1, arg2)
	ret0, _ := ret[0].(SessionSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtensionState indicates an expected call of ExtensionState.
func (mr *MockSessionStateMockRecorder) ExtensionState(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtensionState", reflect.TypeOf((*MockSessionState)(nil).ExtensionState), arg0, arg1, arg2)
}

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// ActiveSelection mocks base method.
func (m *MockCatalog) ActiveSelection() model.Selection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveSelection")
	ret0, _ := ret[0].(model.Selection)
	return ret0
}

// ActiveSelection indicates an expected call of ActiveSelection.
func (mr *MockCatalogMockRecorder) ActiveSelection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveSelection", reflect.TypeOf((*MockCatalog)(nil).ActiveSelection))
}

// Models mocks base method.
func (m *MockCatalog) Models() []model.Descriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Models")
	ret0, _ := ret[0].([]model.Descriptor)
	return ret0
}

// Models indicates an expected call of Models.
func (mr *MockCatalogMockRecorder) Models() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Models", reflect.TypeOf((*MockCatalog)(nil).Models))
}

// Request mocks base method.
func (m *MockCatalog) Request(ctx context.Context, selection model.Selection, instructions string, history []agent.HistoryEntry) (model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, selection, instructions, history)
	ret0, _ := ret[0].(model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockCatalogMockRecorder) Request(ctx, selection, instructions, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockCatalog)(nil).Request), ctx, selection, instructions, history)
}

// MockRequestFailure is a mock of RequestFailure interface.
type MockRequestFailure struct {
	ctrl     *gomock.Controller
	recorder *MockRequestFailureMockRecorder
	isgomock struct{}
}

// MockRequestFailureMockRecorder is the mock recorder for MockRequestFailure.
type MockRequestFailureMockRecorder struct {
	mock *MockRequestFailure
}

// NewMockRequestFailure creates a new mock instance.
func NewMockRequestFailure(ctrl *gomock.Controller) *MockRequestFailure {
	mock := &MockRequestFailure{ctrl: ctrl}
	mock.recorder = &MockRequestFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestFailure) EXPECT() *MockRequestFailureMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockRequestFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockRequestFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockRequestFailure)(nil).Error))
}

// SelectionCode mocks base method.
func (m *MockRequestFailure) SelectionCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectionCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectionCode indicates an expected call of SelectionCode.
func (mr *MockRequestFailureMockRecorder) SelectionCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectionCode", reflect.TypeOf((*MockRequestFailure)(nil).SelectionCode))
}
