// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=startup
//

// Package startup is a generated GoMock package.
package startup

import (
	context "context"
	reflect "reflect"

	tools "github.com/n-r-w/glyph/host/internal/usecase/host/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// ReportIssue mocks base method.
func (m *MockReporter) ReportIssue(ctx context.Context, issue tools.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportIssue", ctx, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportIssue indicates an expected call of ReportIssue.
func (mr *MockReporterMockRecorder) ReportIssue(ctx, issue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportIssue", reflect.TypeOf((*MockReporter)(nil).ReportIssue), ctx, issue)
}

// ReportSummary mocks base method.
func (m *MockReporter) ReportSummary(ctx context.Context, report tools.LoadReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportSummary", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportSummary indicates an expected call of ReportSummary.
func (mr *MockReporterMockRecorder) ReportSummary(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportSummary", reflect.TypeOf((*MockReporter)(nil).ReportSummary), ctx, report)
}
