// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=sessiontree
//

// Package sessiontree is a generated GoMock package.
package sessiontree

import (
	context "context"
	reflect "reflect"

	session "github.com/n-r-w/glyph/host/internal/domain/session"
	mo "github.com/samber/mo"
	gomock "go.uber.org/mock/gomock"
)

// MockActiveSession is a mock of ActiveSession interface.
type MockActiveSession struct {
	ctrl     *gomock.Controller
	recorder *MockActiveSessionMockRecorder
	isgomock struct{}
}

// MockActiveSessionMockRecorder is the mock recorder for MockActiveSession.
type MockActiveSessionMockRecorder struct {
	mock *MockActiveSession
}

// NewMockActiveSession creates a new mock instance.
func NewMockActiveSession(ctrl *gomock.Controller) *MockActiveSession {
	mock := &MockActiveSession{ctrl: ctrl}
	mock.recorder = &MockActiveSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveSession) EXPECT() *MockActiveSessionMockRecorder {
	return m.recorder
}

// CommitNavigation mocks base method.
func (m *MockActiveSession) CommitNavigation(arg0 context.Context, arg1, arg2 mo.Option[string]) (session.Tree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitNavigation", arg0, arg1, arg2)
	ret0, _ := ret[0].(session.Tree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitNavigation indicates an expected call of CommitNavigation.
func (mr *MockActiveSessionMockRecorder) CommitNavigation(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitNavigation", reflect.TypeOf((*MockActiveSession)(nil).CommitNavigation), arg0, arg1, arg2)
}

// Tree mocks base method.
func (m *MockActiveSession) Tree() session.Tree {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree")
	ret0, _ := ret[0].(session.Tree)
	return ret0
}

// Tree indicates an expected call of Tree.
func (mr *MockActiveSessionMockRecorder) Tree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockActiveSession)(nil).Tree))
}
