// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=sessiontree
//

// Package sessiontree is a generated GoMock package.
package sessiontree

import (
	context "context"
	reflect "reflect"

	agent "github.com/n-r-w/glyph/host/internal/domain/agent"
	model "github.com/n-r-w/glyph/host/internal/domain/model"
	session "github.com/n-r-w/glyph/host/internal/domain/session"
	gomock "go.uber.org/mock/gomock"
)

// MockActiveSession is a mock of ActiveSession interface.
type MockActiveSession struct {
	ctrl     *gomock.Controller
	recorder *MockActiveSessionMockRecorder
	isgomock struct{}
}

// MockActiveSessionMockRecorder is the mock recorder for MockActiveSession.
type MockActiveSessionMockRecorder struct {
	mock *MockActiveSession
}

// NewMockActiveSession creates a new mock instance.
func NewMockActiveSession(ctrl *gomock.Controller) *MockActiveSession {
	mock := &MockActiveSession{ctrl: ctrl}
	mock.recorder = &MockActiveSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveSession) EXPECT() *MockActiveSessionMockRecorder {
	return m.recorder
}

// CommitNavigation mocks base method.
func (m *MockActiveSession) CommitNavigation(arg0 context.Context, arg1 CommitCommand) (session.Tree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitNavigation", arg0, arg1)
	ret0, _ := ret[0].(session.Tree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitNavigation indicates an expected call of CommitNavigation.
func (mr *MockActiveSessionMockRecorder) CommitNavigation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitNavigation", reflect.TypeOf((*MockActiveSession)(nil).CommitNavigation), arg0, arg1)
}

// SessionID mocks base method.
func (m *MockActiveSession) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockActiveSessionMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockActiveSession)(nil).SessionID))
}

// Tree mocks base method.
func (m *MockActiveSession) Tree() session.Tree {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree")
	ret0, _ := ret[0].(session.Tree)
	return ret0
}

// Tree indicates an expected call of Tree.
func (mr *MockActiveSessionMockRecorder) Tree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockActiveSession)(nil).Tree))
}

// MockHandlerRunner is a mock of HandlerRunner interface.
type MockHandlerRunner struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerRunnerMockRecorder
	isgomock struct{}
}

// MockHandlerRunnerMockRecorder is the mock recorder for MockHandlerRunner.
type MockHandlerRunnerMockRecorder struct {
	mock *MockHandlerRunner
}

// NewMockHandlerRunner creates a new mock instance.
func NewMockHandlerRunner(ctrl *gomock.Controller) *MockHandlerRunner {
	mock := &MockHandlerRunner{ctrl: ctrl}
	mock.recorder = &MockHandlerRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerRunner) EXPECT() *MockHandlerRunnerMockRecorder {
	return m.recorder
}

// HandleRequest mocks base method.
func (m *MockHandlerRunner) HandleRequest(arg0 context.Context, arg1 Handler, arg2 RequestHandlerInvocation) (RequestHandlerAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRequest", arg0, arg1, arg2)
	ret0, _ := ret[0].(RequestHandlerAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRequest indicates an expected call of HandleRequest.
func (mr *MockHandlerRunnerMockRecorder) HandleRequest(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequest", reflect.TypeOf((*MockHandlerRunner)(nil).HandleRequest), arg0, arg1, arg2)
}

// HandleResult mocks base method.
func (m *MockHandlerRunner) HandleResult(arg0 context.Context, arg1 Handler, arg2 ResultHandlerInvocation) (ResultHandlerAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleResult", arg0, arg1, arg2)
	ret0, _ := ret[0].(ResultHandlerAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleResult indicates an expected call of HandleResult.
func (mr *MockHandlerRunnerMockRecorder) HandleResult(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleResult", reflect.TypeOf((*MockHandlerRunner)(nil).HandleResult), arg0, arg1, arg2)
}

// Handlers mocks base method.
func (m *MockHandlerRunner) Handlers(arg0 HandlerKind) []Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handlers", arg0)
	ret0, _ := ret[0].([]Handler)
	return ret0
}

// Handlers indicates an expected call of Handlers.
func (mr *MockHandlerRunnerMockRecorder) Handlers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handlers", reflect.TypeOf((*MockHandlerRunner)(nil).Handlers), arg0)
}

// Observe mocks base method.
func (m *MockHandlerRunner) Observe(arg0 context.Context, arg1 Handler, arg2 TreeObserverInvocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Observe", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Observe indicates an expected call of Observe.
func (mr *MockHandlerRunnerMockRecorder) Observe(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockHandlerRunner)(nil).Observe), arg0, arg1, arg2)
}

// MockModelRequester is a mock of ModelRequester interface.
type MockModelRequester struct {
	ctrl     *gomock.Controller
	recorder *MockModelRequesterMockRecorder
	isgomock struct{}
}

// MockModelRequesterMockRecorder is the mock recorder for MockModelRequester.
type MockModelRequesterMockRecorder struct {
	mock *MockModelRequester
}

// NewMockModelRequester creates a new mock instance.
func NewMockModelRequester(ctrl *gomock.Controller) *MockModelRequester {
	mock := &MockModelRequester{ctrl: ctrl}
	mock.recorder = &MockModelRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelRequester) EXPECT() *MockModelRequesterMockRecorder {
	return m.recorder
}

// ActiveSelection mocks base method.
func (m *MockModelRequester) ActiveSelection() model.Selection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveSelection")
	ret0, _ := ret[0].(model.Selection)
	return ret0
}

// ActiveSelection indicates an expected call of ActiveSelection.
func (mr *MockModelRequesterMockRecorder) ActiveSelection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveSelection", reflect.TypeOf((*MockModelRequester)(nil).ActiveSelection))
}

// CheckAvailability mocks base method.
func (m *MockModelRequester) CheckAvailability(ctx context.Context, selection model.Selection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailability", ctx, selection)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAvailability indicates an expected call of CheckAvailability.
func (mr *MockModelRequesterMockRecorder) CheckAvailability(ctx, selection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailability", reflect.TypeOf((*MockModelRequester)(nil).CheckAvailability), ctx, selection)
}

// Request mocks base method.
func (m *MockModelRequester) Request(ctx context.Context, selection model.Selection, instructions string, history []agent.HistoryEntry) (model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, selection, instructions, history)
	ret0, _ := ret[0].(model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockModelRequesterMockRecorder) Request(ctx, selection, instructions, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockModelRequester)(nil).Request), ctx, selection, instructions, history)
}
