// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=programmatic
//

// Package programmatic is a generated GoMock package.
package programmatic

import (
	context "context"
	reflect "reflect"

	agent "github.com/n-r-w/glyph/host/internal/domain/agent"
	model "github.com/n-r-w/glyph/host/internal/domain/model"
	session "github.com/n-r-w/glyph/host/internal/domain/session"
	sessionnavigation "github.com/n-r-w/glyph/host/internal/usecase/host/sessionnavigation"
	gomock "go.uber.org/mock/gomock"
)

// MockCoordinator is a mock of Coordinator interface.
type MockCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorMockRecorder
	isgomock struct{}
}

// MockCoordinatorMockRecorder is the mock recorder for MockCoordinator.
type MockCoordinatorMockRecorder struct {
	mock *MockCoordinator
}

// NewMockCoordinator creates a new mock instance.
func NewMockCoordinator(ctrl *gomock.Controller) *MockCoordinator {
	mock := &MockCoordinator{ctrl: ctrl}
	mock.recorder = &MockCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinator) EXPECT() *MockCoordinatorMockRecorder {
	return m.recorder
}

// CancelPrepared mocks base method.
func (m *MockCoordinator) CancelPrepared(runID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelPrepared", runID)
}

// CancelPrepared indicates an expected call of CancelPrepared.
func (mr *MockCoordinatorMockRecorder) CancelPrepared(runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPrepared", reflect.TypeOf((*MockCoordinator)(nil).CancelPrepared), runID)
}

// PrepareRun mocks base method.
func (m *MockCoordinator) PrepareRun() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareRun")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareRun indicates an expected call of PrepareRun.
func (mr *MockCoordinatorMockRecorder) PrepareRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareRun", reflect.TypeOf((*MockCoordinator)(nil).PrepareRun))
}

// RunPrepared mocks base method.
func (m *MockCoordinator) RunPrepared(ctx context.Context, runID, userText string) (agent.RunOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPrepared", ctx, runID, userText)
	ret0, _ := ret[0].(agent.RunOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunPrepared indicates an expected call of RunPrepared.
func (mr *MockCoordinatorMockRecorder) RunPrepared(ctx, runID, userText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPrepared", reflect.TypeOf((*MockCoordinator)(nil).RunPrepared), ctx, runID, userText)
}

// MockSessionControl is a mock of SessionControl interface.
type MockSessionControl struct {
	ctrl     *gomock.Controller
	recorder *MockSessionControlMockRecorder
	isgomock struct{}
}

// MockSessionControlMockRecorder is the mock recorder for MockSessionControl.
type MockSessionControlMockRecorder struct {
	mock *MockSessionControl
}

// NewMockSessionControl creates a new mock instance.
func NewMockSessionControl(ctrl *gomock.Controller) *MockSessionControl {
	mock := &MockSessionControl{ctrl: ctrl}
	mock.recorder = &MockSessionControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionControl) EXPECT() *MockSessionControlMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionControl) Create(arg0 context.Context) (session.Replacement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(session.Replacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionControlMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionControl)(nil).Create), arg0)
}

// Entries mocks base method.
func (m *MockSessionControl) Entries() []session.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entries")
	ret0, _ := ret[0].([]session.Entry)
	return ret0
}

// Entries indicates an expected call of Entries.
func (mr *MockSessionControlMockRecorder) Entries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entries", reflect.TypeOf((*MockSessionControl)(nil).Entries))
}

// Info mocks base method.
func (m *MockSessionControl) Info() session.Info {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(session.Info)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockSessionControlMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockSessionControl)(nil).Info))
}

// List mocks base method.
func (m *MockSessionControl) List(arg0 context.Context) ([]session.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]session.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSessionControlMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionControl)(nil).List), arg0)
}

// Navigate mocks base method.
func (m *MockSessionControl) Navigate(arg0 context.Context, arg1 string) (sessionnavigation.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Navigate", arg0, arg1)
	ret0, _ := ret[0].(sessionnavigation.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Navigate indicates an expected call of Navigate.
func (mr *MockSessionControlMockRecorder) Navigate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Navigate", reflect.TypeOf((*MockSessionControl)(nil).Navigate), arg0, arg1)
}

// Resume mocks base method.
func (m *MockSessionControl) Resume(arg0 context.Context, arg1 session.ID) (session.Replacement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", arg0, arg1)
	ret0, _ := ret[0].(session.Replacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockSessionControlMockRecorder) Resume(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockSessionControl)(nil).Resume), arg0, arg1)
}

// SetName mocks base method.
func (m *MockSessionControl) SetName(arg0 context.Context, arg1 string) (session.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetName", arg0, arg1)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetName indicates an expected call of SetName.
func (mr *MockSessionControlMockRecorder) SetName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockSessionControl)(nil).SetName), arg0, arg1)
}

// Statistics mocks base method.
func (m *MockSessionControl) Statistics() session.Statistics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statistics")
	ret0, _ := ret[0].(session.Statistics)
	return ret0
}

// Statistics indicates an expected call of Statistics.
func (mr *MockSessionControlMockRecorder) Statistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statistics", reflect.TypeOf((*MockSessionControl)(nil).Statistics))
}

// Tree mocks base method.
func (m *MockSessionControl) Tree() session.Tree {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree")
	ret0, _ := ret[0].(session.Tree)
	return ret0
}

// Tree indicates an expected call of Tree.
func (mr *MockSessionControlMockRecorder) Tree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockSessionControl)(nil).Tree))
}

// MockSelectionFailure is a mock of SelectionFailure interface.
type MockSelectionFailure struct {
	ctrl     *gomock.Controller
	recorder *MockSelectionFailureMockRecorder
	isgomock struct{}
}

// MockSelectionFailureMockRecorder is the mock recorder for MockSelectionFailure.
type MockSelectionFailureMockRecorder struct {
	mock *MockSelectionFailure
}

// NewMockSelectionFailure creates a new mock instance.
func NewMockSelectionFailure(ctrl *gomock.Controller) *MockSelectionFailure {
	mock := &MockSelectionFailure{ctrl: ctrl}
	mock.recorder = &MockSelectionFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSelectionFailure) EXPECT() *MockSelectionFailureMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockSelectionFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockSelectionFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSelectionFailure)(nil).Error))
}

// SelectionCode mocks base method.
func (m *MockSelectionFailure) SelectionCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectionCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectionCode indicates an expected call of SelectionCode.
func (mr *MockSelectionFailureMockRecorder) SelectionCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectionCode", reflect.TypeOf((*MockSelectionFailure)(nil).SelectionCode))
}

// MockModelCatalog is a mock of ModelCatalog interface.
type MockModelCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockModelCatalogMockRecorder
	isgomock struct{}
}

// MockModelCatalogMockRecorder is the mock recorder for MockModelCatalog.
type MockModelCatalogMockRecorder struct {
	mock *MockModelCatalog
}

// NewMockModelCatalog creates a new mock instance.
func NewMockModelCatalog(ctrl *gomock.Controller) *MockModelCatalog {
	mock := &MockModelCatalog{ctrl: ctrl}
	mock.recorder = &MockModelCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelCatalog) EXPECT() *MockModelCatalogMockRecorder {
	return m.recorder
}

// Models mocks base method.
func (m *MockModelCatalog) Models() []model.Descriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Models")
	ret0, _ := ret[0].([]model.Descriptor)
	return ret0
}

// Models indicates an expected call of Models.
func (mr *MockModelCatalogMockRecorder) Models() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Models", reflect.TypeOf((*MockModelCatalog)(nil).Models))
}

// SelectModel mocks base method.
func (m *MockModelCatalog) SelectModel(ctx context.Context, provider model.ProviderID, modelID model.ID) (model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectModel", ctx, provider, modelID)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectModel indicates an expected call of SelectModel.
func (mr *MockModelCatalogMockRecorder) SelectModel(ctx, provider, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectModel", reflect.TypeOf((*MockModelCatalog)(nil).SelectModel), ctx, provider, modelID)
}

// SelectReasoningChoice mocks base method.
func (m *MockModelCatalog) SelectReasoningChoice(level model.ReasoningChoice) (model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectReasoningChoice", level)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectReasoningChoice indicates an expected call of SelectReasoningChoice.
func (mr *MockModelCatalogMockRecorder) SelectReasoningChoice(level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectReasoningChoice", reflect.TypeOf((*MockModelCatalog)(nil).SelectReasoningChoice), level)
}

// Selection mocks base method.
func (m *MockModelCatalog) Selection() model.Selection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selection")
	ret0, _ := ret[0].(model.Selection)
	return ret0
}

// Selection indicates an expected call of Selection.
func (mr *MockModelCatalogMockRecorder) Selection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selection", reflect.TypeOf((*MockModelCatalog)(nil).Selection))
}
