// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=programmatic
//

// Package programmatic is a generated GoMock package.
package programmatic

import (
	context "context"
	reflect "reflect"

	programmatic "github.com/n-r-w/glyph/host/internal/controller/programmatic"
	agent "github.com/n-r-w/glyph/host/internal/domain/agent"
	model "github.com/n-r-w/glyph/host/internal/domain/model"
	session "github.com/n-r-w/glyph/host/internal/domain/session"
	operation "github.com/n-r-w/glyph/internal/operation"
	gomock "go.uber.org/mock/gomock"
)

// MockStateQuery is a mock of StateQuery interface.
type MockStateQuery struct {
	ctrl     *gomock.Controller
	recorder *MockStateQueryMockRecorder
	isgomock struct{}
}

// MockStateQueryMockRecorder is the mock recorder for MockStateQuery.
type MockStateQueryMockRecorder struct {
	mock *MockStateQuery
}

// NewMockStateQuery creates a new mock instance.
func NewMockStateQuery(ctrl *gomock.Controller) *MockStateQuery {
	mock := &MockStateQuery{ctrl: ctrl}
	mock.recorder = &MockStateQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateQuery) EXPECT() *MockStateQueryMockRecorder {
	return m.recorder
}

// RunActive mocks base method.
func (m *MockStateQuery) RunActive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunActive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RunActive indicates an expected call of RunActive.
func (mr *MockStateQueryMockRecorder) RunActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunActive", reflect.TypeOf((*MockStateQuery)(nil).RunActive))
}

// MockRunOutput is a mock of RunOutput interface.
type MockRunOutput struct {
	ctrl     *gomock.Controller
	recorder *MockRunOutputMockRecorder
	isgomock struct{}
}

// MockRunOutputMockRecorder is the mock recorder for MockRunOutput.
type MockRunOutputMockRecorder struct {
	mock *MockRunOutput
}

// NewMockRunOutput creates a new mock instance.
func NewMockRunOutput(ctrl *gomock.Controller) *MockRunOutput {
	mock := &MockRunOutput{ctrl: ctrl}
	mock.recorder = &MockRunOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunOutput) EXPECT() *MockRunOutputMockRecorder {
	return m.recorder
}

// ActiveOperation mocks base method.
func (m *MockRunOutput) ActiveOperation() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveOperation")
	ret0, _ := ret[0].(string)
	return ret0
}

// ActiveOperation indicates an expected call of ActiveOperation.
func (mr *MockRunOutputMockRecorder) ActiveOperation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveOperation", reflect.TypeOf((*MockRunOutput)(nil).ActiveOperation))
}

// BindProgress mocks base method.
func (m *MockRunOutput) BindProgress(runID string, reporter operation.Reporter[programmatic.OperationProgress]) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindProgress", runID, reporter)
	ret0, _ := ret[0].(func())
	return ret0
}

// BindProgress indicates an expected call of BindProgress.
func (mr *MockRunOutputMockRecorder) BindProgress(runID, reporter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindProgress", reflect.TypeOf((*MockRunOutput)(nil).BindProgress), runID, reporter)
}

// CancelPrepared mocks base method.
func (m *MockRunOutput) CancelPrepared(runID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelPrepared", runID)
}

// CancelPrepared indicates an expected call of CancelPrepared.
func (mr *MockRunOutputMockRecorder) CancelPrepared(runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPrepared", reflect.TypeOf((*MockRunOutput)(nil).CancelPrepared), runID)
}

// Reserve mocks base method.
func (m *MockRunOutput) Reserve(operationID, runID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", operationID, runID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockRunOutputMockRecorder) Reserve(operationID, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockRunOutput)(nil).Reserve), operationID, runID)
}

// MockCoordinator is a mock of Coordinator interface.
type MockCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorMockRecorder
	isgomock struct{}
}

// MockCoordinatorMockRecorder is the mock recorder for MockCoordinator.
type MockCoordinatorMockRecorder struct {
	mock *MockCoordinator
}

// NewMockCoordinator creates a new mock instance.
func NewMockCoordinator(ctrl *gomock.Controller) *MockCoordinator {
	mock := &MockCoordinator{ctrl: ctrl}
	mock.recorder = &MockCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinator) EXPECT() *MockCoordinatorMockRecorder {
	return m.recorder
}

// CancelPrepared mocks base method.
func (m *MockCoordinator) CancelPrepared(runID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelPrepared", runID)
}

// CancelPrepared indicates an expected call of CancelPrepared.
func (mr *MockCoordinatorMockRecorder) CancelPrepared(runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPrepared", reflect.TypeOf((*MockCoordinator)(nil).CancelPrepared), runID)
}

// PrepareRun mocks base method.
func (m *MockCoordinator) PrepareRun() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareRun")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareRun indicates an expected call of PrepareRun.
func (mr *MockCoordinatorMockRecorder) PrepareRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareRun", reflect.TypeOf((*MockCoordinator)(nil).PrepareRun))
}

// RunPrepared mocks base method.
func (m *MockCoordinator) RunPrepared(ctx context.Context, runID, userText string) (agent.RunOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPrepared", ctx, runID, userText)
	ret0, _ := ret[0].(agent.RunOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunPrepared indicates an expected call of RunPrepared.
func (mr *MockCoordinatorMockRecorder) RunPrepared(ctx, runID, userText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPrepared", reflect.TypeOf((*MockCoordinator)(nil).RunPrepared), ctx, runID, userText)
}

// MockActiveSessions is a mock of ActiveSessions interface.
type MockActiveSessions struct {
	ctrl     *gomock.Controller
	recorder *MockActiveSessionsMockRecorder
	isgomock struct{}
}

// MockActiveSessionsMockRecorder is the mock recorder for MockActiveSessions.
type MockActiveSessionsMockRecorder struct {
	mock *MockActiveSessions
}

// NewMockActiveSessions creates a new mock instance.
func NewMockActiveSessions(ctrl *gomock.Controller) *MockActiveSessions {
	mock := &MockActiveSessions{ctrl: ctrl}
	mock.recorder = &MockActiveSessionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveSessions) EXPECT() *MockActiveSessionsMockRecorder {
	return m.recorder
}

// ActiveEntries mocks base method.
func (m *MockActiveSessions) ActiveEntries() []session.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveEntries")
	ret0, _ := ret[0].([]session.Entry)
	return ret0
}

// ActiveEntries indicates an expected call of ActiveEntries.
func (mr *MockActiveSessionsMockRecorder) ActiveEntries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveEntries", reflect.TypeOf((*MockActiveSessions)(nil).ActiveEntries))
}

// ActiveInfo mocks base method.
func (m *MockActiveSessions) ActiveInfo() session.Info {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveInfo")
	ret0, _ := ret[0].(session.Info)
	return ret0
}

// ActiveInfo indicates an expected call of ActiveInfo.
func (mr *MockActiveSessionsMockRecorder) ActiveInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveInfo", reflect.TypeOf((*MockActiveSessions)(nil).ActiveInfo))
}

// ActiveStatistics mocks base method.
func (m *MockActiveSessions) ActiveStatistics() session.Statistics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveStatistics")
	ret0, _ := ret[0].(session.Statistics)
	return ret0
}

// ActiveStatistics indicates an expected call of ActiveStatistics.
func (mr *MockActiveSessionsMockRecorder) ActiveStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveStatistics", reflect.TypeOf((*MockActiveSessions)(nil).ActiveStatistics))
}

// ClientSnapshot mocks base method.
func (m *MockActiveSessions) ClientSnapshot() []agent.HistoryEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientSnapshot")
	ret0, _ := ret[0].([]agent.HistoryEntry)
	return ret0
}

// ClientSnapshot indicates an expected call of ClientSnapshot.
func (mr *MockActiveSessionsMockRecorder) ClientSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientSnapshot", reflect.TypeOf((*MockActiveSessions)(nil).ClientSnapshot))
}

// CloneActive mocks base method.
func (m *MockActiveSessions) CloneActive(arg0 context.Context) (session.Info, []session.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneActive", arg0)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].([]session.Entry)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CloneActive indicates an expected call of CloneActive.
func (mr *MockActiveSessionsMockRecorder) CloneActive(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneActive", reflect.TypeOf((*MockActiveSessions)(nil).CloneActive), arg0)
}

// CreateActive mocks base method.
func (m *MockActiveSessions) CreateActive() (session.Info, []session.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActive")
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].([]session.Entry)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateActive indicates an expected call of CreateActive.
func (mr *MockActiveSessionsMockRecorder) CreateActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActive", reflect.TypeOf((*MockActiveSessions)(nil).CreateActive))
}

// ForkActive mocks base method.
func (m *MockActiveSessions) ForkActive(arg0 context.Context, arg1 string) (session.Info, []session.Entry, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkActive", arg0, arg1)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].([]session.Entry)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ForkActive indicates an expected call of ForkActive.
func (mr *MockActiveSessionsMockRecorder) ForkActive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkActive", reflect.TypeOf((*MockActiveSessions)(nil).ForkActive), arg0, arg1)
}

// ListProgrammaticSessions mocks base method.
func (m *MockActiveSessions) ListProgrammaticSessions(arg0 context.Context) ([]StoredSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProgrammaticSessions", arg0)
	ret0, _ := ret[0].([]StoredSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProgrammaticSessions indicates an expected call of ListProgrammaticSessions.
func (mr *MockActiveSessionsMockRecorder) ListProgrammaticSessions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProgrammaticSessions", reflect.TypeOf((*MockActiveSessions)(nil).ListProgrammaticSessions), arg0)
}

// ResumeActive mocks base method.
func (m *MockActiveSessions) ResumeActive(arg0 context.Context, arg1 session.ID) (session.Info, []session.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeActive", arg0, arg1)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].([]session.Entry)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResumeActive indicates an expected call of ResumeActive.
func (mr *MockActiveSessionsMockRecorder) ResumeActive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeActive", reflect.TypeOf((*MockActiveSessions)(nil).ResumeActive), arg0, arg1)
}

// SetActiveName mocks base method.
func (m *MockActiveSessions) SetActiveName(arg0 context.Context, arg1 string) (session.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveName", arg0, arg1)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActiveName indicates an expected call of SetActiveName.
func (mr *MockActiveSessionsMockRecorder) SetActiveName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveName", reflect.TypeOf((*MockActiveSessions)(nil).SetActiveName), arg0, arg1)
}

// SetLabel mocks base method.
func (m *MockActiveSessions) SetLabel(arg0 context.Context, arg1, arg2 string) (session.Tree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabel", arg0, arg1, arg2)
	ret0, _ := ret[0].(session.Tree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLabel indicates an expected call of SetLabel.
func (mr *MockActiveSessionsMockRecorder) SetLabel(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabel", reflect.TypeOf((*MockActiveSessions)(nil).SetLabel), arg0, arg1, arg2)
}

// Tree mocks base method.
func (m *MockActiveSessions) Tree() session.Tree {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree")
	ret0, _ := ret[0].(session.Tree)
	return ret0
}

// Tree indicates an expected call of Tree.
func (mr *MockActiveSessionsMockRecorder) Tree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockActiveSessions)(nil).Tree))
}

// MockSelectionFailure is a mock of SelectionFailure interface.
type MockSelectionFailure struct {
	ctrl     *gomock.Controller
	recorder *MockSelectionFailureMockRecorder
	isgomock struct{}
}

// MockSelectionFailureMockRecorder is the mock recorder for MockSelectionFailure.
type MockSelectionFailureMockRecorder struct {
	mock *MockSelectionFailure
}

// NewMockSelectionFailure creates a new mock instance.
func NewMockSelectionFailure(ctrl *gomock.Controller) *MockSelectionFailure {
	mock := &MockSelectionFailure{ctrl: ctrl}
	mock.recorder = &MockSelectionFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSelectionFailure) EXPECT() *MockSelectionFailureMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockSelectionFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockSelectionFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockSelectionFailure)(nil).Error))
}

// SelectionCode mocks base method.
func (m *MockSelectionFailure) SelectionCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectionCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectionCode indicates an expected call of SelectionCode.
func (mr *MockSelectionFailureMockRecorder) SelectionCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectionCode", reflect.TypeOf((*MockSelectionFailure)(nil).SelectionCode))
}

// MockModelCatalog is a mock of ModelCatalog interface.
type MockModelCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockModelCatalogMockRecorder
	isgomock struct{}
}

// MockModelCatalogMockRecorder is the mock recorder for MockModelCatalog.
type MockModelCatalogMockRecorder struct {
	mock *MockModelCatalog
}

// NewMockModelCatalog creates a new mock instance.
func NewMockModelCatalog(ctrl *gomock.Controller) *MockModelCatalog {
	mock := &MockModelCatalog{ctrl: ctrl}
	mock.recorder = &MockModelCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelCatalog) EXPECT() *MockModelCatalogMockRecorder {
	return m.recorder
}

// ActiveSelection mocks base method.
func (m *MockModelCatalog) ActiveSelection() model.Selection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveSelection")
	ret0, _ := ret[0].(model.Selection)
	return ret0
}

// ActiveSelection indicates an expected call of ActiveSelection.
func (mr *MockModelCatalogMockRecorder) ActiveSelection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveSelection", reflect.TypeOf((*MockModelCatalog)(nil).ActiveSelection))
}

// Models mocks base method.
func (m *MockModelCatalog) Models() []model.Descriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Models")
	ret0, _ := ret[0].([]model.Descriptor)
	return ret0
}

// Models indicates an expected call of Models.
func (mr *MockModelCatalogMockRecorder) Models() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Models", reflect.TypeOf((*MockModelCatalog)(nil).Models))
}

// SelectModel mocks base method.
func (m *MockModelCatalog) SelectModel(ctx context.Context, provider model.ProviderID, modelID model.ID) (model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectModel", ctx, provider, modelID)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectModel indicates an expected call of SelectModel.
func (mr *MockModelCatalogMockRecorder) SelectModel(ctx, provider, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectModel", reflect.TypeOf((*MockModelCatalog)(nil).SelectModel), ctx, provider, modelID)
}

// SelectReasoningChoice mocks base method.
func (m *MockModelCatalog) SelectReasoningChoice(choice model.ReasoningChoice) (model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectReasoningChoice", choice)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectReasoningChoice indicates an expected call of SelectReasoningChoice.
func (mr *MockModelCatalogMockRecorder) SelectReasoningChoice(choice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectReasoningChoice", reflect.TypeOf((*MockModelCatalog)(nil).SelectReasoningChoice), choice)
}

// MockGate is a mock of Gate interface.
type MockGate struct {
	ctrl     *gomock.Controller
	recorder *MockGateMockRecorder
	isgomock struct{}
}

// MockGateMockRecorder is the mock recorder for MockGate.
type MockGateMockRecorder struct {
	mock *MockGate
}

// NewMockGate creates a new mock instance.
func NewMockGate(ctrl *gomock.Controller) *MockGate {
	mock := &MockGate{ctrl: ctrl}
	mock.recorder = &MockGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGate) EXPECT() *MockGateMockRecorder {
	return m.recorder
}

// TryAcquire mocks base method.
func (m *MockGate) TryAcquire() (func(), bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquire")
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// TryAcquire indicates an expected call of TryAcquire.
func (mr *MockGateMockRecorder) TryAcquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquire", reflect.TypeOf((*MockGate)(nil).TryAcquire))
}
