// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: api/operation/v1/operation.proto

package operationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TerminalState identifies an operation terminal state.
type TerminalState int32

const (
	// TERMINAL_STATE_UNSPECIFIED is not a valid terminal state.
	TerminalState_TERMINAL_STATE_UNSPECIFIED TerminalState = 0
	// TERMINAL_STATE_COMPLETED reports successful completion.
	TerminalState_TERMINAL_STATE_COMPLETED TerminalState = 1
	// TERMINAL_STATE_CANCELED reports cancellation.
	TerminalState_TERMINAL_STATE_CANCELED TerminalState = 2
	// TERMINAL_STATE_FAILED reports failure.
	TerminalState_TERMINAL_STATE_FAILED TerminalState = 3
)

// Enum value maps for TerminalState.
var (
	TerminalState_name = map[int32]string{
		0: "TERMINAL_STATE_UNSPECIFIED",
		1: "TERMINAL_STATE_COMPLETED",
		2: "TERMINAL_STATE_CANCELED",
		3: "TERMINAL_STATE_FAILED",
	}
	TerminalState_value = map[string]int32{
		"TERMINAL_STATE_UNSPECIFIED": 0,
		"TERMINAL_STATE_COMPLETED":   1,
		"TERMINAL_STATE_CANCELED":    2,
		"TERMINAL_STATE_FAILED":      3,
	}
)

func (x TerminalState) Enum() *TerminalState {
	p := new(TerminalState)
	*p = x
	return p
}

func (x TerminalState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_operation_v1_operation_proto_enumTypes[0].Descriptor()
}

func (TerminalState) Type() protoreflect.EnumType {
	return &file_api_operation_v1_operation_proto_enumTypes[0]
}

func (x TerminalState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Accepted reports that a request created an operation.
type Accepted struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accepted) Reset() {
	*x = Accepted{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accepted) ProtoMessage() {}

func (x *Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Accepted_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Accepted_builder) Build() *Accepted {
	m0 := &Accepted{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Running reports that accepted operation work started.
type Running struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Running) Reset() {
	*x = Running{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Running) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Running) ProtoMessage() {}

func (x *Running) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Running_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Running_builder) Build() *Running {
	m0 := &Running{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Rejected reports that a request did not create an operation.
type Rejected struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code        *string                `protobuf:"bytes,1,opt,name=code"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Rejected) GetCode() string {
	if x != nil {
		if x.xxx_hidden_Code != nil {
			return *x.xxx_hidden_Code
		}
		return ""
	}
	return ""
}

func (x *Rejected) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *Rejected) SetCode(v string) {
	x.xxx_hidden_Code = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Rejected) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Rejected) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Rejected) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Rejected) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = nil
}

func (x *Rejected) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type Rejected_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The machine-readable rejection code.
	Code *string
	// The complete rejection error text.
	Message *string
}

func (b0 Rejected_builder) Build() *Rejected {
	m0 := &Rejected{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Code = b.Code
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

// Canceled reports that an operation stopped because it was canceled.
type Canceled struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Canceled) Reset() {
	*x = Canceled{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Canceled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Canceled) ProtoMessage() {}

func (x *Canceled) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Canceled_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Canceled_builder) Build() *Canceled {
	m0 := &Canceled{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Failed reports that an operation failed.
type Failed struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code        *string                `protobuf:"bytes,1,opt,name=code"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Failed) Reset() {
	*x = Failed{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failed) ProtoMessage() {}

func (x *Failed) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Failed) GetCode() string {
	if x != nil {
		if x.xxx_hidden_Code != nil {
			return *x.xxx_hidden_Code
		}
		return ""
	}
	return ""
}

func (x *Failed) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *Failed) SetCode(v string) {
	x.xxx_hidden_Code = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Failed) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Failed) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Failed) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Failed) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = nil
}

func (x *Failed) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type Failed_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The machine-readable failure code.
	Code *string
	// The complete failure error text.
	Message *string
}

func (b0 Failed_builder) Build() *Failed {
	m0 := &Failed{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Code = b.Code
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

// CancelOperation requests cancellation of an active operation.
type CancelOperation struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TargetOperationId *string                `protobuf:"bytes,1,opt,name=target_operation_id,json=targetOperationId"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CancelOperation) Reset() {
	*x = CancelOperation{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperation) ProtoMessage() {}

func (x *CancelOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CancelOperation) GetTargetOperationId() string {
	if x != nil {
		if x.xxx_hidden_TargetOperationId != nil {
			return *x.xxx_hidden_TargetOperationId
		}
		return ""
	}
	return ""
}

func (x *CancelOperation) SetTargetOperationId(v string) {
	x.xxx_hidden_TargetOperationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CancelOperation) HasTargetOperationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CancelOperation) ClearTargetOperationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TargetOperationId = nil
}

type CancelOperation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identifier of the operation to cancel.
	TargetOperationId *string
}

func (b0 CancelOperation_builder) Build() *CancelOperation {
	m0 := &CancelOperation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TargetOperationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_TargetOperationId = b.TargetOperationId
	}
	return m0
}

// CancelCompleted reports the target operation terminal state.
type CancelCompleted struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TargetState TerminalState          `protobuf:"varint,1,opt,name=target_state,json=targetState,enum=glyph.operation.v1.TerminalState"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CancelCompleted) Reset() {
	*x = CancelCompleted{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCompleted) ProtoMessage() {}

func (x *CancelCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CancelCompleted) GetTargetState() TerminalState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_TargetState
		}
	}
	return TerminalState_TERMINAL_STATE_UNSPECIFIED
}

func (x *CancelCompleted) SetTargetState(v TerminalState) {
	x.xxx_hidden_TargetState = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CancelCompleted) HasTargetState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CancelCompleted) ClearTargetState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TargetState = TerminalState_TERMINAL_STATE_UNSPECIFIED
}

type CancelCompleted_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target operation terminal state.
	TargetState *TerminalState
}

func (b0 CancelCompleted_builder) Build() *CancelCompleted {
	m0 := &CancelCompleted{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TargetState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_TargetState = *b.TargetState
	}
	return m0
}

// CloseConnection requests orderly connection closure.
type CloseConnection struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnection) Reset() {
	*x = CloseConnection{}
	mi := &file_api_operation_v1_operation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnection) ProtoMessage() {}

func (x *CloseConnection) ProtoReflect() protoreflect.Message {
	mi := &file_api_operation_v1_operation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CloseConnection_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CloseConnection_builder) Build() *CloseConnection {
	m0 := &CloseConnection{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_operation_v1_operation_proto protoreflect.FileDescriptor

const file_api_operation_v1_operation_proto_rawDesc = "" +
	"\n" +
	" api/operation/v1/operation.proto\x12\x12glyph.operation.v1\"\n" +
	"\n" +
	"\bAccepted\"\t\n" +
	"\aRunning\"8\n" +
	"\bRejected\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\n" +
	"\n" +
	"\bCanceled\"6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x0fCancelOperation\x12.\n" +
	"\x13target_operation_id\x18\x01 \x01(\tR\x11targetOperationId\"W\n" +
	"\x0fCancelCompleted\x12D\n" +
	"\ftarget_state\x18\x01 \x01(\x0e2!.glyph.operation.v1.TerminalStateR\vtargetState\"\x11\n" +
	"\x0fCloseConnection*\x85\x01\n" +
	"\rTerminalState\x12\x1e\n" +
	"\x1aTERMINAL_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TERMINAL_STATE_COMPLETED\x10\x01\x12\x1b\n" +
	"\x17TERMINAL_STATE_CANCELED\x10\x02\x12\x19\n" +
	"\x15TERMINAL_STATE_FAILED\x10\x03B5Z3github.com/n-r-w/glyph/pkg/operation/v1;operationv1b\beditionsp\xe8\a"

var file_api_operation_v1_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_operation_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_operation_v1_operation_proto_goTypes = []any{
	(TerminalState)(0),      // 0: glyph.operation.v1.TerminalState
	(*Accepted)(nil),        // 1: glyph.operation.v1.Accepted
	(*Running)(nil),         // 2: glyph.operation.v1.Running
	(*Rejected)(nil),        // 3: glyph.operation.v1.Rejected
	(*Canceled)(nil),        // 4: glyph.operation.v1.Canceled
	(*Failed)(nil),          // 5: glyph.operation.v1.Failed
	(*CancelOperation)(nil), // 6: glyph.operation.v1.CancelOperation
	(*CancelCompleted)(nil), // 7: glyph.operation.v1.CancelCompleted
	(*CloseConnection)(nil), // 8: glyph.operation.v1.CloseConnection
}
var file_api_operation_v1_operation_proto_depIdxs = []int32{
	0, // 0: glyph.operation.v1.CancelCompleted.target_state:type_name -> glyph.operation.v1.TerminalState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_operation_v1_operation_proto_init() }
func file_api_operation_v1_operation_proto_init() {
	if File_api_operation_v1_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_operation_v1_operation_proto_rawDesc), len(file_api_operation_v1_operation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_operation_v1_operation_proto_goTypes,
		DependencyIndexes: file_api_operation_v1_operation_proto_depIdxs,
		EnumInfos:         file_api_operation_v1_operation_proto_enumTypes,
		MessageInfos:      file_api_operation_v1_operation_proto_msgTypes,
	}.Build()
	File_api_operation_v1_operation_proto = out.File
	file_api_operation_v1_operation_proto_goTypes = nil
	file_api_operation_v1_operation_proto_depIdxs = nil
}
