// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=bash
//

// Package bash is a generated GoMock package.
package bash

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcessRunner is a mock of ProcessRunner interface.
type MockProcessRunner struct {
	ctrl     *gomock.Controller
	recorder *MockProcessRunnerMockRecorder
	isgomock struct{}
}

// MockProcessRunnerMockRecorder is the mock recorder for MockProcessRunner.
type MockProcessRunnerMockRecorder struct {
	mock *MockProcessRunner
}

// NewMockProcessRunner creates a new mock instance.
func NewMockProcessRunner(ctrl *gomock.Controller) *MockProcessRunner {
	mock := &MockProcessRunner{ctrl: ctrl}
	mock.recorder = &MockProcessRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessRunner) EXPECT() *MockProcessRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockProcessRunner) Run(ctx context.Context, command string, handleProgress ProgressHandler) (ProcessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, command, handleProgress)
	ret0, _ := ret[0].(ProcessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockProcessRunnerMockRecorder) Run(ctx, command, handleProgress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProcessRunner)(nil).Run), ctx, command, handleProgress)
}
