// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=modelselection
//

// Package modelselection is a generated GoMock package.
package modelselection

import (
	context "context"
	reflect "reflect"

	extension "github.com/n-r-w/glyph/host/internal/domain/extension"
	model "github.com/n-r-w/glyph/host/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogFailure is a mock of CatalogFailure interface.
type MockCatalogFailure struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogFailureMockRecorder
	isgomock struct{}
}

// MockCatalogFailureMockRecorder is the mock recorder for MockCatalogFailure.
type MockCatalogFailureMockRecorder struct {
	mock *MockCatalogFailure
}

// NewMockCatalogFailure creates a new mock instance.
func NewMockCatalogFailure(ctrl *gomock.Controller) *MockCatalogFailure {
	mock := &MockCatalogFailure{ctrl: ctrl}
	mock.recorder = &MockCatalogFailureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogFailure) EXPECT() *MockCatalogFailureMockRecorder {
	return m.recorder
}

// CatalogSelectionCode mocks base method.
func (m *MockCatalogFailure) CatalogSelectionCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CatalogSelectionCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// CatalogSelectionCode indicates an expected call of CatalogSelectionCode.
func (mr *MockCatalogFailureMockRecorder) CatalogSelectionCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CatalogSelectionCode", reflect.TypeOf((*MockCatalogFailure)(nil).CatalogSelectionCode))
}

// Error mocks base method.
func (m *MockCatalogFailure) Error() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(string)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockCatalogFailureMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockCatalogFailure)(nil).Error))
}

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// CommitSelection mocks base method.
func (m *MockCatalog) CommitSelection(arg0 context.Context, arg1 model.Selection) (model.Selection, model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitSelection", arg0, arg1)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(model.Selection)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CommitSelection indicates an expected call of CommitSelection.
func (mr *MockCatalogMockRecorder) CommitSelection(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitSelection", reflect.TypeOf((*MockCatalog)(nil).CommitSelection), arg0, arg1)
}

// ResolveModel mocks base method.
func (m *MockCatalog) ResolveModel(arg0 model.ProviderID, arg1 model.ID) (model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveModel", arg0, arg1)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveModel indicates an expected call of ResolveModel.
func (mr *MockCatalogMockRecorder) ResolveModel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveModel", reflect.TypeOf((*MockCatalog)(nil).ResolveModel), arg0, arg1)
}

// ResolveReasoning mocks base method.
func (m *MockCatalog) ResolveReasoning(arg0 model.ReasoningChoice) (model.Selection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReasoning", arg0)
	ret0, _ := ret[0].(model.Selection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveReasoning indicates an expected call of ResolveReasoning.
func (mr *MockCatalogMockRecorder) ResolveReasoning(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReasoning", reflect.TypeOf((*MockCatalog)(nil).ResolveReasoning), arg0)
}

// ValidateSelection mocks base method.
func (m *MockCatalog) ValidateSelection(arg0 context.Context, arg1 model.Selection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSelection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSelection indicates an expected call of ValidateSelection.
func (mr *MockCatalogMockRecorder) ValidateSelection(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSelection", reflect.TypeOf((*MockCatalog)(nil).ValidateSelection), arg0, arg1)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishSelection mocks base method.
func (m *MockPublisher) PublishSelection(arg0 model.Selection) (func(context.Context) error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSelection", arg0)
	ret0, _ := ret[0].(func(context.Context) error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishSelection indicates an expected call of PublishSelection.
func (mr *MockPublisherMockRecorder) PublishSelection(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSelection", reflect.TypeOf((*MockPublisher)(nil).PublishSelection), arg0)
}

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
	isgomock struct{}
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// HandleSelection mocks base method.
func (m *MockRuntime) HandleSelection(arg0 context.Context, arg1, arg2 string, arg3 HandlerInvocation) (HandlerAction, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSelection", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(HandlerAction)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HandleSelection indicates an expected call of HandleSelection.
func (mr *MockRuntimeMockRecorder) HandleSelection(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelection", reflect.TypeOf((*MockRuntime)(nil).HandleSelection), arg0, arg1, arg2, arg3)
}

// HandlerRuntimeAvailable mocks base method.
func (m *MockRuntime) HandlerRuntimeAvailable(extensionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlerRuntimeAvailable", extensionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HandlerRuntimeAvailable indicates an expected call of HandlerRuntimeAvailable.
func (mr *MockRuntimeMockRecorder) HandlerRuntimeAvailable(extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlerRuntimeAvailable", reflect.TypeOf((*MockRuntime)(nil).HandlerRuntimeAvailable), extensionID)
}

// MockContextIssuer is a mock of ContextIssuer interface.
type MockContextIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockContextIssuerMockRecorder
	isgomock struct{}
}

// MockContextIssuerMockRecorder is the mock recorder for MockContextIssuer.
type MockContextIssuerMockRecorder struct {
	mock *MockContextIssuer
}

// NewMockContextIssuer creates a new mock instance.
func NewMockContextIssuer(ctrl *gomock.Controller) *MockContextIssuer {
	mock := &MockContextIssuer{ctrl: ctrl}
	mock.recorder = &MockContextIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextIssuer) EXPECT() *MockContextIssuerMockRecorder {
	return m.recorder
}

// IssueContext mocks base method.
func (m *MockContextIssuer) IssueContext(extensionID string) (extension.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueContext", extensionID)
	ret0, _ := ret[0].(extension.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueContext indicates an expected call of IssueContext.
func (mr *MockContextIssuerMockRecorder) IssueContext(extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueContext", reflect.TypeOf((*MockContextIssuer)(nil).IssueContext), extensionID)
}

// MockIssueDelivery is a mock of IssueDelivery interface.
type MockIssueDelivery struct {
	ctrl     *gomock.Controller
	recorder *MockIssueDeliveryMockRecorder
	isgomock struct{}
}

// MockIssueDeliveryMockRecorder is the mock recorder for MockIssueDelivery.
type MockIssueDeliveryMockRecorder struct {
	mock *MockIssueDelivery
}

// NewMockIssueDelivery creates a new mock instance.
func NewMockIssueDelivery(ctrl *gomock.Controller) *MockIssueDelivery {
	mock := &MockIssueDelivery{ctrl: ctrl}
	mock.recorder = &MockIssueDeliveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueDelivery) EXPECT() *MockIssueDeliveryMockRecorder {
	return m.recorder
}

// DeliverSelectionIssue mocks base method.
func (m *MockIssueDelivery) DeliverSelectionIssue(arg0 context.Context, arg1 Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverSelectionIssue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeliverSelectionIssue indicates an expected call of DeliverSelectionIssue.
func (mr *MockIssueDeliveryMockRecorder) DeliverSelectionIssue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverSelectionIssue", reflect.TypeOf((*MockIssueDelivery)(nil).DeliverSelectionIssue), arg0, arg1)
}
