// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=codex
//

// Package codex is a generated GoMock package.
package codex

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCredentials is a mock of Credentials interface.
type MockCredentials struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsMockRecorder
	isgomock struct{}
}

// MockCredentialsMockRecorder is the mock recorder for MockCredentials.
type MockCredentialsMockRecorder struct {
	mock *MockCredentials
}

// NewMockCredentials creates a new mock instance.
func NewMockCredentials(ctrl *gomock.Controller) *MockCredentials {
	mock := &MockCredentials{ctrl: ctrl}
	mock.recorder = &MockCredentialsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentials) EXPECT() *MockCredentialsMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCredentials) Delete() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete")
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCredentialsMockRecorder) Delete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCredentials)(nil).Delete))
}

// Load mocks base method.
func (m *MockCredentials) Load() ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Load indicates an expected call of Load.
func (mr *MockCredentialsMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCredentials)(nil).Load))
}

// Save mocks base method.
func (m *MockCredentials) Save(payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCredentialsMockRecorder) Save(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCredentials)(nil).Save), payload)
}

// MockInteraction is a mock of Interaction interface.
type MockInteraction struct {
	ctrl     *gomock.Controller
	recorder *MockInteractionMockRecorder
	isgomock struct{}
}

// MockInteractionMockRecorder is the mock recorder for MockInteraction.
type MockInteractionMockRecorder struct {
	mock *MockInteraction
}

// NewMockInteraction creates a new mock instance.
func NewMockInteraction(ctrl *gomock.Controller) *MockInteraction {
	mock := &MockInteraction{ctrl: ctrl}
	mock.recorder = &MockInteractionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteraction) EXPECT() *MockInteractionMockRecorder {
	return m.recorder
}

// OpenBrowser mocks base method.
func (m *MockInteraction) OpenBrowser(ctx context.Context, authorizationURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenBrowser", ctx, authorizationURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenBrowser indicates an expected call of OpenBrowser.
func (mr *MockInteractionMockRecorder) OpenBrowser(ctx, authorizationURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenBrowser", reflect.TypeOf((*MockInteraction)(nil).OpenBrowser), ctx, authorizationURL)
}

// PresentAuthorizationURL mocks base method.
func (m *MockInteraction) PresentAuthorizationURL(ctx context.Context, authorizationURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentAuthorizationURL", ctx, authorizationURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// PresentAuthorizationURL indicates an expected call of PresentAuthorizationURL.
func (mr *MockInteractionMockRecorder) PresentAuthorizationURL(ctx, authorizationURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentAuthorizationURL", reflect.TypeOf((*MockInteraction)(nil).PresentAuthorizationURL), ctx, authorizationURL)
}
