// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: api/plugins/ui/v1/agent.proto

package uiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Availability identifies whether the Host can accept a user request.
type Availability int32

const (
	// No Host availability was provided.
	Availability_AVAILABILITY_UNSPECIFIED Availability = 0
	// The Host is checking stored authentication.
	Availability_AVAILABILITY_CHECKING_AUTHENTICATION Availability = 1
	// The Host is waiting for authentication.
	Availability_AVAILABILITY_AUTHENTICATING Availability = 2
	// Authentication failed and can be retried.
	Availability_AVAILABILITY_AUTHENTICATION_FAILED Availability = 3
	// The Host can accept a user request.
	Availability_AVAILABILITY_IDLE Availability = 4
	// The Host is processing an agent run.
	Availability_AVAILABILITY_RUNNING Availability = 5
)

// Enum value maps for Availability.
var (
	Availability_name = map[int32]string{
		0: "AVAILABILITY_UNSPECIFIED",
		1: "AVAILABILITY_CHECKING_AUTHENTICATION",
		2: "AVAILABILITY_AUTHENTICATING",
		3: "AVAILABILITY_AUTHENTICATION_FAILED",
		4: "AVAILABILITY_IDLE",
		5: "AVAILABILITY_RUNNING",
	}
	Availability_value = map[string]int32{
		"AVAILABILITY_UNSPECIFIED":             0,
		"AVAILABILITY_CHECKING_AUTHENTICATION": 1,
		"AVAILABILITY_AUTHENTICATING":          2,
		"AVAILABILITY_AUTHENTICATION_FAILED":   3,
		"AVAILABILITY_IDLE":                    4,
		"AVAILABILITY_RUNNING":                 5,
	}
)

func (x Availability) Enum() *Availability {
	p := new(Availability)
	*p = x
	return p
}

func (x Availability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Availability) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugins_ui_v1_agent_proto_enumTypes[0].Descriptor()
}

func (Availability) Type() protoreflect.EnumType {
	return &file_api_plugins_ui_v1_agent_proto_enumTypes[0]
}

func (x Availability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ModelContentKind identifies visible text, refusal, or hidden reasoning content.
type ModelContentKind int32

const (
	// No content kind was provided.
	ModelContentKind_MODEL_CONTENT_KIND_UNSPECIFIED ModelContentKind = 0
	// The content is public response text.
	ModelContentKind_MODEL_CONTENT_KIND_TEXT ModelContentKind = 1
	// The content is hidden model reasoning.
	ModelContentKind_MODEL_CONTENT_KIND_REASONING ModelContentKind = 2
	// The content is a model refusal.
	ModelContentKind_MODEL_CONTENT_KIND_REFUSAL ModelContentKind = 3
)

// Enum value maps for ModelContentKind.
var (
	ModelContentKind_name = map[int32]string{
		0: "MODEL_CONTENT_KIND_UNSPECIFIED",
		1: "MODEL_CONTENT_KIND_TEXT",
		2: "MODEL_CONTENT_KIND_REASONING",
		3: "MODEL_CONTENT_KIND_REFUSAL",
	}
	ModelContentKind_value = map[string]int32{
		"MODEL_CONTENT_KIND_UNSPECIFIED": 0,
		"MODEL_CONTENT_KIND_TEXT":        1,
		"MODEL_CONTENT_KIND_REASONING":   2,
		"MODEL_CONTENT_KIND_REFUSAL":     3,
	}
)

func (x ModelContentKind) Enum() *ModelContentKind {
	p := new(ModelContentKind)
	*p = x
	return p
}

func (x ModelContentKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelContentKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugins_ui_v1_agent_proto_enumTypes[1].Descriptor()
}

func (ModelContentKind) Type() protoreflect.EnumType {
	return &file_api_plugins_ui_v1_agent_proto_enumTypes[1]
}

func (x ModelContentKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ModelContentType identifies one content transition.
type ModelContentType int32

const (
	// No model content transition was provided.
	ModelContentType_MODEL_CONTENT_TYPE_UNSPECIFIED ModelContentType = 0
	// A model content block started.
	ModelContentType_MODEL_CONTENT_TYPE_START ModelContentType = 1
	// A text delta was appended to a content block.
	ModelContentType_MODEL_CONTENT_TYPE_TEXT_DELTA ModelContentType = 2
	// A model content block ended.
	ModelContentType_MODEL_CONTENT_TYPE_END ModelContentType = 3
)

// Enum value maps for ModelContentType.
var (
	ModelContentType_name = map[int32]string{
		0: "MODEL_CONTENT_TYPE_UNSPECIFIED",
		1: "MODEL_CONTENT_TYPE_START",
		2: "MODEL_CONTENT_TYPE_TEXT_DELTA",
		3: "MODEL_CONTENT_TYPE_END",
	}
	ModelContentType_value = map[string]int32{
		"MODEL_CONTENT_TYPE_UNSPECIFIED": 0,
		"MODEL_CONTENT_TYPE_START":       1,
		"MODEL_CONTENT_TYPE_TEXT_DELTA":  2,
		"MODEL_CONTENT_TYPE_END":         3,
	}
)

func (x ModelContentType) Enum() *ModelContentType {
	p := new(ModelContentType)
	*p = x
	return p
}

func (x ModelContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugins_ui_v1_agent_proto_enumTypes[2].Descriptor()
}

func (ModelContentType) Type() protoreflect.EnumType {
	return &file_api_plugins_ui_v1_agent_proto_enumTypes[2]
}

func (x ModelContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// LifecycleType identifies the ordered Host or Agent lifecycle transition.
type LifecycleType int32

const (
	// No lifecycle transition was provided.
	LifecycleType_LIFECYCLE_TYPE_UNSPECIFIED LifecycleType = 0
	// The agent run started.
	LifecycleType_LIFECYCLE_TYPE_AGENT_START LifecycleType = 1
	// An agent turn started.
	LifecycleType_LIFECYCLE_TYPE_TURN_START LifecycleType = 2
	// A model response message started.
	LifecycleType_LIFECYCLE_TYPE_MESSAGE_START LifecycleType = 3
	// A model response message ended.
	LifecycleType_LIFECYCLE_TYPE_MESSAGE_END LifecycleType = 4
	// Tool execution started.
	LifecycleType_LIFECYCLE_TYPE_TOOL_EXECUTION_START LifecycleType = 5
	// Tool execution emitted progress.
	LifecycleType_LIFECYCLE_TYPE_TOOL_EXECUTION_UPDATE LifecycleType = 6
	// Tool execution ended.
	LifecycleType_LIFECYCLE_TYPE_TOOL_EXECUTION_END LifecycleType = 7
	// A terminal tool result became available.
	LifecycleType_LIFECYCLE_TYPE_TOOL_RESULT LifecycleType = 8
	// The current agent turn ended.
	LifecycleType_LIFECYCLE_TYPE_TURN_END LifecycleType = 9
	// The agent run ended.
	LifecycleType_LIFECYCLE_TYPE_AGENT_END LifecycleType = 10
	// A typed model content block started.
	LifecycleType_LIFECYCLE_TYPE_MODEL_CONTENT_START LifecycleType = 11
	// A typed model text delta arrived.
	LifecycleType_LIFECYCLE_TYPE_MODEL_TEXT_DELTA LifecycleType = 12
	// A typed model content block ended.
	LifecycleType_LIFECYCLE_TYPE_MODEL_CONTENT_END LifecycleType = 13
	// Incremental tool call generation started.
	LifecycleType_LIFECYCLE_TYPE_TOOL_CALL_START LifecycleType = 14
	// Incremental tool call state changed.
	LifecycleType_LIFECYCLE_TYPE_TOOL_CALL_DELTA LifecycleType = 15
	// Tool call generation ended.
	LifecycleType_LIFECYCLE_TYPE_TOOL_CALL_END LifecycleType = 16
)

// Enum value maps for LifecycleType.
var (
	LifecycleType_name = map[int32]string{
		0:  "LIFECYCLE_TYPE_UNSPECIFIED",
		1:  "LIFECYCLE_TYPE_AGENT_START",
		2:  "LIFECYCLE_TYPE_TURN_START",
		3:  "LIFECYCLE_TYPE_MESSAGE_START",
		4:  "LIFECYCLE_TYPE_MESSAGE_END",
		5:  "LIFECYCLE_TYPE_TOOL_EXECUTION_START",
		6:  "LIFECYCLE_TYPE_TOOL_EXECUTION_UPDATE",
		7:  "LIFECYCLE_TYPE_TOOL_EXECUTION_END",
		8:  "LIFECYCLE_TYPE_TOOL_RESULT",
		9:  "LIFECYCLE_TYPE_TURN_END",
		10: "LIFECYCLE_TYPE_AGENT_END",
		11: "LIFECYCLE_TYPE_MODEL_CONTENT_START",
		12: "LIFECYCLE_TYPE_MODEL_TEXT_DELTA",
		13: "LIFECYCLE_TYPE_MODEL_CONTENT_END",
		14: "LIFECYCLE_TYPE_TOOL_CALL_START",
		15: "LIFECYCLE_TYPE_TOOL_CALL_DELTA",
		16: "LIFECYCLE_TYPE_TOOL_CALL_END",
	}
	LifecycleType_value = map[string]int32{
		"LIFECYCLE_TYPE_UNSPECIFIED":           0,
		"LIFECYCLE_TYPE_AGENT_START":           1,
		"LIFECYCLE_TYPE_TURN_START":            2,
		"LIFECYCLE_TYPE_MESSAGE_START":         3,
		"LIFECYCLE_TYPE_MESSAGE_END":           4,
		"LIFECYCLE_TYPE_TOOL_EXECUTION_START":  5,
		"LIFECYCLE_TYPE_TOOL_EXECUTION_UPDATE": 6,
		"LIFECYCLE_TYPE_TOOL_EXECUTION_END":    7,
		"LIFECYCLE_TYPE_TOOL_RESULT":           8,
		"LIFECYCLE_TYPE_TURN_END":              9,
		"LIFECYCLE_TYPE_AGENT_END":             10,
		"LIFECYCLE_TYPE_MODEL_CONTENT_START":   11,
		"LIFECYCLE_TYPE_MODEL_TEXT_DELTA":      12,
		"LIFECYCLE_TYPE_MODEL_CONTENT_END":     13,
		"LIFECYCLE_TYPE_TOOL_CALL_START":       14,
		"LIFECYCLE_TYPE_TOOL_CALL_DELTA":       15,
		"LIFECYCLE_TYPE_TOOL_CALL_END":         16,
	}
)

func (x LifecycleType) Enum() *LifecycleType {
	p := new(LifecycleType)
	*p = x
	return p
}

func (x LifecycleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugins_ui_v1_agent_proto_enumTypes[3].Descriptor()
}

func (LifecycleType) Type() protoreflect.EnumType {
	return &file_api_plugins_ui_v1_agent_proto_enumTypes[3]
}

func (x LifecycleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ProgressChannel identifies the meaning of one tool progress fragment.
type ProgressChannel int32

const (
	// No progress channel was provided.
	ProgressChannel_PROGRESS_CHANNEL_UNSPECIFIED ProgressChannel = 0
	// The fragment reports status information.
	ProgressChannel_PROGRESS_CHANNEL_STATUS ProgressChannel = 1
	// The fragment contains standard output.
	ProgressChannel_PROGRESS_CHANNEL_STDOUT ProgressChannel = 2
	// The fragment contains standard error.
	ProgressChannel_PROGRESS_CHANNEL_STDERR ProgressChannel = 3
)

// Enum value maps for ProgressChannel.
var (
	ProgressChannel_name = map[int32]string{
		0: "PROGRESS_CHANNEL_UNSPECIFIED",
		1: "PROGRESS_CHANNEL_STATUS",
		2: "PROGRESS_CHANNEL_STDOUT",
		3: "PROGRESS_CHANNEL_STDERR",
	}
	ProgressChannel_value = map[string]int32{
		"PROGRESS_CHANNEL_UNSPECIFIED": 0,
		"PROGRESS_CHANNEL_STATUS":      1,
		"PROGRESS_CHANNEL_STDOUT":      2,
		"PROGRESS_CHANNEL_STDERR":      3,
	}
)

func (x ProgressChannel) Enum() *ProgressChannel {
	p := new(ProgressChannel)
	*p = x
	return p
}

func (x ProgressChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugins_ui_v1_agent_proto_enumTypes[4].Descriptor()
}

func (ProgressChannel) Type() protoreflect.EnumType {
	return &file_api_plugins_ui_v1_agent_proto_enumTypes[4]
}

func (x ProgressChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ExtensionAvailability describes one available extension, its executable path, and its tool names.
type ExtensionAvailability struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PluginId    *string                `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId"`
	xxx_hidden_Tools       []string               `protobuf:"bytes,2,rep,name=tools"`
	xxx_hidden_Path        *string                `protobuf:"bytes,3,opt,name=path"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExtensionAvailability) Reset() {
	*x = ExtensionAvailability{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionAvailability) ProtoMessage() {}

func (x *ExtensionAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExtensionAvailability) GetPluginId() string {
	if x != nil {
		if x.xxx_hidden_PluginId != nil {
			return *x.xxx_hidden_PluginId
		}
		return ""
	}
	return ""
}

func (x *ExtensionAvailability) GetTools() []string {
	if x != nil {
		return x.xxx_hidden_Tools
	}
	return nil
}

func (x *ExtensionAvailability) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *ExtensionAvailability) SetPluginId(v string) {
	x.xxx_hidden_PluginId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ExtensionAvailability) SetTools(v []string) {
	x.xxx_hidden_Tools = v
}

func (x *ExtensionAvailability) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ExtensionAvailability) HasPluginId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ExtensionAvailability) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ExtensionAvailability) ClearPluginId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PluginId = nil
}

func (x *ExtensionAvailability) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Path = nil
}

type ExtensionAvailability_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The configured extension plugin identifier.
	PluginId *string
	// The tool names exposed by the extension.
	Tools []string
	// The resolved extension executable path.
	Path *string
}

func (b0 ExtensionAvailability_builder) Build() *ExtensionAvailability {
	m0 := &ExtensionAvailability{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PluginId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_PluginId = b.PluginId
	}
	x.xxx_hidden_Tools = b.Tools
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Path = b.Path
	}
	return m0
}

// LifecycleEvent carries one explicit provider-neutral lifecycle update.
type AgentEvent struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type               LifecycleType          `protobuf:"varint,1,opt,name=type,enum=glyph.plugins.ui.v1.LifecycleType"`
	xxx_hidden_RunId              *string                `protobuf:"bytes,2,opt,name=run_id,json=runId"`
	xxx_hidden_Text               *string                `protobuf:"bytes,3,opt,name=text"`
	xxx_hidden_ToolCallId         *string                `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId"`
	xxx_hidden_ToolName           *string                `protobuf:"bytes,5,opt,name=tool_name,json=toolName"`
	xxx_hidden_ProgressChannel    ProgressChannel        `protobuf:"varint,6,opt,name=progress_channel,json=progressChannel,enum=glyph.plugins.ui.v1.ProgressChannel"`
	xxx_hidden_IsError            bool                   `protobuf:"varint,7,opt,name=is_error,json=isError"`
	xxx_hidden_Outcome            *string                `protobuf:"bytes,8,opt,name=outcome"`
	xxx_hidden_ErrorMessage       *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage"`
	xxx_hidden_Availability       Availability           `protobuf:"varint,10,opt,name=availability,enum=glyph.plugins.ui.v1.Availability"`
	xxx_hidden_ModelContent       *ModelContent          `protobuf:"bytes,11,opt,name=model_content,json=modelContent"`
	xxx_hidden_ModelResponse      *ModelResponse         `protobuf:"bytes,12,opt,name=model_response,json=modelResponse"`
	xxx_hidden_ToolCallPreview    *ToolCallPreview       `protobuf:"bytes,13,opt,name=tool_call_preview,json=toolCallPreview"`
	xxx_hidden_FinalToolCall      *FinalToolCall         `protobuf:"bytes,14,opt,name=final_tool_call,json=finalToolCall"`
	xxx_hidden_ToolResultContents *[]*ToolResultContent  `protobuf:"bytes,15,rep,name=tool_result_contents,json=toolResultContents"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentEvent) GetType() LifecycleType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return LifecycleType_LIFECYCLE_TYPE_UNSPECIFIED
}

func (x *AgentEvent) GetRunId() string {
	if x != nil {
		if x.xxx_hidden_RunId != nil {
			return *x.xxx_hidden_RunId
		}
		return ""
	}
	return ""
}

func (x *AgentEvent) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *AgentEvent) GetToolCallId() string {
	if x != nil {
		if x.xxx_hidden_ToolCallId != nil {
			return *x.xxx_hidden_ToolCallId
		}
		return ""
	}
	return ""
}

func (x *AgentEvent) GetToolName() string {
	if x != nil {
		if x.xxx_hidden_ToolName != nil {
			return *x.xxx_hidden_ToolName
		}
		return ""
	}
	return ""
}

func (x *AgentEvent) GetProgressChannel() ProgressChannel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_ProgressChannel
		}
	}
	return ProgressChannel_PROGRESS_CHANNEL_UNSPECIFIED
}

func (x *AgentEvent) GetIsError() bool {
	if x != nil {
		return x.xxx_hidden_IsError
	}
	return false
}

func (x *AgentEvent) GetOutcome() string {
	if x != nil {
		if x.xxx_hidden_Outcome != nil {
			return *x.xxx_hidden_Outcome
		}
		return ""
	}
	return ""
}

func (x *AgentEvent) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *AgentEvent) GetAvailability() Availability {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 9) {
			return x.xxx_hidden_Availability
		}
	}
	return Availability_AVAILABILITY_UNSPECIFIED
}

func (x *AgentEvent) GetModelContent() *ModelContent {
	if x != nil {
		return x.xxx_hidden_ModelContent
	}
	return nil
}

func (x *AgentEvent) GetModelResponse() *ModelResponse {
	if x != nil {
		return x.xxx_hidden_ModelResponse
	}
	return nil
}

func (x *AgentEvent) GetToolCallPreview() *ToolCallPreview {
	if x != nil {
		return x.xxx_hidden_ToolCallPreview
	}
	return nil
}

func (x *AgentEvent) GetFinalToolCall() *FinalToolCall {
	if x != nil {
		return x.xxx_hidden_FinalToolCall
	}
	return nil
}

func (x *AgentEvent) GetToolResultContents() []*ToolResultContent {
	if x != nil {
		if x.xxx_hidden_ToolResultContents != nil {
			return *x.xxx_hidden_ToolResultContents
		}
	}
	return nil
}

func (x *AgentEvent) SetType(v LifecycleType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 15)
}

func (x *AgentEvent) SetRunId(v string) {
	x.xxx_hidden_RunId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 15)
}

func (x *AgentEvent) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 15)
}

func (x *AgentEvent) SetToolCallId(v string) {
	x.xxx_hidden_ToolCallId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 15)
}

func (x *AgentEvent) SetToolName(v string) {
	x.xxx_hidden_ToolName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 15)
}

func (x *AgentEvent) SetProgressChannel(v ProgressChannel) {
	x.xxx_hidden_ProgressChannel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 15)
}

func (x *AgentEvent) SetIsError(v bool) {
	x.xxx_hidden_IsError = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 15)
}

func (x *AgentEvent) SetOutcome(v string) {
	x.xxx_hidden_Outcome = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 15)
}

func (x *AgentEvent) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 15)
}

func (x *AgentEvent) SetAvailability(v Availability) {
	x.xxx_hidden_Availability = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 15)
}

func (x *AgentEvent) SetModelContent(v *ModelContent) {
	x.xxx_hidden_ModelContent = v
}

func (x *AgentEvent) SetModelResponse(v *ModelResponse) {
	x.xxx_hidden_ModelResponse = v
}

func (x *AgentEvent) SetToolCallPreview(v *ToolCallPreview) {
	x.xxx_hidden_ToolCallPreview = v
}

func (x *AgentEvent) SetFinalToolCall(v *FinalToolCall) {
	x.xxx_hidden_FinalToolCall = v
}

func (x *AgentEvent) SetToolResultContents(v []*ToolResultContent) {
	x.xxx_hidden_ToolResultContents = &v
}

func (x *AgentEvent) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentEvent) HasRunId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentEvent) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AgentEvent) HasToolCallId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AgentEvent) HasToolName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AgentEvent) HasProgressChannel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AgentEvent) HasIsError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AgentEvent) HasOutcome() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AgentEvent) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AgentEvent) HasAvailability() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *AgentEvent) HasModelContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ModelContent != nil
}

func (x *AgentEvent) HasModelResponse() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ModelResponse != nil
}

func (x *AgentEvent) HasToolCallPreview() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ToolCallPreview != nil
}

func (x *AgentEvent) HasFinalToolCall() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FinalToolCall != nil
}

func (x *AgentEvent) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = LifecycleType_LIFECYCLE_TYPE_UNSPECIFIED
}

func (x *AgentEvent) ClearRunId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RunId = nil
}

func (x *AgentEvent) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Text = nil
}

func (x *AgentEvent) ClearToolCallId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ToolCallId = nil
}

func (x *AgentEvent) ClearToolName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ToolName = nil
}

func (x *AgentEvent) ClearProgressChannel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ProgressChannel = ProgressChannel_PROGRESS_CHANNEL_UNSPECIFIED
}

func (x *AgentEvent) ClearIsError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_IsError = false
}

func (x *AgentEvent) ClearOutcome() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Outcome = nil
}

func (x *AgentEvent) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *AgentEvent) ClearAvailability() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Availability = Availability_AVAILABILITY_UNSPECIFIED
}

func (x *AgentEvent) ClearModelContent() {
	x.xxx_hidden_ModelContent = nil
}

func (x *AgentEvent) ClearModelResponse() {
	x.xxx_hidden_ModelResponse = nil
}

func (x *AgentEvent) ClearToolCallPreview() {
	x.xxx_hidden_ToolCallPreview = nil
}

func (x *AgentEvent) ClearFinalToolCall() {
	x.xxx_hidden_FinalToolCall = nil
}

type AgentEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The lifecycle transition represented by this event.
	Type *LifecycleType
	// The identifier of the associated agent run.
	RunId *string
	// The user-visible text carried by the transition.
	Text *string
	// The provider-assigned tool call identifier.
	ToolCallId *string
	// The name of the associated tool.
	ToolName *string
	// The semantic channel of a tool progress update.
	ProgressChannel *ProgressChannel
	// Whether the associated operation failed.
	IsError *bool
	// The provider-neutral terminal outcome.
	Outcome *string
	// The safe user-visible error message.
	ErrorMessage *string
	// The Host availability after this transition.
	Availability *Availability
	// The typed incremental model content transition.
	ModelContent *ModelContent
	// The finalized model response.
	ModelResponse *ModelResponse
	// The transient tool call state assembled from deltas.
	ToolCallPreview *ToolCallPreview
	// The finalized tool call and decoded arguments.
	FinalToolCall *FinalToolCall
	// The ordered typed terminal tool result blocks.
	ToolResultContents []*ToolResultContent
}

func (b0 AgentEvent_builder) Build() *AgentEvent {
	m0 := &AgentEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 15)
		x.xxx_hidden_Type = *b.Type
	}
	if b.RunId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 15)
		x.xxx_hidden_RunId = b.RunId
	}
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 15)
		x.xxx_hidden_Text = b.Text
	}
	if b.ToolCallId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 15)
		x.xxx_hidden_ToolCallId = b.ToolCallId
	}
	if b.ToolName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 15)
		x.xxx_hidden_ToolName = b.ToolName
	}
	if b.ProgressChannel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 15)
		x.xxx_hidden_ProgressChannel = *b.ProgressChannel
	}
	if b.IsError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 15)
		x.xxx_hidden_IsError = *b.IsError
	}
	if b.Outcome != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 15)
		x.xxx_hidden_Outcome = b.Outcome
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 15)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	if b.Availability != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 15)
		x.xxx_hidden_Availability = *b.Availability
	}
	x.xxx_hidden_ModelContent = b.ModelContent
	x.xxx_hidden_ModelResponse = b.ModelResponse
	x.xxx_hidden_ToolCallPreview = b.ToolCallPreview
	x.xxx_hidden_FinalToolCall = b.FinalToolCall
	x.xxx_hidden_ToolResultContents = &b.ToolResultContents
	return m0
}

// ToolResultContent carries one ordered terminal tool result block.
type ToolResultContent struct {
	state              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Content isToolResultContent_Content `protobuf_oneof:"content"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ToolResultContent) Reset() {
	*x = ToolResultContent{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultContent) ProtoMessage() {}

func (x *ToolResultContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolResultContent) GetText() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*toolResultContent_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ToolResultContent) GetImage() *ToolResultImage {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*toolResultContent_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ToolResultContent) SetText(v string) {
	x.xxx_hidden_Content = &toolResultContent_Text{v}
}

func (x *ToolResultContent) SetImage(v *ToolResultImage) {
	if v == nil {
		x.xxx_hidden_Content = nil
		return
	}
	x.xxx_hidden_Content = &toolResultContent_Image{v}
}

func (x *ToolResultContent) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *ToolResultContent) HasText() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*toolResultContent_Text)
	return ok
}

func (x *ToolResultContent) HasImage() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*toolResultContent_Image)
	return ok
}

func (x *ToolResultContent) ClearContent() {
	x.xxx_hidden_Content = nil
}

func (x *ToolResultContent) ClearText() {
	if _, ok := x.xxx_hidden_Content.(*toolResultContent_Text); ok {
		x.xxx_hidden_Content = nil
	}
}

func (x *ToolResultContent) ClearImage() {
	if _, ok := x.xxx_hidden_Content.(*toolResultContent_Image); ok {
		x.xxx_hidden_Content = nil
	}
}

const ToolResultContent_Content_not_set_case case_ToolResultContent_Content = 0
const ToolResultContent_Text_case case_ToolResultContent_Content = 1
const ToolResultContent_Image_case case_ToolResultContent_Content = 2

func (x *ToolResultContent) WhichContent() case_ToolResultContent_Content {
	if x == nil {
		return ToolResultContent_Content_not_set_case
	}
	switch x.xxx_hidden_Content.(type) {
	case *toolResultContent_Text:
		return ToolResultContent_Text_case
	case *toolResultContent_Image:
		return ToolResultContent_Image_case
	default:
		return ToolResultContent_Content_not_set_case
	}
}

type ToolResultContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The result content payload.

	// Fields of oneof xxx_hidden_Content:
	// The UTF-8 text payload.
	Text *string
	// The binary image payload.
	Image *ToolResultImage
	// -- end of xxx_hidden_Content
}

func (b0 ToolResultContent_builder) Build() *ToolResultContent {
	m0 := &ToolResultContent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		x.xxx_hidden_Content = &toolResultContent_Text{*b.Text}
	}
	if b.Image != nil {
		x.xxx_hidden_Content = &toolResultContent_Image{b.Image}
	}
	return m0
}

type case_ToolResultContent_Content protoreflect.FieldNumber

func (x case_ToolResultContent_Content) String() string {
	md := file_api_plugins_ui_v1_agent_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isToolResultContent_Content interface {
	isToolResultContent_Content()
}

type toolResultContent_Text struct {
	// The UTF-8 text payload.
	Text string `protobuf:"bytes,1,opt,name=text,oneof"`
}

type toolResultContent_Image struct {
	// The binary image payload.
	Image *ToolResultImage `protobuf:"bytes,2,opt,name=image,oneof"`
}

func (*toolResultContent_Text) isToolResultContent_Content() {}

func (*toolResultContent_Image) isToolResultContent_Content() {}

// ToolResultImage carries binary image data and its media type.
type ToolResultImage struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MediaType   *string                `protobuf:"bytes,1,opt,name=media_type,json=mediaType"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolResultImage) Reset() {
	*x = ToolResultImage{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultImage) ProtoMessage() {}

func (x *ToolResultImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolResultImage) GetMediaType() string {
	if x != nil {
		if x.xxx_hidden_MediaType != nil {
			return *x.xxx_hidden_MediaType
		}
		return ""
	}
	return ""
}

func (x *ToolResultImage) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ToolResultImage) SetMediaType(v string) {
	x.xxx_hidden_MediaType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ToolResultImage) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ToolResultImage) HasMediaType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolResultImage) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ToolResultImage) ClearMediaType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MediaType = nil
}

func (x *ToolResultImage) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type ToolResultImage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The image media type.
	MediaType *string
	// The binary image data.
	Data []byte
}

func (b0 ToolResultImage_builder) Build() *ToolResultImage {
	m0 := &ToolResultImage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MediaType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_MediaType = b.MediaType
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

// ToolCallPreview carries transient provenance-aware function-call state.
type ToolCallPreview struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_CallId      *string                  `protobuf:"bytes,1,opt,name=call_id,json=callId"`
	xxx_hidden_Name        *string                  `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Position    int64                    `protobuf:"varint,3,opt,name=position"`
	xxx_hidden_Provisional bool                     `protobuf:"varint,4,opt,name=provisional"`
	xxx_hidden_Fields      *[]*ToolCallPreviewField `protobuf:"bytes,5,rep,name=fields"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolCallPreview) Reset() {
	*x = ToolCallPreview{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallPreview) ProtoMessage() {}

func (x *ToolCallPreview) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolCallPreview) GetCallId() string {
	if x != nil {
		if x.xxx_hidden_CallId != nil {
			return *x.xxx_hidden_CallId
		}
		return ""
	}
	return ""
}

func (x *ToolCallPreview) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ToolCallPreview) GetPosition() int64 {
	if x != nil {
		return x.xxx_hidden_Position
	}
	return 0
}

func (x *ToolCallPreview) GetProvisional() bool {
	if x != nil {
		return x.xxx_hidden_Provisional
	}
	return false
}

func (x *ToolCallPreview) GetFields() []*ToolCallPreviewField {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *ToolCallPreview) SetCallId(v string) {
	x.xxx_hidden_CallId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ToolCallPreview) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ToolCallPreview) SetPosition(v int64) {
	x.xxx_hidden_Position = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ToolCallPreview) SetProvisional(v bool) {
	x.xxx_hidden_Provisional = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ToolCallPreview) SetFields(v []*ToolCallPreviewField) {
	x.xxx_hidden_Fields = &v
}

func (x *ToolCallPreview) HasCallId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolCallPreview) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ToolCallPreview) HasPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ToolCallPreview) HasProvisional() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ToolCallPreview) ClearCallId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CallId = nil
}

func (x *ToolCallPreview) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *ToolCallPreview) ClearPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Position = 0
}

func (x *ToolCallPreview) ClearProvisional() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Provisional = false
}

type ToolCallPreview_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The provider-assigned tool call identifier.
	CallId *string
	// The current tool name.
	Name *string
	// The zero-based position in the model response.
	Position *int64
	// Whether the preview can still change.
	Provisional *bool
	// The currently decoded argument fields.
	Fields []*ToolCallPreviewField
}

func (b0 ToolCallPreview_builder) Build() *ToolCallPreview {
	m0 := &ToolCallPreview{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CallId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_CallId = b.CallId
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Position != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Position = *b.Position
	}
	if b.Provisional != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Provisional = *b.Provisional
	}
	x.xxx_hidden_Fields = &b.Fields
	return m0
}

// ToolCallPreviewField carries either one complete value or one exact scalar prefix.
type ToolCallPreviewField struct {
	state                  protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                        `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Content     isToolCallPreviewField_Content `protobuf_oneof:"content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolCallPreviewField) Reset() {
	*x = ToolCallPreviewField{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallPreviewField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallPreviewField) ProtoMessage() {}

func (x *ToolCallPreviewField) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolCallPreviewField) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ToolCallPreviewField) GetValue() *structpb.Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*toolCallPreviewField_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *ToolCallPreviewField) GetPrefix() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Content.(*toolCallPreviewField_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *ToolCallPreviewField) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ToolCallPreviewField) SetValue(v *structpb.Value) {
	if v == nil {
		x.xxx_hidden_Content = nil
		return
	}
	x.xxx_hidden_Content = &toolCallPreviewField_Value{v}
}

func (x *ToolCallPreviewField) SetPrefix(v string) {
	x.xxx_hidden_Content = &toolCallPreviewField_Prefix{v}
}

func (x *ToolCallPreviewField) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolCallPreviewField) HasContent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Content != nil
}

func (x *ToolCallPreviewField) HasValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*toolCallPreviewField_Value)
	return ok
}

func (x *ToolCallPreviewField) HasPrefix() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Content.(*toolCallPreviewField_Prefix)
	return ok
}

func (x *ToolCallPreviewField) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ToolCallPreviewField) ClearContent() {
	x.xxx_hidden_Content = nil
}

func (x *ToolCallPreviewField) ClearValue() {
	if _, ok := x.xxx_hidden_Content.(*toolCallPreviewField_Value); ok {
		x.xxx_hidden_Content = nil
	}
}

func (x *ToolCallPreviewField) ClearPrefix() {
	if _, ok := x.xxx_hidden_Content.(*toolCallPreviewField_Prefix); ok {
		x.xxx_hidden_Content = nil
	}
}

const ToolCallPreviewField_Content_not_set_case case_ToolCallPreviewField_Content = 0
const ToolCallPreviewField_Value_case case_ToolCallPreviewField_Content = 2
const ToolCallPreviewField_Prefix_case case_ToolCallPreviewField_Content = 3

func (x *ToolCallPreviewField) WhichContent() case_ToolCallPreviewField_Content {
	if x == nil {
		return ToolCallPreviewField_Content_not_set_case
	}
	switch x.xxx_hidden_Content.(type) {
	case *toolCallPreviewField_Value:
		return ToolCallPreviewField_Value_case
	case *toolCallPreviewField_Prefix:
		return ToolCallPreviewField_Prefix_case
	default:
		return ToolCallPreviewField_Content_not_set_case
	}
}

type ToolCallPreviewField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The argument field name.
	Name *string
	// The complete value or exact scalar prefix.

	// Fields of oneof xxx_hidden_Content:
	Value  *structpb.Value
	Prefix *string
	// -- end of xxx_hidden_Content
}

func (b0 ToolCallPreviewField_builder) Build() *ToolCallPreviewField {
	m0 := &ToolCallPreviewField{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Value != nil {
		x.xxx_hidden_Content = &toolCallPreviewField_Value{b.Value}
	}
	if b.Prefix != nil {
		x.xxx_hidden_Content = &toolCallPreviewField_Prefix{*b.Prefix}
	}
	return m0
}

type case_ToolCallPreviewField_Content protoreflect.FieldNumber

func (x case_ToolCallPreviewField_Content) String() string {
	md := file_api_plugins_ui_v1_agent_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isToolCallPreviewField_Content interface {
	isToolCallPreviewField_Content()
}

type toolCallPreviewField_Value struct {
	Value *structpb.Value `protobuf:"bytes,2,opt,name=value,oneof"`
}

type toolCallPreviewField_Prefix struct {
	Prefix string `protobuf:"bytes,3,opt,name=prefix,oneof"`
}

func (*toolCallPreviewField_Value) isToolCallPreviewField_Content() {}

func (*toolCallPreviewField_Prefix) isToolCallPreviewField_Content() {}

// FinalToolCall carries exact arguments decoded at function-call completion.
type FinalToolCall struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CallId      *string                `protobuf:"bytes,1,opt,name=call_id,json=callId"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Position    int64                  `protobuf:"varint,3,opt,name=position"`
	xxx_hidden_Arguments   *structpb.Struct       `protobuf:"bytes,4,opt,name=arguments"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FinalToolCall) Reset() {
	*x = FinalToolCall{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalToolCall) ProtoMessage() {}

func (x *FinalToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FinalToolCall) GetCallId() string {
	if x != nil {
		if x.xxx_hidden_CallId != nil {
			return *x.xxx_hidden_CallId
		}
		return ""
	}
	return ""
}

func (x *FinalToolCall) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *FinalToolCall) GetPosition() int64 {
	if x != nil {
		return x.xxx_hidden_Position
	}
	return 0
}

func (x *FinalToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_Arguments
	}
	return nil
}

func (x *FinalToolCall) SetCallId(v string) {
	x.xxx_hidden_CallId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *FinalToolCall) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *FinalToolCall) SetPosition(v int64) {
	x.xxx_hidden_Position = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *FinalToolCall) SetArguments(v *structpb.Struct) {
	x.xxx_hidden_Arguments = v
}

func (x *FinalToolCall) HasCallId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FinalToolCall) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FinalToolCall) HasPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FinalToolCall) HasArguments() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Arguments != nil
}

func (x *FinalToolCall) ClearCallId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CallId = nil
}

func (x *FinalToolCall) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *FinalToolCall) ClearPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Position = 0
}

func (x *FinalToolCall) ClearArguments() {
	x.xxx_hidden_Arguments = nil
}

type FinalToolCall_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The provider-assigned tool call identifier.
	CallId *string
	// The finalized tool name.
	Name *string
	// The zero-based position in the model response.
	Position *int64
	// The decoded tool arguments.
	Arguments *structpb.Struct
}

func (b0 FinalToolCall_builder) Build() *FinalToolCall {
	m0 := &FinalToolCall{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CallId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_CallId = b.CallId
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Position != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Position = *b.Position
	}
	x.xxx_hidden_Arguments = b.Arguments
	return m0
}

// ModelContent carries one typed model content transition.
type ModelContent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        ModelContentType       `protobuf:"varint,1,opt,name=type,enum=glyph.plugins.ui.v1.ModelContentType"`
	xxx_hidden_Position    int64                  `protobuf:"varint,2,opt,name=position"`
	xxx_hidden_Text        *string                `protobuf:"bytes,3,opt,name=text"`
	xxx_hidden_Kind        ModelContentKind       `protobuf:"varint,4,opt,name=kind,enum=glyph.plugins.ui.v1.ModelContentKind"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ModelContent) Reset() {
	*x = ModelContent{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelContent) ProtoMessage() {}

func (x *ModelContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelContent) GetType() ModelContentType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return ModelContentType_MODEL_CONTENT_TYPE_UNSPECIFIED
}

func (x *ModelContent) GetPosition() int64 {
	if x != nil {
		return x.xxx_hidden_Position
	}
	return 0
}

func (x *ModelContent) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *ModelContent) GetKind() ModelContentKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Kind
		}
	}
	return ModelContentKind_MODEL_CONTENT_KIND_UNSPECIFIED
}

func (x *ModelContent) SetType(v ModelContentType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ModelContent) SetPosition(v int64) {
	x.xxx_hidden_Position = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ModelContent) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ModelContent) SetKind(v ModelContentKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ModelContent) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ModelContent) HasPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ModelContent) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ModelContent) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ModelContent) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = ModelContentType_MODEL_CONTENT_TYPE_UNSPECIFIED
}

func (x *ModelContent) ClearPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Position = 0
}

func (x *ModelContent) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Text = nil
}

func (x *ModelContent) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Kind = ModelContentKind_MODEL_CONTENT_KIND_UNSPECIFIED
}

type ModelContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The transition applied to this model content block.
	Type *ModelContentType
	// The zero-based content block position.
	Position *int64
	// The text delta carried by this transition.
	Text *string
	// The semantic kind of the content block.
	Kind *ModelContentKind
}

func (b0 ModelContent_builder) Build() *ModelContent {
	m0 := &ModelContent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Position != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Position = *b.Position
	}
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Text = b.Text
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Kind = *b.Kind
	}
	return m0
}

// ModelResponse carries typed terminal data and public text.
type ModelResponse struct {
	state                    protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Text          *string                  `protobuf:"bytes,1,opt,name=text"`
	xxx_hidden_Outcome       *string                  `protobuf:"bytes,2,opt,name=outcome"`
	xxx_hidden_ErrorMessage  *string                  `protobuf:"bytes,3,opt,name=error_message,json=errorMessage"`
	xxx_hidden_Provider      *string                  `protobuf:"bytes,4,opt,name=provider"`
	xxx_hidden_Model         *string                  `protobuf:"bytes,5,opt,name=model"`
	xxx_hidden_ResponseId    *string                  `protobuf:"bytes,6,opt,name=response_id,json=responseId"`
	xxx_hidden_Usage         *ModelUsage              `protobuf:"bytes,7,opt,name=usage"`
	xxx_hidden_Diagnostics   *[]*ModelDiagnostic      `protobuf:"bytes,8,rep,name=diagnostics"`
	xxx_hidden_Content       *[]*ModelResponseContent `protobuf:"bytes,9,rep,name=content"`
	xxx_hidden_ResponseModel *string                  `protobuf:"bytes,10,opt,name=response_model,json=responseModel"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ModelResponse) Reset() {
	*x = ModelResponse{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponse) ProtoMessage() {}

func (x *ModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelResponse) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) GetOutcome() string {
	if x != nil {
		if x.xxx_hidden_Outcome != nil {
			return *x.xxx_hidden_Outcome
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) GetProvider() string {
	if x != nil {
		if x.xxx_hidden_Provider != nil {
			return *x.xxx_hidden_Provider
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) GetModel() string {
	if x != nil {
		if x.xxx_hidden_Model != nil {
			return *x.xxx_hidden_Model
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) GetResponseId() string {
	if x != nil {
		if x.xxx_hidden_ResponseId != nil {
			return *x.xxx_hidden_ResponseId
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) GetUsage() *ModelUsage {
	if x != nil {
		return x.xxx_hidden_Usage
	}
	return nil
}

func (x *ModelResponse) GetDiagnostics() []*ModelDiagnostic {
	if x != nil {
		if x.xxx_hidden_Diagnostics != nil {
			return *x.xxx_hidden_Diagnostics
		}
	}
	return nil
}

func (x *ModelResponse) GetContent() []*ModelResponseContent {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
	}
	return nil
}

func (x *ModelResponse) GetResponseModel() string {
	if x != nil {
		if x.xxx_hidden_ResponseModel != nil {
			return *x.xxx_hidden_ResponseModel
		}
		return ""
	}
	return ""
}

func (x *ModelResponse) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *ModelResponse) SetOutcome(v string) {
	x.xxx_hidden_Outcome = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *ModelResponse) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *ModelResponse) SetProvider(v string) {
	x.xxx_hidden_Provider = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *ModelResponse) SetModel(v string) {
	x.xxx_hidden_Model = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *ModelResponse) SetResponseId(v string) {
	x.xxx_hidden_ResponseId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *ModelResponse) SetUsage(v *ModelUsage) {
	x.xxx_hidden_Usage = v
}

func (x *ModelResponse) SetDiagnostics(v []*ModelDiagnostic) {
	x.xxx_hidden_Diagnostics = &v
}

func (x *ModelResponse) SetContent(v []*ModelResponseContent) {
	x.xxx_hidden_Content = &v
}

func (x *ModelResponse) SetResponseModel(v string) {
	x.xxx_hidden_ResponseModel = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *ModelResponse) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ModelResponse) HasOutcome() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ModelResponse) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ModelResponse) HasProvider() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ModelResponse) HasModel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ModelResponse) HasResponseId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ModelResponse) HasUsage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Usage != nil
}

func (x *ModelResponse) HasResponseModel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ModelResponse) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Text = nil
}

func (x *ModelResponse) ClearOutcome() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Outcome = nil
}

func (x *ModelResponse) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ErrorMessage = nil
}

func (x *ModelResponse) ClearProvider() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Provider = nil
}

func (x *ModelResponse) ClearModel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Model = nil
}

func (x *ModelResponse) ClearResponseId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ResponseId = nil
}

func (x *ModelResponse) ClearUsage() {
	x.xxx_hidden_Usage = nil
}

func (x *ModelResponse) ClearResponseModel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_ResponseModel = nil
}

type ModelResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The finalized public response text.
	Text *string
	// The provider-neutral response outcome.
	Outcome *string
	// The safe user-visible terminal error.
	ErrorMessage *string
	// The provider that produced the response.
	Provider *string
	// The configured model identifier.
	Model *string
	// The provider-assigned response identifier.
	ResponseId *string
	// The provider-reported token usage.
	Usage *ModelUsage
	// The safe diagnostics produced while processing the response.
	Diagnostics []*ModelDiagnostic
	// The ordered finalized response content blocks.
	Content []*ModelResponseContent
	// The model identifier reported by the provider response.
	ResponseModel *string
}

func (b0 ModelResponse_builder) Build() *ModelResponse {
	m0 := &ModelResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Text = b.Text
	}
	if b.Outcome != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Outcome = b.Outcome
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	if b.Provider != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Provider = b.Provider
	}
	if b.Model != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Model = b.Model
	}
	if b.ResponseId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_ResponseId = b.ResponseId
	}
	x.xxx_hidden_Usage = b.Usage
	x.xxx_hidden_Diagnostics = &b.Diagnostics
	x.xxx_hidden_Content = &b.Content
	if b.ResponseModel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_ResponseModel = b.ResponseModel
	}
	return m0
}

// ModelResponseContent carries one ordered finalized text, refusal, or reasoning block.
type ModelResponseContent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        ModelContentKind       `protobuf:"varint,1,opt,name=kind,enum=glyph.plugins.ui.v1.ModelContentKind"`
	xxx_hidden_Text        *string                `protobuf:"bytes,2,opt,name=text"`
	xxx_hidden_ToolCall    *FinalToolCall         `protobuf:"bytes,3,opt,name=tool_call,json=toolCall"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ModelResponseContent) Reset() {
	*x = ModelResponseContent{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResponseContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponseContent) ProtoMessage() {}

func (x *ModelResponseContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelResponseContent) GetKind() ModelContentKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return ModelContentKind_MODEL_CONTENT_KIND_UNSPECIFIED
}

func (x *ModelResponseContent) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *ModelResponseContent) GetToolCall() *FinalToolCall {
	if x != nil {
		return x.xxx_hidden_ToolCall
	}
	return nil
}

func (x *ModelResponseContent) SetKind(v ModelContentKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ModelResponseContent) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ModelResponseContent) SetToolCall(v *FinalToolCall) {
	x.xxx_hidden_ToolCall = v
}

func (x *ModelResponseContent) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ModelResponseContent) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ModelResponseContent) HasToolCall() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ToolCall != nil
}

func (x *ModelResponseContent) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = ModelContentKind_MODEL_CONTENT_KIND_UNSPECIFIED
}

func (x *ModelResponseContent) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Text = nil
}

func (x *ModelResponseContent) ClearToolCall() {
	x.xxx_hidden_ToolCall = nil
}

type ModelResponseContent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The semantic kind of this finalized content block.
	Kind *ModelContentKind
	// The finalized content block text.
	Text *string
	// The finalized tool call when this content position invokes a tool.
	ToolCall *FinalToolCall
}

func (b0 ModelResponseContent_builder) Build() *ModelResponseContent {
	m0 := &ModelResponseContent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Text = b.Text
	}
	x.xxx_hidden_ToolCall = b.ToolCall
	return m0
}

// ModelUsage carries provider-reported token accounting.
type ModelUsage struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InputTokens       int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens"`
	xxx_hidden_OutputTokens      int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens"`
	xxx_hidden_CachedInputTokens int64                  `protobuf:"varint,3,opt,name=cached_input_tokens,json=cachedInputTokens"`
	xxx_hidden_CacheWriteTokens  int64                  `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens"`
	xxx_hidden_ReasoningTokens   int64                  `protobuf:"varint,5,opt,name=reasoning_tokens,json=reasoningTokens"`
	xxx_hidden_TotalTokens       int64                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ModelUsage) Reset() {
	*x = ModelUsage{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUsage) ProtoMessage() {}

func (x *ModelUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelUsage) GetInputTokens() int64 {
	if x != nil {
		return x.xxx_hidden_InputTokens
	}
	return 0
}

func (x *ModelUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.xxx_hidden_OutputTokens
	}
	return 0
}

func (x *ModelUsage) GetCachedInputTokens() int64 {
	if x != nil {
		return x.xxx_hidden_CachedInputTokens
	}
	return 0
}

func (x *ModelUsage) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.xxx_hidden_CacheWriteTokens
	}
	return 0
}

func (x *ModelUsage) GetReasoningTokens() int64 {
	if x != nil {
		return x.xxx_hidden_ReasoningTokens
	}
	return 0
}

func (x *ModelUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.xxx_hidden_TotalTokens
	}
	return 0
}

func (x *ModelUsage) SetInputTokens(v int64) {
	x.xxx_hidden_InputTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ModelUsage) SetOutputTokens(v int64) {
	x.xxx_hidden_OutputTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ModelUsage) SetCachedInputTokens(v int64) {
	x.xxx_hidden_CachedInputTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *ModelUsage) SetCacheWriteTokens(v int64) {
	x.xxx_hidden_CacheWriteTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ModelUsage) SetReasoningTokens(v int64) {
	x.xxx_hidden_ReasoningTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ModelUsage) SetTotalTokens(v int64) {
	x.xxx_hidden_TotalTokens = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ModelUsage) HasInputTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ModelUsage) HasOutputTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ModelUsage) HasCachedInputTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ModelUsage) HasCacheWriteTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ModelUsage) HasReasoningTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ModelUsage) HasTotalTokens() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ModelUsage) ClearInputTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InputTokens = 0
}

func (x *ModelUsage) ClearOutputTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OutputTokens = 0
}

func (x *ModelUsage) ClearCachedInputTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CachedInputTokens = 0
}

func (x *ModelUsage) ClearCacheWriteTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_CacheWriteTokens = 0
}

func (x *ModelUsage) ClearReasoningTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ReasoningTokens = 0
}

func (x *ModelUsage) ClearTotalTokens() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TotalTokens = 0
}

type ModelUsage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The number of input tokens processed.
	InputTokens *int64
	// The number of output tokens generated.
	OutputTokens *int64
	// The number of input tokens read from a cache.
	CachedInputTokens *int64
	// The number of input tokens written to a cache.
	CacheWriteTokens *int64
	// The number of output tokens used for reasoning.
	ReasoningTokens *int64
	// The total provider-reported token count.
	TotalTokens *int64
}

func (b0 ModelUsage_builder) Build() *ModelUsage {
	m0 := &ModelUsage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InputTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_InputTokens = *b.InputTokens
	}
	if b.OutputTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_OutputTokens = *b.OutputTokens
	}
	if b.CachedInputTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_CachedInputTokens = *b.CachedInputTokens
	}
	if b.CacheWriteTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_CacheWriteTokens = *b.CacheWriteTokens
	}
	if b.ReasoningTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_ReasoningTokens = *b.ReasoningTokens
	}
	if b.TotalTokens != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_TotalTokens = *b.TotalTokens
	}
	return m0
}

// ModelDiagnostic carries safe typed provider diagnostics.
type ModelDiagnostic struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code        *string                `protobuf:"bytes,1,opt,name=code"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ModelDiagnostic) Reset() {
	*x = ModelDiagnostic{}
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDiagnostic) ProtoMessage() {}

func (x *ModelDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugins_ui_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ModelDiagnostic) GetCode() string {
	if x != nil {
		if x.xxx_hidden_Code != nil {
			return *x.xxx_hidden_Code
		}
		return ""
	}
	return ""
}

func (x *ModelDiagnostic) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ModelDiagnostic) SetCode(v string) {
	x.xxx_hidden_Code = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ModelDiagnostic) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ModelDiagnostic) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ModelDiagnostic) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ModelDiagnostic) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = nil
}

func (x *ModelDiagnostic) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ModelDiagnostic_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The stable machine-readable diagnostic code.
	Code *string
	// The safe diagnostic message.
	Message *string
}

func (b0 ModelDiagnostic_builder) Build() *ModelDiagnostic {
	m0 := &ModelDiagnostic{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Code = b.Code
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_api_plugins_ui_v1_agent_proto protoreflect.FileDescriptor

const file_api_plugins_ui_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/plugins/ui/v1/agent.proto\x12\x13glyph.plugins.ui.v1\x1a\x1cgoogle/protobuf/struct.proto\"^\n" +
	"\x15ExtensionAvailability\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x14\n" +
	"\x05tools\x18\x02 \x03(\tR\x05tools\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xab\x06\n" +
	"\n" +
	"AgentEvent\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".glyph.plugins.ui.v1.LifecycleTypeR\x04type\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12O\n" +
	"\x10progress_channel\x18\x06 \x01(\x0e2$.glyph.plugins.ui.v1.ProgressChannelR\x0fprogressChannel\x12\x19\n" +
	"\bis_error\x18\a \x01(\bR\aisError\x12\x18\n" +
	"\aoutcome\x18\b \x01(\tR\aoutcome\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12E\n" +
	"\favailability\x18\n" +
	" \x01(\x0e2!.glyph.plugins.ui.v1.AvailabilityR\favailability\x12F\n" +
	"\rmodel_content\x18\v \x01(\v2!.glyph.plugins.ui.v1.ModelContentR\fmodelContent\x12I\n" +
	"\x0emodel_response\x18\f \x01(\v2\".glyph.plugins.ui.v1.ModelResponseR\rmodelResponse\x12P\n" +
	"\x11tool_call_preview\x18\r \x01(\v2$.glyph.plugins.ui.v1.ToolCallPreviewR\x0ftoolCallPreview\x12J\n" +
	"\x0ffinal_tool_call\x18\x0e \x01(\v2\".glyph.plugins.ui.v1.FinalToolCallR\rfinalToolCall\x12X\n" +
	"\x14tool_result_contents\x18\x0f \x03(\v2&.glyph.plugins.ui.v1.ToolResultContentR\x12toolResultContents\"r\n" +
	"\x11ToolResultContent\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12<\n" +
	"\x05image\x18\x02 \x01(\v2$.glyph.plugins.ui.v1.ToolResultImageH\x00R\x05imageB\t\n" +
	"\acontent\"D\n" +
	"\x0fToolResultImage\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xbf\x01\n" +
	"\x0fToolCallPreview\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x12 \n" +
	"\vprovisional\x18\x04 \x01(\bR\vprovisional\x12A\n" +
	"\x06fields\x18\x05 \x03(\v2).glyph.plugins.ui.v1.ToolCallPreviewFieldR\x06fields\"\x7f\n" +
	"\x14ToolCallPreviewField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueH\x00R\x05value\x12\x18\n" +
	"\x06prefix\x18\x03 \x01(\tH\x00R\x06prefixB\t\n" +
	"\acontent\"\x8f\x01\n" +
	"\rFinalToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x03R\bposition\x125\n" +
	"\targuments\x18\x04 \x01(\v2\x17.google.protobuf.StructR\targuments\"\xb4\x01\n" +
	"\fModelContent\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.glyph.plugins.ui.v1.ModelContentTypeR\x04type\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x129\n" +
	"\x04kind\x18\x04 \x01(\x0e2%.glyph.plugins.ui.v1.ModelContentKindR\x04kind\"\xa0\x03\n" +
	"\rModelResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1f\n" +
	"\vresponse_id\x18\x06 \x01(\tR\n" +
	"responseId\x125\n" +
	"\x05usage\x18\a \x01(\v2\x1f.glyph.plugins.ui.v1.ModelUsageR\x05usage\x12F\n" +
	"\vdiagnostics\x18\b \x03(\v2$.glyph.plugins.ui.v1.ModelDiagnosticR\vdiagnostics\x12C\n" +
	"\acontent\x18\t \x03(\v2).glyph.plugins.ui.v1.ModelResponseContentR\acontent\x12%\n" +
	"\x0eresponse_model\x18\n" +
	" \x01(\tR\rresponseModel\"\xa6\x01\n" +
	"\x14ModelResponseContent\x129\n" +
	"\x04kind\x18\x01 \x01(\x0e2%.glyph.plugins.ui.v1.ModelContentKindR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12?\n" +
	"\ttool_call\x18\x03 \x01(\v2\".glyph.plugins.ui.v1.FinalToolCallR\btoolCall\"\x80\x02\n" +
	"\n" +
	"ModelUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x03 \x01(\x03R\x11cachedInputTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x03R\x10cacheWriteTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x05 \x01(\x03R\x0freasoningTokens\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\"?\n" +
	"\x0fModelDiagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xd0\x01\n" +
	"\fAvailability\x12\x1c\n" +
	"\x18AVAILABILITY_UNSPECIFIED\x10\x00\x12(\n" +
	"$AVAILABILITY_CHECKING_AUTHENTICATION\x10\x01\x12\x1f\n" +
	"\x1bAVAILABILITY_AUTHENTICATING\x10\x02\x12&\n" +
	"\"AVAILABILITY_AUTHENTICATION_FAILED\x10\x03\x12\x15\n" +
	"\x11AVAILABILITY_IDLE\x10\x04\x12\x18\n" +
	"\x14AVAILABILITY_RUNNING\x10\x05*\x95\x01\n" +
	"\x10ModelContentKind\x12\"\n" +
	"\x1eMODEL_CONTENT_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MODEL_CONTENT_KIND_TEXT\x10\x01\x12 \n" +
	"\x1cMODEL_CONTENT_KIND_REASONING\x10\x02\x12\x1e\n" +
	"\x1aMODEL_CONTENT_KIND_REFUSAL\x10\x03*\x93\x01\n" +
	"\x10ModelContentType\x12\"\n" +
	"\x1eMODEL_CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MODEL_CONTENT_TYPE_START\x10\x01\x12!\n" +
	"\x1dMODEL_CONTENT_TYPE_TEXT_DELTA\x10\x02\x12\x1a\n" +
	"\x16MODEL_CONTENT_TYPE_END\x10\x03*\xe2\x04\n" +
	"\rLifecycleType\x12\x1e\n" +
	"\x1aLIFECYCLE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aLIFECYCLE_TYPE_AGENT_START\x10\x01\x12\x1d\n" +
	"\x19LIFECYCLE_TYPE_TURN_START\x10\x02\x12 \n" +
	"\x1cLIFECYCLE_TYPE_MESSAGE_START\x10\x03\x12\x1e\n" +
	"\x1aLIFECYCLE_TYPE_MESSAGE_END\x10\x04\x12'\n" +
	"#LIFECYCLE_TYPE_TOOL_EXECUTION_START\x10\x05\x12(\n" +
	"$LIFECYCLE_TYPE_TOOL_EXECUTION_UPDATE\x10\x06\x12%\n" +
	"!LIFECYCLE_TYPE_TOOL_EXECUTION_END\x10\a\x12\x1e\n" +
	"\x1aLIFECYCLE_TYPE_TOOL_RESULT\x10\b\x12\x1b\n" +
	"\x17LIFECYCLE_TYPE_TURN_END\x10\t\x12\x1c\n" +
	"\x18LIFECYCLE_TYPE_AGENT_END\x10\n" +
	"\x12&\n" +
	"\"LIFECYCLE_TYPE_MODEL_CONTENT_START\x10\v\x12#\n" +
	"\x1fLIFECYCLE_TYPE_MODEL_TEXT_DELTA\x10\f\x12$\n" +
	" LIFECYCLE_TYPE_MODEL_CONTENT_END\x10\r\x12\"\n" +
	"\x1eLIFECYCLE_TYPE_TOOL_CALL_START\x10\x0e\x12\"\n" +
	"\x1eLIFECYCLE_TYPE_TOOL_CALL_DELTA\x10\x0f\x12 \n" +
	"\x1cLIFECYCLE_TYPE_TOOL_CALL_END\x10\x10*\x8a\x01\n" +
	"\x0fProgressChannel\x12 \n" +
	"\x1cPROGRESS_CHANNEL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROGRESS_CHANNEL_STATUS\x10\x01\x12\x1b\n" +
	"\x17PROGRESS_CHANNEL_STDOUT\x10\x02\x12\x1b\n" +
	"\x17PROGRESS_CHANNEL_STDERR\x10\x03B/Z-github.com/n-r-w/glyph/pkg/plugins/ui/v1;uiv1b\beditionsp\xe8\a"

var file_api_plugins_ui_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_plugins_ui_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_plugins_ui_v1_agent_proto_goTypes = []any{
	(Availability)(0),             // 0: glyph.plugins.ui.v1.Availability
	(ModelContentKind)(0),         // 1: glyph.plugins.ui.v1.ModelContentKind
	(ModelContentType)(0),         // 2: glyph.plugins.ui.v1.ModelContentType
	(LifecycleType)(0),            // 3: glyph.plugins.ui.v1.LifecycleType
	(ProgressChannel)(0),          // 4: glyph.plugins.ui.v1.ProgressChannel
	(*ExtensionAvailability)(nil), // 5: glyph.plugins.ui.v1.ExtensionAvailability
	(*AgentEvent)(nil),            // 6: glyph.plugins.ui.v1.AgentEvent
	(*ToolResultContent)(nil),     // 7: glyph.plugins.ui.v1.ToolResultContent
	(*ToolResultImage)(nil),       // 8: glyph.plugins.ui.v1.ToolResultImage
	(*ToolCallPreview)(nil),       // 9: glyph.plugins.ui.v1.ToolCallPreview
	(*ToolCallPreviewField)(nil),  // 10: glyph.plugins.ui.v1.ToolCallPreviewField
	(*FinalToolCall)(nil),         // 11: glyph.plugins.ui.v1.FinalToolCall
	(*ModelContent)(nil),          // 12: glyph.plugins.ui.v1.ModelContent
	(*ModelResponse)(nil),         // 13: glyph.plugins.ui.v1.ModelResponse
	(*ModelResponseContent)(nil),  // 14: glyph.plugins.ui.v1.ModelResponseContent
	(*ModelUsage)(nil),            // 15: glyph.plugins.ui.v1.ModelUsage
	(*ModelDiagnostic)(nil),       // 16: glyph.plugins.ui.v1.ModelDiagnostic
	(*structpb.Value)(nil),        // 17: google.protobuf.Value
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
}
var file_api_plugins_ui_v1_agent_proto_depIdxs = []int32{
	3,  // 0: glyph.plugins.ui.v1.AgentEvent.type:type_name -> glyph.plugins.ui.v1.LifecycleType
	4,  // 1: glyph.plugins.ui.v1.AgentEvent.progress_channel:type_name -> glyph.plugins.ui.v1.ProgressChannel
	0,  // 2: glyph.plugins.ui.v1.AgentEvent.availability:type_name -> glyph.plugins.ui.v1.Availability
	12, // 3: glyph.plugins.ui.v1.AgentEvent.model_content:type_name -> glyph.plugins.ui.v1.ModelContent
	13, // 4: glyph.plugins.ui.v1.AgentEvent.model_response:type_name -> glyph.plugins.ui.v1.ModelResponse
	9,  // 5: glyph.plugins.ui.v1.AgentEvent.tool_call_preview:type_name -> glyph.plugins.ui.v1.ToolCallPreview
	11, // 6: glyph.plugins.ui.v1.AgentEvent.final_tool_call:type_name -> glyph.plugins.ui.v1.FinalToolCall
	7,  // 7: glyph.plugins.ui.v1.AgentEvent.tool_result_contents:type_name -> glyph.plugins.ui.v1.ToolResultContent
	8,  // 8: glyph.plugins.ui.v1.ToolResultContent.image:type_name -> glyph.plugins.ui.v1.ToolResultImage
	10, // 9: glyph.plugins.ui.v1.ToolCallPreview.fields:type_name -> glyph.plugins.ui.v1.ToolCallPreviewField
	17, // 10: glyph.plugins.ui.v1.ToolCallPreviewField.value:type_name -> google.protobuf.Value
	18, // 11: glyph.plugins.ui.v1.FinalToolCall.arguments:type_name -> google.protobuf.Struct
	2,  // 12: glyph.plugins.ui.v1.ModelContent.type:type_name -> glyph.plugins.ui.v1.ModelContentType
	1,  // 13: glyph.plugins.ui.v1.ModelContent.kind:type_name -> glyph.plugins.ui.v1.ModelContentKind
	15, // 14: glyph.plugins.ui.v1.ModelResponse.usage:type_name -> glyph.plugins.ui.v1.ModelUsage
	16, // 15: glyph.plugins.ui.v1.ModelResponse.diagnostics:type_name -> glyph.plugins.ui.v1.ModelDiagnostic
	14, // 16: glyph.plugins.ui.v1.ModelResponse.content:type_name -> glyph.plugins.ui.v1.ModelResponseContent
	1,  // 17: glyph.plugins.ui.v1.ModelResponseContent.kind:type_name -> glyph.plugins.ui.v1.ModelContentKind
	11, // 18: glyph.plugins.ui.v1.ModelResponseContent.tool_call:type_name -> glyph.plugins.ui.v1.FinalToolCall
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_plugins_ui_v1_agent_proto_init() }
func file_api_plugins_ui_v1_agent_proto_init() {
	if File_api_plugins_ui_v1_agent_proto != nil {
		return
	}
	file_api_plugins_ui_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*toolResultContent_Text)(nil),
		(*toolResultContent_Image)(nil),
	}
	file_api_plugins_ui_v1_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*toolCallPreviewField_Value)(nil),
		(*toolCallPreviewField_Prefix)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugins_ui_v1_agent_proto_rawDesc), len(file_api_plugins_ui_v1_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_plugins_ui_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_plugins_ui_v1_agent_proto_depIdxs,
		EnumInfos:         file_api_plugins_ui_v1_agent_proto_enumTypes,
		MessageInfos:      file_api_plugins_ui_v1_agent_proto_msgTypes,
	}.Build()
	File_api_plugins_ui_v1_agent_proto = out.File
	file_api_plugins_ui_v1_agent_proto_goTypes = nil
	file_api_plugins_ui_v1_agent_proto_depIdxs = nil
}
