// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=sessioncontrol
//

// Package sessioncontrol is a generated GoMock package.
package sessioncontrol

import (
	context "context"
	reflect "reflect"

	session "github.com/n-r-w/glyph/host/internal/domain/session"
	gomock "go.uber.org/mock/gomock"
)

// MockActiveSessions is a mock of ActiveSessions interface.
type MockActiveSessions struct {
	ctrl     *gomock.Controller
	recorder *MockActiveSessionsMockRecorder
	isgomock struct{}
}

// MockActiveSessionsMockRecorder is the mock recorder for MockActiveSessions.
type MockActiveSessionsMockRecorder struct {
	mock *MockActiveSessions
}

// NewMockActiveSessions creates a new mock instance.
func NewMockActiveSessions(ctrl *gomock.Controller) *MockActiveSessions {
	mock := &MockActiveSessions{ctrl: ctrl}
	mock.recorder = &MockActiveSessionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActiveSessions) EXPECT() *MockActiveSessionsMockRecorder {
	return m.recorder
}

// ActiveInfo mocks base method.
func (m *MockActiveSessions) ActiveInfo() session.Info {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveInfo")
	ret0, _ := ret[0].(session.Info)
	return ret0
}

// ActiveInfo indicates an expected call of ActiveInfo.
func (mr *MockActiveSessionsMockRecorder) ActiveInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveInfo", reflect.TypeOf((*MockActiveSessions)(nil).ActiveInfo))
}

// CreateActive mocks base method.
func (m *MockActiveSessions) CreateActive(arg0 context.Context) (session.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActive", arg0)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActive indicates an expected call of CreateActive.
func (mr *MockActiveSessionsMockRecorder) CreateActive(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActive", reflect.TypeOf((*MockActiveSessions)(nil).CreateActive), arg0)
}

// ListStored mocks base method.
func (m *MockActiveSessions) ListStored(arg0 context.Context) ([]session.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStored", arg0)
	ret0, _ := ret[0].([]session.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStored indicates an expected call of ListStored.
func (mr *MockActiveSessionsMockRecorder) ListStored(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStored", reflect.TypeOf((*MockActiveSessions)(nil).ListStored), arg0)
}

// ResumeActive mocks base method.
func (m *MockActiveSessions) ResumeActive(arg0 context.Context, arg1 session.ID) (session.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeActive", arg0, arg1)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeActive indicates an expected call of ResumeActive.
func (mr *MockActiveSessionsMockRecorder) ResumeActive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeActive", reflect.TypeOf((*MockActiveSessions)(nil).ResumeActive), arg0, arg1)
}

// SetActiveName mocks base method.
func (m *MockActiveSessions) SetActiveName(arg0 context.Context, arg1 string) (session.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveName", arg0, arg1)
	ret0, _ := ret[0].(session.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActiveName indicates an expected call of SetActiveName.
func (mr *MockActiveSessionsMockRecorder) SetActiveName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveName", reflect.TypeOf((*MockActiveSessions)(nil).SetActiveName), arg0, arg1)
}

// MockOperationGate is a mock of OperationGate interface.
type MockOperationGate struct {
	ctrl     *gomock.Controller
	recorder *MockOperationGateMockRecorder
	isgomock struct{}
}

// MockOperationGateMockRecorder is the mock recorder for MockOperationGate.
type MockOperationGateMockRecorder struct {
	mock *MockOperationGate
}

// NewMockOperationGate creates a new mock instance.
func NewMockOperationGate(ctrl *gomock.Controller) *MockOperationGate {
	mock := &MockOperationGate{ctrl: ctrl}
	mock.recorder = &MockOperationGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationGate) EXPECT() *MockOperationGateMockRecorder {
	return m.recorder
}

// TryAcquire mocks base method.
func (m *MockOperationGate) TryAcquire() (func(), bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquire")
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// TryAcquire indicates an expected call of TryAcquire.
func (mr *MockOperationGateMockRecorder) TryAcquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquire", reflect.TypeOf((*MockOperationGate)(nil).TryAcquire))
}
