// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=interfaces_mock.go -package=interactions
//

// Package interactions is a generated GoMock package.
package interactions

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrowser is a mock of Browser interface.
type MockBrowser struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserMockRecorder
	isgomock struct{}
}

// MockBrowserMockRecorder is the mock recorder for MockBrowser.
type MockBrowserMockRecorder struct {
	mock *MockBrowser
}

// NewMockBrowser creates a new mock instance.
func NewMockBrowser(ctrl *gomock.Controller) *MockBrowser {
	mock := &MockBrowser{ctrl: ctrl}
	mock.recorder = &MockBrowserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowser) EXPECT() *MockBrowserMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockBrowser) Open(ctx context.Context, authorizationURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, authorizationURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockBrowserMockRecorder) Open(ctx, authorizationURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrowser)(nil).Open), ctx, authorizationURL)
}
