// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../sdk/plugins/ui/v1/service.go
//
// Generated by this command:
//
//	mockgen -source=../../../sdk/plugins/ui/v1/service.go -destination=ui_interfaces_mock.go -package=pluginmock -mock_names=Service=MockUIService,InitializeOperation=MockUIInitializeOperation
//

// Package pluginmock is a generated GoMock package.
package pluginmock

import (
	context "context"
	reflect "reflect"

	uiv1 "github.com/n-r-w/glyph/pkg/plugins/ui/v1"
	uiv10 "github.com/n-r-w/glyph/sdk/plugins/ui/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockUIService is a mock of Service interface.
type MockUIService struct {
	ctrl     *gomock.Controller
	recorder *MockUIServiceMockRecorder
	isgomock struct{}
}

// MockUIServiceMockRecorder is the mock recorder for MockUIService.
type MockUIServiceMockRecorder struct {
	mock *MockUIService
}

// NewMockUIService creates a new mock instance.
func NewMockUIService(ctrl *gomock.Controller) *MockUIService {
	mock := &MockUIService{ctrl: ctrl}
	mock.recorder = &MockUIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUIService) EXPECT() *MockUIServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockUIService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockUIServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUIService)(nil).Close))
}

// PrepareInitialize mocks base method.
func (m *MockUIService) PrepareInitialize(arg0 context.Context, arg1 *uiv1.Initialization) (uiv10.InitializeOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareInitialize", arg0, arg1)
	ret0, _ := ret[0].(uiv10.InitializeOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareInitialize indicates an expected call of PrepareInitialize.
func (mr *MockUIServiceMockRecorder) PrepareInitialize(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareInitialize", reflect.TypeOf((*MockUIService)(nil).PrepareInitialize), arg0, arg1)
}

// Run mocks base method.
func (m *MockUIService) Run(arg0 context.Context, arg1 *uiv10.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockUIServiceMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockUIService)(nil).Run), arg0, arg1)
}

// MockUIInitializeOperation is a mock of InitializeOperation interface.
type MockUIInitializeOperation struct {
	ctrl     *gomock.Controller
	recorder *MockUIInitializeOperationMockRecorder
	isgomock struct{}
}

// MockUIInitializeOperationMockRecorder is the mock recorder for MockUIInitializeOperation.
type MockUIInitializeOperationMockRecorder struct {
	mock *MockUIInitializeOperation
}

// NewMockUIInitializeOperation creates a new mock instance.
func NewMockUIInitializeOperation(ctrl *gomock.Controller) *MockUIInitializeOperation {
	mock := &MockUIInitializeOperation{ctrl: ctrl}
	mock.recorder = &MockUIInitializeOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUIInitializeOperation) EXPECT() *MockUIInitializeOperationMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockUIInitializeOperation) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockUIInitializeOperationMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockUIInitializeOperation)(nil).Release))
}

// Run mocks base method.
func (m *MockUIInitializeOperation) Run(arg0 context.Context) (*uiv1.Initialized, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(*uiv1.Initialized)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockUIInitializeOperationMockRecorder) Run(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockUIInitializeOperation)(nil).Run), arg0)
}
