// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=extension
//

// Package extension is a generated GoMock package.
package extension

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadTool is a mock of ReadTool interface.
type MockReadTool struct {
	ctrl     *gomock.Controller
	recorder *MockReadToolMockRecorder
	isgomock struct{}
}

// MockReadToolMockRecorder is the mock recorder for MockReadTool.
type MockReadToolMockRecorder struct {
	mock *MockReadTool
}

// NewMockReadTool creates a new mock instance.
func NewMockReadTool(ctrl *gomock.Controller) *MockReadTool {
	mock := &MockReadTool{ctrl: ctrl}
	mock.recorder = &MockReadToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadTool) EXPECT() *MockReadToolMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockReadTool) Read(arg0 context.Context, arg1 string, arg2, arg3 uint) (ReadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(ReadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReadToolMockRecorder) Read(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReadTool)(nil).Read), arg0, arg1, arg2, arg3)
}

// MockWriteTool is a mock of WriteTool interface.
type MockWriteTool struct {
	ctrl     *gomock.Controller
	recorder *MockWriteToolMockRecorder
	isgomock struct{}
}

// MockWriteToolMockRecorder is the mock recorder for MockWriteTool.
type MockWriteToolMockRecorder struct {
	mock *MockWriteTool
}

// NewMockWriteTool creates a new mock instance.
func NewMockWriteTool(ctrl *gomock.Controller) *MockWriteTool {
	mock := &MockWriteTool{ctrl: ctrl}
	mock.recorder = &MockWriteToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteTool) EXPECT() *MockWriteToolMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockWriteTool) Write(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockWriteToolMockRecorder) Write(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWriteTool)(nil).Write), arg0, arg1, arg2)
}

// MockEditTool is a mock of EditTool interface.
type MockEditTool struct {
	ctrl     *gomock.Controller
	recorder *MockEditToolMockRecorder
	isgomock struct{}
}

// MockEditToolMockRecorder is the mock recorder for MockEditTool.
type MockEditToolMockRecorder struct {
	mock *MockEditTool
}

// NewMockEditTool creates a new mock instance.
func NewMockEditTool(ctrl *gomock.Controller) *MockEditTool {
	mock := &MockEditTool{ctrl: ctrl}
	mock.recorder = &MockEditToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditTool) EXPECT() *MockEditToolMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockEditTool) Edit(arg0 context.Context, arg1 string, arg2 []Replacement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockEditToolMockRecorder) Edit(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockEditTool)(nil).Edit), arg0, arg1, arg2)
}

// MockBashTool is a mock of BashTool interface.
type MockBashTool struct {
	ctrl     *gomock.Controller
	recorder *MockBashToolMockRecorder
	isgomock struct{}
}

// MockBashToolMockRecorder is the mock recorder for MockBashTool.
type MockBashToolMockRecorder struct {
	mock *MockBashTool
}

// NewMockBashTool creates a new mock instance.
func NewMockBashTool(ctrl *gomock.Controller) *MockBashTool {
	mock := &MockBashTool{ctrl: ctrl}
	mock.recorder = &MockBashToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBashTool) EXPECT() *MockBashToolMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBashTool) Execute(arg0 context.Context, arg1 string, arg2 func(BashProgress) error) (BashResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1, arg2)
	ret0, _ := ret[0].(BashResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockBashToolMockRecorder) Execute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBashTool)(nil).Execute), arg0, arg1, arg2)
}

// MockSearchTool is a mock of SearchTool interface.
type MockSearchTool struct {
	ctrl     *gomock.Controller
	recorder *MockSearchToolMockRecorder
	isgomock struct{}
}

// MockSearchToolMockRecorder is the mock recorder for MockSearchTool.
type MockSearchToolMockRecorder struct {
	mock *MockSearchTool
}

// NewMockSearchTool creates a new mock instance.
func NewMockSearchTool(ctrl *gomock.Controller) *MockSearchTool {
	mock := &MockSearchTool{ctrl: ctrl}
	mock.recorder = &MockSearchToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchTool) EXPECT() *MockSearchToolMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockSearchTool) Find(arg0 context.Context, arg1 FindArguments) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSearchToolMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSearchTool)(nil).Find), arg0, arg1)
}

// Grep mocks base method.
func (m *MockSearchTool) Grep(arg0 context.Context, arg1 GrepArguments) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grep", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grep indicates an expected call of Grep.
func (mr *MockSearchToolMockRecorder) Grep(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grep", reflect.TypeOf((*MockSearchTool)(nil).Grep), arg0, arg1)
}

// List mocks base method.
func (m *MockSearchTool) List(arg0 context.Context, arg1 ListArguments) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSearchToolMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSearchTool)(nil).List), arg0, arg1)
}
